/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * http://www.gnu.org/copyleft/gpl.html
 */
package net.l1j.server.model.item;

public class ItemId {
	//public static final int SPELLBOOK_OF_THE_CURSED = ?; //受詛咒的魔法書
	//public static final int SPELLBOOK_OF_THE_HIGHPRIEST = ?; //神官魔法書
        public static final int SCROLL_OF_EQUIPMENT_PROTECTION = 30001; //裝備保護捲軸 ?
	public static final int BIBLE_OF_ATONEMENT = 30002; //贖罪聖書
	public static final int GIFT_OF_LOVE_BOX = 30101; //愛的禮物盒 period 28d / 1w > 1
	/* 11週年禮物箱 可開出
	 * 對武器施法的卷軸(1),對盔甲施法的卷軸(1),受祝福的對武器施法的卷軸(1),受祝福的對盔甲施法的卷軸(1),地之武器強化卷軸(1),水之武器強化卷軸(1),火之武器強化卷軸(1),風之武器強化卷軸(1),
	 * 古代的卷軸(1),亞克變身卷軸(1),加速袋(1),變身鱗片袋(1),變身石袋(1),濃縮終極體力恢復劑(3)
	 */
	//public static final int GIFT_OF_11TH_ANNIVERSARY_CHEST = ?; //11週年禮物箱
	//public static final int BAG_OF_STONE_POLYMORPH = ?; //變身石袋 > 開出其中一樣 變身石：拉曼斯(3)STONE_OF_LAMIAS_POLYMORPH,變身石：安迪斯(3)STONE_OF_ENDIAS_POLYMORPH,變身石：艾迪爾(3)STONE_OF_EDEA_POLYMORP
	//public static final int BAG_OF_SCALES_POLYMORPH = ?; //變身鱗片袋 > 開出其中一樣 幻之鱗(3),恨之鱗(3),暗之鱗(3),叛之鱗(3),火之鱗(3)
	//public static final int BAG_OF_POLYMORPH = ?; //變身袋 > 開出其中一樣 變身石：拉曼斯(3),變身石：安迪斯(3),變身石：艾迪爾(3),變形卷軸(3),恨之鱗(3),暗之鱗(3),叛之鱗(3),火之鱗(3)
	//public static final int BAG_OF_ACCELERATION = ?; //加速袋 > 開出其中一樣 精靈餅乾(3),強化自我加速藥水(3),勇敢藥水(3),惡魔之血(3),生命之樹果實(3)
	//public static final int SOCK_OF_CHRISTMAS = ?; //聖誕襪
	
	public static final int BOX_OF_BIBLE_ATONEMENT = 30201; //贖罪聖書包 1 > 贖罪聖書 1
	public static final int BOX_OF_STR_TShirt = 30202; //究極力量T恤箱子
	public static final int BOX_OF_DEX_TShirt = 30203; //究極敏捷T恤箱子
	public static final int BOX_OF_CHA_TShirt = 30204; //究極魅力T恤箱子
	public static final int BOX_OF_INT_TShirt = 30205; //究極智力T恤箱子
	public static final int BOX_OF_HP_TShirt = 30206; //究極體力T恤箱子
	public static final int BOX_OF_MP_TShirt = 30207; //究極魔力T恤箱子
	public static final int BOX_OF_StunResistance_TShirt = 30208; //究極抗昏迷T恤箱子
	public static final int BOX_OF_HoldResistance_TShirt = 30209; //究極抗支撐T恤箱子
	public static final int BOX_OF_MAGICResistance_TShirt = 30210; //究極抗魔法T恤箱子
	public static final int BOX_OF_SEVEN_DYE = 30211; //7色染料箱
	public static final int RED_DYE_ForTShirts = 30212; //紅色T恤染料
	public static final int ORANGE_DYE_ForTShirts = 30213; //橙色T恤染料
	public static final int YELLOW_DYE__ForTShirts = 30214; //黃色T恤染料
	public static final int GREEN_DYE_ForTShirts = 30215; //綠色T恤染料
	public static final int BLUE_DYE_ForTShirts = 30216; //藍色T恤染料
	public static final int NAVY_DYE_ForTShirts = 30217; //深藍色T恤染料
	public static final int PURPLE_DYE_ForTShirts = 30218; //紫色T恤染料
	//public static final int ENERGY_SOUP_A_SET = ?; //神力禮盒A > 打開隨機獲得一種 150%神力藥水(2),175%神力藥水(2),200%神力藥水(2),225%神力藥水(2),250%神力藥水(2)
	//public static final int ENERGY_SOUP_B_SET = ?; //神力禮盒B > 打開隨機獲得一種 150%神力藥水(2),175%神力藥水(2),200%神力藥水(2),225%神力藥水(2),250%神力藥水(2)
	//public static final int BOX_OF_IRON_OTHERWORLDLY = ?; //異界鐵盒
	//public static final int MACROSS_CHEST = ?; //超時空寶箱
	//public static final int GIFT_MAZU = ?; //媽祖禮盒
	//public static final int GIFT_OF_SURPRISE_CHEST = ; //驚喜禮盒
	//public static final int LUCKY_POUCH = ?; //福袋
	//public static final int BOX_SCROLL_OF_ENCHANT_ACCESSORY = ?; //飾品強化卷軸箱子
	/* Matic Doll */
	public static final int MAGIC_BAG_OF_Arka = 31000; //魔法娃娃的袋子 > 41247
	public static final int MAGIC_DOLL_OF_SeaDancer = 31001; //魔法娃娃：希爾黛絲
	public static final int MAGIC_DOLL_OF_Yeti = 31002; //魔法娃娃：雪怪
	public static final int MAGIC_DOLL_OF_Ramia = 31003; //魔法娃娃：蛇女
	public static final int MAGIC_DOLL_OF_Cockatrice = 31004; //魔法娃娃：亞力安
	public static final int MAGIC_DOLL_OF_Scarecrow = 31005; //魔法娃娃：稻草人
	public static final int MAGIC_DOLL_OF_Spartoi = 31006; //魔法娃娃：史巴托
	public static final int MAGIC_DOLL_OF_Lich = 31007; //魔法娃娃：巫妖
	public static final int IRON_GUILD_MAGIC_DOLL_OF_Yeti = 31008; //鐵門公會 魔法娃娃：雪怪
	public static final int MAGIC_DOLL_OF_Princess = 31009; //魔法娃娃：公主
	public static final int MAGIC_DOLL_OF_Bugbear = 31010; //魔法娃娃：肥肥 > 41248
	public static final int MAGIC_DOLL_OF_Succubus = 31011; //魔法娃娃：小思克巴 > 41249
	public static final int MAGIC_DOLL_OF_Werewolf = 31012; //魔法娃娃：野狼寶寶 > 41250
	public static final int MAGIC_DOLL_OF_Elder = 31013; //魔法娃娃：長老 > 49037
	public static final int MAGIC_DOLL_OF_Crustacean = 31014; //魔法娃娃：奎斯坦修 > 49038
	public static final int MAGIC_DOLL_OF_StoneGolem = 31015; //魔法娃娃：石頭高崙 > 49039
	public static final int MAGIC_Toy_BOX = 31016; //魔法娃娃收藏盒(new) 隨機：野狼寶寶,肥肥,小思克巴,長老,奎斯坦修,石頭高崙,雪怪,亞力安
	public static final int BAG_OF_MAGIC_DOLL_SeaDancer = 31017; //魔法娃娃：希爾黛斯包(new) > 魔法娃娃：希爾黛
	public static final int BOX_OF_MAGIC_DOLL_Spartoi = 31018; //魔法娃娃：史巴托箱子(new) > 魔法娃娃：史巴托
	public static final int BOX_OF_MAGIC_DOLL_Ramia = 31019; //魔法娃娃：蛇女箱子(new) > 魔法娃娃：蛇女
	public static final int BOX_OF_MAGIC_DOLL_Scarecrow = 31020; //魔法娃娃：稻草人箱子(new) > 魔法娃娃：稻草人
	public static final int BOX_OF_MAGIC_DOLL_Ettin = 31021; //魔法娃娃：阿魯巴箱子(new) > 魔法娃娃：阿魯巴
	public static final int MAGIC_DOLL_OF_Bugbear_ILLUSION = 31022; //幻象食人妖精魔法娃娃(new) 效果時間： 召喚1800秒 可以召喚出肥肥，每次召喚消耗50個魔法結晶體 現有負重 /1.2 中國「魔法娃娃租賃商」的服務道具
	public static final int MAGIC_DOLL_OF_Werewolf_ILLUSION = 31023; //幻象狼人魔法娃娃(new) 效果時間： 召喚1800秒 可以召喚出野狼寶寶，每次召喚消耗50個魔法結晶體 3%機率，攻擊力+15 中國「魔法娃娃租賃商」的服務道具
	public static final int MAGIC_DOLL_OF_Succubus_ILLUSION = 31024; //幻象思克巴魔法娃娃(new) 效果時間： 召喚1800秒 可以召喚出小思克巴，每次召喚消耗50個魔法結晶體 每64秒，魔力恢復15 中國「魔法娃娃租賃商」的服務道具
	
	public static final int LAMP = 40001;
	public static final int LANTERN = 40002;
	public static final int LANTERN_OIL = 40003;
	public static final int MAGIC_LANTERN = 40004;
	public static final int CANDLE = 40005;
	public static final int WAND_OF_ConjureMonster = 40006;
	public static final int WAND_OF_CALLINGLIGHTNING = 40007;
	public static final int WAND_OF_POLYMORPH = 40008;
	public static final int WAND_OF_BLINK = 40009;
	public static final int POTION_OF_LESSER_HEAL  = 40010; //POTION_OF_HEALING
	public static final int POTION_OF_HEAL  = 40011; //POTION_OF_EXTRA_HEALING
	public static final int POTION_OF_GREATER_HEAL = 40012;
	public static final int POTION_OF_HASTE = 40013; // 自我加速藥水
	public static final int POTION_OF_BRAVERY = 40014; // 勇敢藥水
	public static final int POTION_OF_MANA_Recovery = 40015; // 加速魔力回復藥水
	public static final int POTION_OF_WISDOM = 40016; // 慎重藥水
	public static final int POTION_OF_CURE_POISON = 40017;
	public static final int POTION_OF_GREATER_HASTE = 40018; // 強化自我加速藥水
	public static final int POTION_OF_CONDENSED_LESSER_HEAL = 40019; //CONDENSED_POTION_OF_HEALING
	public static final int POTION_OF_CONDENSED_HEAL = 40020; //CONDENSED_POTION_OF_EXTRA_HEALING
	public static final int POTION_OF_CONDENSED_GREATER_HEAL = 40021; //CONDENSED_POTION_OF_GREATER_HEALING
	public static final int POTION_OF_ANCIENT_LESSER_HEAL = 40022;
	public static final int POTION_OF_ANCIENT_HEAL = 40023;
	public static final int POTION_OF_ANCIENT_GREATER_HEAL = 40024;
	public static final int POTION_OF_Blindness = 40025; //POTION_OF_BLINDNESS
	public static final int JUICE_OF_BANANA = 40026;
	public static final int JUICE_OF_ORANGE = 40027;
	public static final int JUICE_OF_APPLE = 40028;
	public static final int IT_HEAL_POTION = 40029;
	public static final int IT_HASTE_POTION = 40030;
	public static final int BLOOD_OF_DEVIL = 40031;
	public static final int BLESS_OF_EVA = 40032;
	public static final int Elixir_STR = 40033;
	public static final int Elixir_CON = 40034;
	public static final int Elixir_DEX = 40035;
	public static final int Elixir_INT = 40036;
	public static final int Elixir_WIS = 40037;
	public static final int Elixir_CHA = 40038;
	public static final int WINE = 40039; //紅酒
	public static final int WHISKEY = 40040; //威士忌
	public static final int SCALE_OF_Mermaid = 40041; //人魚之鱗
	public static final int POTION_OF_MentalAbility = 40042;
	public static final int LIVER_OF_RABBIT = 40043;
	public static final int DIAMOND = 40044;
	public static final int RUBY = 40045;
	public static final int SAPPHIRE = 40046;
	public static final int EMERALD = 40047;
	public static final int HIGHTQUALITY_DIAMOND = 40048;
	public static final int HIGHTQUALITY_RUBY = 40049;
	public static final int HIGHTQUALITY_SAPPHIRE = 40050;
	public static final int HIGHTQUALITY_EMERALD = 40051;
	public static final int HIGHESTQUALITY_DIAMOND = 40052;
	public static final int HIGHESTQUALITY_RUBY = 40053;
	public static final int HIGHESTQUALITY_SAPPHIRE = 40054;
	public static final int HIGHESTQUALITY_EMERALD = 40055;
	public static final int MEAT = 40056;
	public static final int MEAT_OF_FLOATING_EYES = 40057;
	public static final int BROWN_PIECE_OF_BREAD = 40058;
	public static final int EGG = 40059;
	public static final int CARROT = 40060;
	public static final int LEMON = 40061;
	public static final int BANANA = 40062;
	public static final int CHOCOLATE_OF_VALENTINES_DAY = 40063;
	public static final int APPLE = 40064;
	public static final int CANDY = 40065;
	public static final int SONGPYON = 40066;
	public static final int GREENSONGPYON = 40067;
	public static final int ELVEN_WAFER = 40068;
	public static final int ORANGE = 40069;
	public static final int FRUIT_OF_Evolution = 40070;
	public static final int BURNTPIECE_OF_Bread = 40071;
	public static final int PANCAKE = 40072;
	public static final int CHOCOLATE_OF_WHITE_VALENTINES_DAY = 40073;
	public static final int SCROLL_OF_ENCHANT_ARMOR = 40074;
	public static final int SCROLL_OF_DESTROY_ARMOR = 40075;
	public static final int SCROLL_OF_ANCIENT = 40076;
	public static final int SCROLL_OF_ANCIENTS_Alchemy = 40077; //古代人的鍊金術卷軸
	public static final int SCROLL_OF_ANCIENTS_MAGIC = 40078; //古代人的咒術卷軸
	public static final int SCROLL_OF_Escape = 40079;
	public static final int SCROLL_OF_ReturnGludinTown = 40080;
	public static final int SCROLL_OF_ReturnGiranCity = 40081;
	public static final int SCROLL_OF_ReturnSingingIsland = 40082;
	public static final int SCROLL_OF_ReturnCavern = 40083; //大空洞傳送卷軸 跟 大洞穴抵抗軍地區傳送卷軸 位置一樣？
	public static final int SCROLL_OF_ReturnDiad = 40084;
	public static final int SCROLL_OF_ReturnTalkingIslandVillage = 40085;
	public static final int SCROLL_OF_All_Teleport = 40086; //全體傳送術的卷軸 ?
	public static final int SCROLL_OF_ENCHANT_WEAPON = 40087;
	public static final int SCROLL_OF_POLYMORPH = 40088;
	public static final int SCROLL_OF_Resurrection = 40089;
	public static final int BLANK_SCROLL_Level_1 = 40090;
	public static final int BLANK_SCROLL_Level_2 = 40091;
	public static final int BLANK_SCROLL_Level_3 = 40092;
	public static final int BLANK_SCROLL_Level_4 = 40093;
	public static final int BLANK_SCROLL_Level_5 = 40094;
	public static final int IT_SCROLL_OF_Escape = 40095;
	public static final int IT_SCROLL_OF_POLYMORPH = 40096;
	public static final int IT_SCROLL_OF_CurseRemoval = 40097;
	public static final int IT_SCROLL_OF_Identify = 40098;
	public static final int IT_SCROLL_OF_Teleportation = 40099;
	public static final int SCROLL_OF_Teleportation = 40100;
	public static final int SCROLL_OF_ReturnHiddenValley = 40101;
	public static final int SCROLL_OF_ReturnAdenTown = 40102;
	public static final int SCROLL_OF_ReturnOrenCity = 40103;
	public static final int SCROLL_OF_TOI_11F = 40104;
	public static final int SCROLL_OF_TOI_21F = 40105;
	public static final int SCROLL_OF_TOI_31F = 40106;
	public static final int SCROLL_OF_TOI_41F = 40107;
	public static final int SCROLL_OF_TOI_51F = 40108;
	public static final int SCROLL_OF_TOI_61F = 40109;
	public static final int SCROLL_OF_TOI_71F = 40110;
	public static final int SCROLL_OF_TOI_81F = 40111;
	public static final int SCROLL_OF_TOI_91F = 40112;
	public static final int SCROLL_OF_TOI_100F = 40113;
	public static final int SCROLL_OF_ReturnElvenForest = 40114;
	public static final int SCROLL_OF_ReturnWoodbecVillage = 40115;
	public static final int SCROLL_OF_ReturnWerldernVillage = 40116;
	public static final int SCROLL_OF_ReturnSilverKnightTown = 40117;
	public static final int SCROLL_OF_ReturnRecluseVillage = 40118;
	public static final int SCROLL_OF_CurseRemoval = 40119;
	public static final int SCROLL_OF_ReturnResistVillage = 40120;
	public static final int SCROLL_OF_ReturnMineralCavern = 40121;
	public static final int SCROLL_OF_ReturnKentVillage = 40122;
	public static final int SCROLL_OF_ReturnHeineCity = 40123;
	public static final int SCROLL_OF_EscapeClan = 40124;
	public static final int SCROLL_OF_ReturnFireField = 40125;
	public static final int SCROLL_OF_Identify = 40126;
	public static final int SCROLL_OF_ENCHANT_ARMOR_ILLUSION = 40127;
	public static final int SCROLL_OF_ENCHANT_WEAPON_ILLUSION = 40128;
	public static final int SCROLL_OF_Gians = 40129;
	public static final int SCROLL_OF_Kalbas = 40130;
	public static final int TOTEM_OF_Gandi = 40131;
	public static final int TOTEM_OF_Neruga = 40132;
	public static final int TOTEM_OF_DudaMara = 40133;
	public static final int TOTEM_OF_Rova = 40134;
	public static final int TOTEM_OF_Atuba = 40135;
	public static final int ThirdStep_Firework = 40136;
	public static final int SIX_Firework = 40137;
	public static final int HIGHTQUALITY_SixFirework = 40138;
	public static final int BLUE_TwoStepFirework = 40139;
	public static final int BLUE_Sparkler = 40140;
	public static final int BLUE_Firework = 40141;
	public static final int BLUE_HeartShapedFirework = 40142;
	public static final int RED_TwoStepFirework = 40143;
	public static final int RED_Sparkler = 40144;
	public static final int RED_Firework = 40145;
	public static final int RED_HeartShapedFirework = 40146;
	public static final int GREEN_TwoStepRoundFirework = 40147;
	public static final int GREEN_TwoStepFirework = 40148;
	public static final int GREEN_SnowFirework = 40149;
	public static final int GREEN_Sparkler = 40150;
	public static final int GREEN_RoundFirework = 40151;
	public static final int GREEN_Firework = 40152;
	public static final int GREEN_HeartShapedFirework = 40153;
	public static final int CHRISTMAS_Firework = 40154;
	public static final int YELLOW_TwoStepRoundFirework = 40155;
	public static final int YELLOW_TwoStepFirework = 40156;
	public static final int YELLOW_SnowFirework = 40157;
	public static final int YELLOW_Sparkler = 40158;
	public static final int YELLOW_RoundFirework = 40159;
	public static final int YELLOW_Firework = 40160;
	public static final int YELLOW_HeartShapedFirework = 40161;
	public static final int HEART_OF_GOLEM = 40162;
	public static final int KEY_OF_GOLDEN = 40163;
	public static final int BOOKS_TECHNICAL_OF_SHOCKSTUN = 40164;
	public static final int BOOKS_TECHNICAL_OF_REDUCTIONARMOR = 40165;
	public static final int BOOKS_TECHNICAL_OF_BOUNCEATTACK = 40166;
	public static final int BAG_LEATHER_OF_ANCIENT = 40167;
	public static final int BAG_SILK_OF_ANCIENT = 40168;
	public static final int HEART_OF_DRAKE = 40169;
	public static final int SPELLBOOK_OF_FIREBALL = 40170;
	public static final int SPELLBOOK_OF_ENCHANT_DEX = 40171;
	public static final int SPELLBOOK_OF_WEAPONBREAK = 40172;
	public static final int SPELLBOOK_OF_VAMPIRICTOUCH = 40173;
	public static final int SPELLBOOK_OF_SLOW = 40174;
	public static final int SPELLBOOK_OF_COUNTERMAGIC = 40175;
	public static final int SPELLBOOK_OF_MEDITATION = 40176;
	public static final int SPELLBOOK_OF_EARTHJAIL = 40177;
	public static final int SPELLBOOK_OF_CURSEPARALYZE = 40178;
	public static final int SPELLBOOK_OF_CALLLIGHTNING = 40179;
	public static final int SPELLBOOK_OF_GREATERHEAL = 40180;
	public static final int SPELLBOOK_OF_TAMEMONSTER = 40181;
	public static final int SPELLBOOK_OF_REMOVECURSE = 40182;
	public static final int SPELLBOOK_OF_CONEOFCOLD = 40183;
	public static final int SPELLBOOK_OF_MANADRAIN = 40184;
	public static final int SPELLBOOK_OF_DARKNESS = 40185;
	public static final int SPELLBOOK_OF_CREATEZOMBIE = 40186;
	public static final int SPELLBOOK_OF_ENCHANT_MIGHTY = 40187;
	public static final int SPELLBOOK_OF_HASTE = 40188;
	public static final int SPELLBOOK_OF_CANCELMAGIC = 40189;
	public static final int SPELLBOOK_OF_ERUPTION = 40190;
	public static final int SPELLBOOK_OF_SUNBURST = 40191;
	public static final int SPELLBOOK_OF_WEAKNESS = 40192;
	public static final int SPELLBOOK_OF_BLESSMAGICWEAPON = 40193;
	public static final int SPELLBOOK_OF_HEALPLEDGE = 40194;
	public static final int SPELLBOOK_OF_FREEZE = 40195;
	public static final int SPELLBOOK_OF_SUMMONMONSTER = 40196;
	public static final int SPELLBOOK_OF_HOLYWALK = 40197;
	public static final int SPELLBOOK_OF_TORNADO = 40198;
	public static final int SPELLBOOK_OF_GREATERHASTE = 40199;
	public static final int SPELLBOOK_OF_BERSERKERS = 40200;
	public static final int SPELLBOOK_OF_DISEASE = 40201;
	public static final int SPELLBOOK_OF_FULLHEAL = 40202;
	public static final int SPELLBOOK_OF_FIREWALL = 40203;
	public static final int SPELLBOOK_OF_BLIZZARD = 40204;
	public static final int SPELLBOOK_OF_INVISIBILITY = 40205;
	public static final int SPELLBOOK_OF_RESURRECTION = 40206;
	public static final int SPELLBOOK_OF_EARTHQUAKE = 40207;
	public static final int SPELLBOOK_OF_LIFESTREAM = 40208;
	public static final int SPELLBOOK_OF_SILENCE = 40209;
	public static final int SPELLBOOK_OF_LIGHTNINGSTORM = 40210;
	public static final int SPELLBOOK_OF_FOGOFSLEEPING = 40211;
	public static final int SPELLBOOK_OF_POLYMORPH = 40212;
	public static final int SPELLBOOK_OF_IMMUNETOHARM = 40213;
	public static final int SPELLBOOK_OF_MASSTELEPORT = 40214;
	public static final int SPELLBOOK_OF_FIRESTORM = 40215;
	public static final int SPELLBOOK_OF_DECAYPOTION = 40216;
	public static final int SPELLBOOK_OF_COUNTERDETECTION = 40217;
	public static final int SPELLBOOK_OF_CREATEMAGICALWEAPON = 40218;
	public static final int SPELLBOOK_OF_METEORSTRIKE = 40219;
	public static final int SPELLBOOK_OF_GREATERRESURRECTION = 40220;
	public static final int SPELLBOOK_OF_MASSSLOW = 40221;
	public static final int SPELLBOOK_OF_DESTROY = 40222;
	public static final int SPELLBOOK_OF_ABSOLUTEBARRIER = 40223;
	public static final int SPELLBOOK_OF_ADVANCESPIRIT = 40224;
	public static final int SPELLBOOK_OF_FREEZINGBLIZZARD = 40225;
	public static final int SPELLBOOK_OF_TRUETARGET = 40226;
	public static final int SPELLBOOK_OF_GLOWINGAURA = 40227;
	public static final int SPELLBOOK_OF_CALLPLEDGEMEMBER = 40228;
	public static final int SPELLBOOK_OF_SHININGAURA = 40229;
	public static final int SPELLBOOK_OF_BRAVEAURA = 40230;
	public static final int SPELLBOOK_OF_TELEPORTTOPLEDGEMEMBER = 40231;
	public static final int CRYSTAL_OF_SPIRIT_RESISTMAGIC = 40232;
	public static final int CRYSTAL_OF_SPIRIT_BODYTOMIND = 40233;
	public static final int CRYSTAL_OF_SPIRIT_TELEPORTTOMOTHER = 40234;
	public static final int CRYSTAL_OF_SPIRIT_CLEARMIND = 40235;
	public static final int CRYSTAL_OF_SPIRIT_RESISTELEMENTAL = 40236;
	public static final int CRYSTAL_OF_SPIRIT_RETURNTONATURE = 40237;
	public static final int CRYSTAL_OF_SPIRIT_BLOODTOSOUL = 40238;
	public static final int CRYSTAL_OF_SPIRIT_PROTECTIONFORMELEMENTAL = 40239;
	public static final int CRYSTAL_OF_SPIRIT_TRIPLEARROW = 40240;
	public static final int CRYSTAL_OF_SPIRIT_ELEMENTALFALLDOWN = 40241;
	public static final int CRYSTAL_OF_SPIRIT_ERASEMAGIC = 40242;
	public static final int CRYSTAL_OF_SPIRIT_SUMMONLESSERELEMENTAL = 40243;
	public static final int CRYSTAL_OF_SPIRIT_AREAOFSILENCE = 40244;
	public static final int CRYSTAL_OF_SPIRIT_SUMMONGREATERELEMENTAL = 40245;
	public static final int CRYSTAL_OF_SPIRIT_COUNTERMIRROR = 40246;
	public static final int CRYSTAL_OF_SPIRIT_EARTHSKIN = 40247;
	public static final int CRYSTAL_OF_SPIRIT_ENTANGLE = 40248;
	public static final int CRYSTAL_OF_SPIRIT_EARTHBIND = 40249;
	public static final int CRYSTAL_OF_SPIRIT_BLESSOFEARTH = 40250;
	public static final int CRYSTAL_OF_SPIRIT_IRONSKIN = 40251;
	public static final int CRYSTAL_OF_SPIRIT_EXOTICVITALIZE = 40252;
	public static final int CRYSTAL_OF_SPIRIT_WATERLIFE = 40253;
	public static final int CRYSTAL_OF_SPIRIT_NATURESTOUCH = 40254;
	public static final int CRYSTAL_OF_SPIRIT_NATURESBLESSING = 40255;
	public static final int CRYSTAL_OF_SPIRIT_FIREWEAPON = 40256;
	public static final int CRYSTAL_OF_SPIRIT_BLESSOFFIRE = 40257;
	public static final int CRYSTAL_OF_SPIRIT_BURNINGWEAPON = 40258;
	public static final int CRYSTAL_OF_SPIRIT_ELEMENTALFIRE = 40259;
	public static final int CRYSTAL_OF_SPIRIT_WINDSHOT = 40260;
	public static final int CRYSTAL_OF_SPIRIT_WINDWALK = 40261;
	public static final int CRYSTAL_OF_SPIRIT_EYEOFSTORM = 40262;
	public static final int CRYSTAL_OF_SPIRIT_STORMSHOT = 40263;
	public static final int CRYSTAL_OF_SPIRIT_WINDSHACKLE = 40264;
	public static final int CRYSTAL_OF_DARKSPIRIT_BLINDHIDING = 40265;
	public static final int CRYSTAL_OF_DARKSPIRIT_ENCHANTVENOM = 40266;
	public static final int CRYSTAL_OF_DARKSPIRIT_SHADOWARMOR = 40267;
	public static final int CRYSTAL_OF_DARKSPIRIT_PURIFYSTONE = 40268;
	public static final int CRYSTAL_OF_DARKSPIRIT_DRESSMIGHTY = 40269;
	public static final int CRYSTAL_OF_DARKSPIRIT_MOVINGACCELERATION = 40270;
	public static final int CRYSTAL_OF_DARKSPIRIT_BURNINGSPIRIT = 40271;
	public static final int CRYSTAL_OF_DARKSPIRIT_DARKBLIND = 40272;
	public static final int CRYSTAL_OF_DARKSPIRIT_VENOMRESIST = 40273;
	public static final int CRYSTAL_OF_DARKSPIRIT_DRESSDEXTERITY = 40274;
	public static final int CRYSTAL_OF_DARKSPIRIT_DOUBLEBREAK = 40275;
	public static final int CRYSTAL_OF_DARKSPIRIT_UNCANNYDODGE = 40276;
	public static final int CRYSTAL_OF_DARKSPIRIT_SHADOWFANG = 40277;
	public static final int CRYSTAL_OF_DARKSPIRIT_FINALBURN = 40278;
	public static final int CRYSTAL_OF_DARKSPIRIT_DRESSEVASION = 40279;
	public static final int SEALED_TOI_TELEPORT_CHARM_11F = 40280;
	public static final int SEALED_TOI_TELEPORT_CHARM_21F = 40281;
	public static final int SEALED_TOI_TELEPORT_CHARM_31F = 40282;
	public static final int SEALED_TOI_TELEPORT_CHARM_41F = 40283;
	public static final int SEALED_TOI_TELEPORT_CHARM_51F = 40284;
	public static final int SEALED_TOI_TELEPORT_CHARM_61F = 40285;
	public static final int SEALED_TOI_TELEPORT_CHARM_71F = 40286;
	public static final int SEALED_TOI_TELEPORT_CHARM_81F = 40287;
	public static final int SEALED_TOI_TELEPORT_CHARM_91F = 40288;
	public static final int TOI_TELEPORT_CHARM_11F = 40289;
	public static final int TOI_TELEPORT_CHARM_21F = 40290;
	public static final int TOI_TELEPORT_CHARM_31F = 40291;
	public static final int TOI_TELEPORT_CHARM_41F = 40292;
	public static final int TOI_TELEPORT_CHARM_51F = 40293;
	public static final int TOI_TELEPORT_CHARM_61F = 40294;
	public static final int TOI_TELEPORT_CHARM_71F = 40295;
	public static final int TOI_TELEPORT_CHARM_81F = 40296;
	public static final int TOI_TELEPORT_CHARM_91F = 40297;
	public static final int TICKET_OF_TalkingIsland = 40298;
	public static final int TICKET_OF_Gludio = 40299;
	public static final int TICKET_OF_ForgottenIsland = 40300;
	public static final int TICKET_OF_Heine = 40301;
	public static final int TICKET_OF_PiratesIsland = 40302;
	public static final int TICKET_OF_HiddenWharf = 40303;
	public static final int RELIC_OF_MAPHR = 40304;
	public static final int RELIC_OF_PAAGRIO = 40305;
	public static final int RELIC_OF_EVA = 40306;
	public static final int RELIC_OF_SAYHA = 40307;
	public static final int ADENA = 40308;
	public static final int TICKET_RACE = 40309; //食人妖精競賽票
	public static final int LETTER_PAPER = 40310;
	public static final int LETTER_PAPER_OF_CLAN = 40311;
	public static final int KEY_OF_INN_ROOM = 40312;
	public static final int KEY_OF_SILVER = 40313;
	public static final int COLLAR = 40314;
	public static final int DOG_WHISHLE = 40315;
	public static final int HIGHT_LV_COLLAR = 40316;
	public static final int WHETSTONE = 40317;
	public static final int MAGIC_GEM = 40318;
	public static final int SPIRIT_GEM = 40319;
	public static final int BRING_STONE = 40320;
	public static final int DARK_STONE = 40321;
	public static final int BRAVE_STONE = 40322;
	public static final int WISE_STONE = 40323;
	public static final int KAISER_STONE = 40324;
	public static final int MAGIC_DICE_OF_TWOSIDED = 40325; //2階段魔法骰子
	public static final int MAGIC_DICE_OF_THREESIDED = 40326; //3階段魔法骰子
	public static final int MAGIC_DICE_OF_FOURSIDED = 40327; //4階段魔法骰子
	public static final int MAGIC_DICE_OF_SIXSIDED = 40328; //6階段魔法骰子
	public static final int TOTEM_OF_FETISH = 40329; //原住民圖騰
	public static final int QUIVER_OF_ENDLESS = 40330; //無限箭筒
	public static final int SWORD_OF_KENT_SOLDIER = 40331; //肯特勇士之劍
	public static final int BOW_OF_KENT_ARCHER = 40332; //肯特射手之弓
	public static final int STAFF_OF_KENT_WIZARD = 40333; //肯特法師魔杖
	public static final int EDORYU_OF_KENT_ASSASSIN = 40334; //肯特刺客雙刀
	public static final int AXE_OF_KENT_WARRIOR = 40335; //肯特戰士斧頭
	public static final int KENT_EMBLEN_BOOTS = 40336; //肯特徽章長靴
	public static final int KENT_EMBLEN_PLATE = 40337; //肯特徽章盔甲
	public static final int KENT_EMBLEN_GLOVES = 40338; //肯特徽章手套
	public static final int KENT_EMBLEN_SHIELD = 40339; //肯特徽章盾牌
	public static final int KENT_EMBLEN_HELM = 40340; //肯特徽章頭盔
	public static final int SCALE_OF_ANTHARAS = 40341; //安塔瑞斯之鱗
	public static final int BROKEN_CLAW_OF_ANTHARAS = 40342; //安塔瑞斯之爪
	public static final int EYE_OF_ANTHARAS = 40343; //安塔瑞斯之眼
	public static final int BLOOD_OF_ANTHARAS = 40344; //安塔瑞斯之血
	public static final int MEAT_OF_ANTHARAS = 40345; //安塔瑞斯之肉
	public static final int HEART_OF_ANTHARAS = 40346; //安塔瑞斯之心
	public static final int BONE_OF_ANTHARAS = 40347; //安塔瑞斯之骨
	public static final int TOOTH_OF_ANTHARAS = 40348; //安塔瑞斯之牙
	public static final int SCALE_OF_VALAKAS = 40349; //巴拉卡斯之鱗
	public static final int BROKEN_CLAW_OF_ = 40350; //巴拉卡斯之爪
	public static final int EYE_OF_VALAKAS = 40351; //巴拉卡斯之眼
	public static final int BLOOD_OF_VALAKAS = 40352; //巴拉卡斯之血
	public static final int MEAT_OF_VALAKAS = 40353; //巴拉卡斯之肉
	public static final int HEART_OF_VALAKAS = 40354; //巴拉卡斯之心
	public static final int BONE_OF_VALAKAS = 40355; //巴拉卡斯之骨
	public static final int TOOTH_OF_VALAKAS = 40356; //巴拉卡斯之牙
	public static final int SCALE_OF_FAFURION = 40357; //法利昂之鱗
	public static final int BROKEN_CLAW_OF_FAFURION = 40358; //法利昂之爪
	public static final int EYE_OF_FAFURION = 40359; //法利昂之眼
	public static final int BLOOD_OF_FAFURION = 40360; //法利昂之血
	public static final int MEAT_OF_FAFURION = 40361; //法利昂之肉
	public static final int HEART_OF_FAFURION = 40362; //法利昂之心
	public static final int BONE_OF_FAFURION = 40363; //法利昂之骨
	public static final int TOOTH_OF_FAFURION = 40364; //法利昂之牙
	public static final int SCALE_OF_LINDVIOR = 40365; //林德拜爾之鱗
	public static final int BROKEN_CLAW_OF_LINDVIOR = 40366; //林德拜爾之爪
	public static final int EYE_OF_LINDVIOR = 40367; //林德拜爾之眼
	public static final int BLOOD_OF_LINDVIOR = 40368; //林德拜爾之血
	public static final int MEAT_OF_LINDVIOR = 40369; //林德拜爾之肉
	public static final int HEART_OF_LINDVIOR = 40370; //林德拜爾之心
	public static final int BONE_OF_LINDVIOR = 40371; //林德拜爾之骨
	public static final int TOOTH_OF_LINDVIOR = 40372; //林德拜爾之牙
	public static final int Map_All_OF_Aden = 40373;
	public static final int Map_Talking_Island = 40374;
	public static final int Map_Gludio = 40375;
	public static final int Map_Kent_Castle = 40376;
	public static final int Map_Orcish_Fortress = 40377;
	public static final int Map_Elven_Forest = 40378;
	public static final int Map_Windawood = 40379;
	public static final int Map_Silver_Knight_Town = 40380;
	public static final int Map_Dragon_Valley = 40381;
	public static final int Map_Giran = 40382;
	public static final int Map_Singing_Island = 40383;
	public static final int Map_Hidden_Valley = 40384;
	public static final int Map_Heine = 40385;
	public static final int Map_Lair_OF_Valakas = 40386;
	public static final int Map_Oren = 40387;
	public static final int Map_Aden = 40388;
	public static final int Map_Silent_Cavern = 40389;
	public static final int Map_Pirate_Island = 40390;
	public static final int CALCULATOR = 40391;
	public static final int CHRISTMAS_TREE = 40392;
	public static final int SCALES_OF_RED_DRAGON = 40393;
	public static final int SCALES_OF_WHITE_DRAGON = 40394;
	public static final int SCALES_OF_BLUE_DRAGON = 40395;
	public static final int SCALES_OF_GREEN_DRAGON = 40396;
	public static final int SKIN_OF_CIMAERA_DRAGON = 40397;
	public static final int SKIN_OF_CIMAERA_GOAT = 40398;
	public static final int SKIN_OF_CIMAERA_LION = 40399;
	public static final int SKIN_OF_CIMAERA_SNAKE = 40400;
	public static final int LEATHER_CURSED_FIRE = 40401;
	public static final int LEATHER_CURSED_WATER = 40402;
	public static final int LEATHER_CURSED_WILD = 40403;
	public static final int LEATHER_CURSED_EARTH = 40404;
	public static final int FUR = 40405;
	public static final int LEATHER_HARD = 40406; //高級皮革
	public static final int BONE_PIECE = 40407; //骨頭碎片
	public static final int LUMP_OF_IRON = 40408;
	public static final int HEART_OF_FIREBIRD = 40409;
	public static final int BARK_OF_DARK_ENT = 40410;
	public static final int FRUIT_OF_DARK_ENT = 40411;
	public static final int TWIG_OF_DARK_ENT = 40412;
	public static final int HEART_OF_ICEQUEEN = 40413;
	public static final int STONE_ALCHEMISTS = 40414;
	public static final int POUCH_RELIC = 40415;
	public static final int BLOOD_OF_CURSED = 40416;
	public static final int CRYSTAL_OF_SPIRIT = 40417;
	public static final int VALUABLES_OF_TARAKS = 40418;
	public static final int WEB_OF_MURYAN = 40419;
	public static final int ANCIENTS_BOOK_OF_MAGIC_VOL_1 = 40420; //古代人的咒術書1冊
	public static final int ANCIENTS_BOOK_OF_MAGIC_VOL_2 = 40421; //古代人的咒術書2冊
	public static final int ANCIENTS_BOOK_OF_MAGIC_VOL_3 = 40422; //古代人的咒術書3冊
	public static final int ANCIENTS_BOOK_OF_MAGIC_VOL_4 = 40423; //古代人的咒術書4冊
	public static final int LEATHER_OF_WOLF = 40424; //狼皮
	public static final int POTION_OF_DARK_FOREST = 40425; //黑暗棲林者藥水
	public static final int RING_OF_DARK_FORESTER = 40426; //黑暗棲林者戒指
	public static final int BAG_OF_DARK_ELVEN = 40427; //黑暗妖精袋子
	/*
	public static final int = 40428; //月光之淚
	public static final int = 40429; //大洞穴卷軸碎片
	public static final int = 40430; //大洞穴水晶
	public static final int = 40431; //鼴鼠的皮
	public static final int = 40432; //狄亞得卷軸碎片
	public static final int = 40433; //犰狳之爪
	public static final int = 40434; //犰狳的尾巴
	public static final int = 40435; //深淵之花的花苞
	public static final int = 40436; //深淵之花的根
	public static final int = 40437; //深淵花枝條
	public static final int = 40438; //蝙蝠之牙
	public static final int = 40439; //白金金屬板
	public static final int = 40440; //白金
	public static final int = 40441; //白金原石
	public static final int = 40442; //布拉伯的胃液
	public static final int = 40443; //黑色米索莉
	public static final int = 40444; //黑色米索莉原石
	public static final int = 40445; //黑色米索莉金屬板
	public static final int = 40446; //黑法師戒指
	public static final int = 40447; //黑虎的皮
	public static final int = 40448; //黑虎的爪
	public static final int = 40449; //黑虎的牙
	public static final int = 40450; //黑暗安特的樹枝
	public static final int = 40451; //黑虎之心
	public static final int = 40452; //喚獸師戒指
	public static final int = 40453; //喚獸師長鞭
	public static final int = 40454; //馴獸師戒指
	public static final int = 40455; //藍色布料
	public static final int = 40456; //紅色布料
	public static final int = 40457; //白色布料
	public static final int SCALE_OF_SHINING = 40458; //光明的鱗片
	public static final int = 40459; //毒蠍之皮
	public static final int = 40460; //阿西塔基奧的灰燼
	 */
	public static final int WIND_TEAR = 40498;
	public static final int TWIG_OF_ENT = 40507;
	public static final int BLACK_BLOODSTAIN = 40524;
	public static final int TEAR_OF_GRANKAIN = 40525;
	public static final int SCALE_OF_RAMIAS = 40544; //蛇女之鱗
	public static final int BAG_OF_LISTS_ASSASSINATE = 40556;
	public static final int LISTS_ASSASSINATE_Gludin = 40557;
	public static final int LISTS_ASSASSINATE_Giran = 40558;
	public static final int LISTS_ASSASSINATE_Aden = 40559;
	public static final int LISTS_ASSASSINATE_Woodbec = 40560;
	public static final int LISTS_ASSASSINATE_Kent = 40561;
	public static final int LISTS_ASSASSINATE_Heine = 40562;
	public static final int LISTS_ASSASSINATE_OrcTown = 40563;
	public static final int SECRET_OF_LIFE = 40564;
	public static final int SEARCH_DOCUMENT = 40565; //搜索狀
	public static final int SPELLBOOK_GANDI = 40609; //甘地妖魔魔法書
	public static final int SPELLBOOK_NERUGA = 40610; //那魯加妖魔魔法書
	public static final int SPELLBOOK_DUDA_MARA = 40611; //都達瑪拉妖魔魔法書
	public static final int SPELLBOOK_ATUBA = 40612; //阿吐巴妖魔魔法書
	public static final int SCROLL_OF_ENCHANT_QUEST_WEAPON = 40660;
	public static final int COIN_OF_REPUTATION = 40733; // 名譽貨幣
	public static final int COIN_OF_WISDOM = 40736; // 智慧貨幣
	public static final int BONE_OF_UNDEAD = 40579; //不死族的骨頭
	public static final int BONE_FRAGMENT_OF_UNDEAD = 40580; //不死族的骨頭碎片
	public static final int KEY_OF_UNDEAD = 40581; //不死族的鑰匙
	public static final int CRYSTAL_OF_DARKELF_SOUL = 40969;
	public static final int DIRECTIVE_OF_ERIS_1 = 41007; //伊莉絲的命令書：靈魂之安息
	public static final int BAG_OF_ERIS = 41008; //伊莉絲的袋子
	public static final int DIRECTIVE_OF_ERIS_2 = 41009; //伊莉絲的命令書：同盟之意志
	public static final int RECOMMENDATION_LETTER_OF_ERIS = 41010; //伊莉絲的推薦函
	public static final int POTION_OF_SKELETON_PIRATE_BOSS_POLYMORPH = 41143; //海賊骷髏首領變身藥水
	public static final int POTION_OF_SKELETON_PIRATE_SOLDIER_POLYMORPH = 41144; //海賊骷髏士兵變身藥水
	public static final int POTION_OF_SKELETON_PIRATE_KNIFE_POLYMORPH = 41145; //海賊骷髏刀手變身藥水
	public static final int BOOKS_TECHNICAL_OF_SOLID_CARRIAGE = 41147; //技術書(堅固防護)
	public static final int BOOKS_TECHNICAL_OF_COUNTER_BARRIER = 41148; //技術書(反擊屏障)
	public static final int CRYSTAL_OF_SPIRIT_SOULOFFLAME = 41149; //精靈水晶(烈焰之魂)
	public static final int CRYSTAL_OF_SPIRIT_ADDITIONALFIRE = 41150; //精靈水晶(能量激發)
	public static final int CRYSTAL_OF_SPIRIT_AQUAPROTECT = 41151; //精靈水晶(水之防護)
	public static final int CRYSTAL_OF_SPIRIT_POLLUTEWATER = 41152; //精靈水晶(污濁之水)
	public static final int CRYSTAL_OF_SPIRIT_STRIKERSGALE = 41153; //精靈水晶(精準射擊)
	public static final int SCALE_OF_DARKNESS = 41154;//暗之鱗
	public static final int SCALE_OF_FLAMES = 41155; //火之鱗
	public static final int SCALE_OF_IMMORALITY = 41156; //叛之鱗
	public static final int SCALE_OF_HATRED = 41157; //恨之鱗
	public static final int CRYSTAL_ORB_OF_MAYA = 41158; //瑪雅的水晶球
	public static final int SACRED_WING_FEATHER = 41159; //神秘的羽毛
	public static final int CALLING_Flute = 41160; //寵物召喚笛	
	public static final int DULL_WEAPON = 41206;
	public static final int RICE_BALL = 41261; //飯糰
	public static final int CHICKEN_SKEWER = 41262; //雞肉串燒
	public static final int PIZZA_PIECES = 41268; //小比薩
	public static final int GRILLED_CORN = 41269; //烤玉米
	public static final int POPRICE = 41271; //爆米花
	public static final int TEMPURA = 41272; //甜不辣 FISH_CAKE?
	public static final int WAFFLE = 41273; //鬆餅
	public static final int POLE_OF_MAGIC_FISHING = 41293;
	public static final int POLE_OF_SHORT_FISHING = 41294;
	public static final int BAIT = 41295; //餌
	public static final int FRUIT_OF_THE_VICTOR = 41310;
	public static final int BLESSED_WINE = 41338; //受祝福的葡萄酒 資料庫中 bless = 0 ?
	public static final int BLOOD_OF_MEDUSA = 41342; //梅杜莎之血
	public static final int ESSENCE_OF_WATER = 41344; //水中的水
	public static final int HEROS_MARK = 41402;
	public static final int POTION_OF_REINFORCED_CASE = 41415; // 強化勇氣的藥水
	public static final int SCROLL_OF_ENCHANT_WEAPON_WIND = 41429; //風之武器強化卷軸
	public static final int SCROLL_OF_ENCHANT_WEAPON_EARTH = 41430; //地之武器強化卷軸
	public static final int SCROLL_OF_ENCHANT_WEAPON_WATER = 41431; //水之武器強化卷軸
	public static final int SCROLL_OF_ENCHANT_WEAPON_FIRE = 41432; //火之武器強化卷軸
	public static final int IT_BAG_OF_MAGIC = 41460; //象牙塔魔法袋
	public static final int IT_SCROLL_OF_SUPPLEMENT = 41461; //象牙塔補給品卷軸
	public static final int IT_OF_WONDER_DRUG = 41462; //象牙塔妙藥 : TIME 900 , HPR + 10 , MPR + 2 , < Lv45
	public static final int SCALE_OF_OBLIVION = 41463; //幻之鱗 : TIME 900 , 變身為克特
	public static final int SPELLBOOK_OF_LESSERHEAL = 45000;
	public static final int SPELLBOOK_OF_LIGHT = 45001;
	public static final int SPELLBOOK_OF_SHIELD = 45002;
	public static final int SPELLBOOK_OF_ENERGYBOLT = 45003;
	public static final int SPELLBOOK_OF_TELEPORT = 45004;
	public static final int SPELLBOOK_OF_ICEDAGGER = 45005;
	public static final int SPELLBOOK_OF_WINDSHURIKEN = 45006;
	public static final int SPELLBOOK_OF_HOLYWEAPON = 45007;
	public static final int SPELLBOOK_OF_CUREPOISON = 45008;
	public static final int SPELLBOOK_OF_CHILLTOUCH = 45009;
	public static final int SPELLBOOK_OF_CURSEPOISON = 45010;
	public static final int SPELLBOOK_OF_ENCHANTWEAPON = 45011;
	public static final int SPELLBOOK_OF_DETECTION = 45012;
	public static final int SPELLBOOK_OF_DECREASEWEIGHT = 45013;
	public static final int SPELLBOOK_OF_STALAC = 45014;
	public static final int SPELLBOOK_OF_FIREARROW = 45015;
	public static final int SPELLBOOK_OF_LIGHTNING = 45016;
	public static final int SPELLBOOK_OF_FROZENCLOUD = 45017;
	public static final int SPELLBOOK_OF_HEAL = 45018;
	public static final int SPELLBOOK_OF_CURSEBLIND = 45019;
	public static final int SPELLBOOK_OF_BLESSEDARMOR = 45020;
	public static final int SPELLBOOK_OF_TURNUNDEAD = 45021;
	public static final int SPELLBOOK_OF_REVEALWEAKNESS = 45022;
	/*
	public static final int = 49000; //
	public static final int = 49001; //
	public static final int = 49002; //
	public static final int = 49003; //
	public static final int = 49004; //
	public static final int = 49005; //卡立普的袋子
	public static final int = 49006; //
	public static final int = 49007; //
	public static final int = 49008; //
	public static final int = 49009; //
	public static final int = 49010; //
	public static final int = 49011; //
	public static final int = 49012; //
	public static final int = 49013; //
	public static final int = 49014; //
	public static final int = 49015; //
	public static final int = 49016; //
	public static final int = 49017; //
	public static final int = 49018; //
	public static final int = 49019; //
	public static final int = 49020; //
	public static final int = 49021; //
	public static final int = 49022; //
	public static final int = 49023; //
	public static final int = 49024; //
	public static final int = 49025; //
	public static final int ANCIENT_GoldCoin = 49026;
	public static final int = 49027; //
	public static final int = 49028; //
	public static final int = 49029; //
	public static final int = 49030; //
	public static final int = 49031; //
	public static final int = 49032; //
	public static final int = 49033; //
	public static final int = 49034; //
	public static final int KEY_OF_ICE_CASTLE_1 = 49035;
	public static final int KEY_OF_ICE_CASTLE_2 = 49036;
	public static final int = 49037; //
	public static final int = 49038; //
	public static final int = 49039; //
	public static final int = 49040; //
	public static final int = 49041; //
	public static final int = 49042; //
	public static final int = 49043; //
	public static final int = 49044; //
	public static final int = 49045; //
	public static final int = 49046; //
	public static final int = 49047; //
	public static final int = 49048; //
	public static final int = 49049; //
	public static final int = 49050; //
	*/
	public static final int CAKE_PARTY = 49071; //派對蛋糕
	public static final int OPENED_HIGHGRADE_TREASURE_CHEST_OF_OSIRIS = 49100; //開鎖的歐西里斯高級寶箱
	public static final int FRAGMENT_OF_TIME = 49101; //時空裂痕碎片
	public static final int DRAGON_TABLET_OF_DRAGONSKIN = 49102; //龍騎士書板(龍之護鎧)
	public static final int DRAGON_TABLET_OF_BURNINGSLASH = 49103; //龍騎士書板(燃燒擊砍)
	public static final int DRAGON_TABLET_OF_GUARDBREAK = 49104; //龍騎士書板(護衛毀滅)
	public static final int DRAGON_TABLET_OF_MAGMABREATH = 49105; //龍騎士書板(岩漿噴吐)
	public static final int DRAGON_TABLET_OF_AWAKENING_ANTHARAS = 49106; //龍騎士書板(覺醒：安塔瑞斯)
	public static final int DRAGON_TABLET_OF_BLOODLUST = 49107; //龍騎士書板(血之渴望)
	public static final int DRAGON_TABLET_OF_FOESLAYER = 49108; //龍騎士書板(屠宰者)
	public static final int DRAGON_TABLET_OF_FEAR = 49109; //龍騎士書板(恐懼無助)
	public static final int DRAGON_TABLET_OF_SHOCKSKIN = 49110; //龍騎士書板(衝擊之膚)
	public static final int DRAGON_TABLET_OF_AWAKENING_FAFURION = 49111; //龍騎士書板(覺醒：法利昂)
	public static final int DRAGON_TABLET_OF_MORTALBODY = 49112; //龍騎士書板(致命身軀)
	public static final int DRAGON_TABLET_OF_THUNDERGRAB = 49113; //龍騎士書板(奪命之雷)
	public static final int DRAGON_TABLET_OF_HORROROFDEATH = 49114; //龍騎士書板(驚悚死神)
	public static final int DRAGON_TABLET_OF_FREEZINGBREATH = 49115; //龍騎士書板(寒冰噴吐)
	public static final int DRAGON_TABLET_OF_AWAKENING_VALAKAS = 49116; //龍騎士書板(覺醒：巴拉卡斯)
	public static final int MEMORY_CRYSTAL_OF_MIRRORIMAGE = 49117; //記憶水晶(鏡像)
	public static final int MEMORY_CRYSTAL_OF_CONFUSION = 49118; //記憶水晶(混亂)
	public static final int MEMORY_CRYSTAL_OF_SMASH = 49119; //記憶水晶(暴擊)
	public static final int MEMORY_CRYSTAL_OF_ILLUSIONOGRE = 49120; //記憶水晶(幻覺：歐吉)
	public static final int MEMORY_CRYSTAL_OF_CUBEIGNITION = 49121; //記憶水晶(立方：燃燒)
	public static final int MEMORY_CRYSTAL_OF_CONCENTRATION = 49122; //記憶水晶(專注)
	public static final int MEMORY_CRYSTAL_OF_MINDBRAKE = 49123; //記憶水晶(心靈破壞)
	public static final int MEMORY_CRYSTAL_OF_BONEBRAKE = 49124; //記憶水晶(骷髏毀壞)
	public static final int MEMORY_CRYSTAL_OF_ILLUSIONLICH = 49125; //記憶水晶(幻覺：巫妖)
	public static final int MEMORY_CRYSTAL_OF_CUBEQUAKE = 49126; //記憶水晶(立方：地裂)
	public static final int MEMORY_CRYSTAL_OF_PATIENCE = 49127; //記憶水晶(耐力)
	public static final int MEMORY_CRYSTAL_OF_FANTASM = 49128; //記憶水晶(幻想)
	public static final int MEMORY_CRYSTAL_OF_ARMBREAKER = 49129; //記憶水晶(武器破壞者)
	public static final int MEMORY_CRYSTAL_OF_ILLUSIONDIAMONDGOLEM = 49130; //記憶水晶(幻覺：鑽石高崙)
	public static final int MEMORY_CRYSTAL_OF_CUBESHOCK = 49131; //記憶水晶(立方：衝擊)
	public static final int MEMORY_CRYSTAL_OF_INSIGHT = 49132; //記憶水晶(洞察)
	public static final int MEMORY_CRYSTAL_OF_PANIC = 49133; //記憶水晶(恐慌)
	public static final int MEMORY_CRYSTAL_OF_JOYOFPAIN = 49134; //記憶水晶(疼痛的歡愉)
	public static final int MEMORY_CRYSTAL_OF_ILLUSIONAVATAR = 49135; //記憶水晶(幻覺：化身)
	public static final int MEMORY_CRYSTAL_OF_CUBEBALANCE = 49136; //記憶水晶(立方：和諧)
	public static final int CAKE_OF_FRESH_CREAM = 49137; //鮮奶油蛋糕
	public static final int CAKE_OF_CHOCOLATE = 49138; //巧克力蛋糕
	public static final int CAKE_OF_CHEESE = 49139; //起司蛋糕
	public static final int CAKE_OF_GREEN_TEA_ROLL = 49140; //綠茶蛋糕捲
	public static final int BOX_OF_MAGIC_CAKE = 49141; //魔法蛋糕盒
	public static final int CANDLE_OF_Reminiscence = 49142; //回憶蠟燭
	public static final int CRYSTAL_OF_BRAVERY = 49143; //勇氣結晶
	/*
	public static final int = 49144; //
	public static final int = 49145; //
	public static final int = 49146; //
	public static final int = 49147; //
	*/
	public static final int SCROLL_OF_ENCHANT_ACCESSORY = 49148; //飾品強化卷軸
	public static final int SCROLL_OF_SHARNAS_LV30_POLYMORPH = 49149; //夏納的變身卷軸_等級30
	public static final int SCROLL_OF_SHARNAS_LV40_POLYMORPH = 49150; //夏納的變身卷軸_等級40
	public static final int SCROLL_OF_SHARNAS_LV52_POLYMORPH = 49151; //夏納的變身卷軸_等級52
	public static final int SCROLL_OF_SHARNAS_LV55_POLYMORPH = 49152; //夏納的變身卷軸_等級55
	public static final int SCROLL_OF_SHARNAS_LV60_POLYMORPH = 49153; //夏納的變身卷軸_等級60
	public static final int SCROLL_OF_SHARNAS_LV65_POLYMORPH = 49154; //夏納的變身卷軸_等級65
	public static final int SCROLL_OF_SHARNAS_LV70_POLYMORPH = 49155; //夏納的變身卷軸_等級70
	public static final int STONE_OF_ELEMENTAL = 49156; //屬性石
	public static final int BONE_OF_FRAGMENT = 49157; //刻印的骨頭碎片
	public static final int FORBIDDEN_FRUIT = 49158; // 生命之樹果實
	public static final int MOVEMENT_ORDER = 49159; //調職命令書
	public static final int DANTES_ROYAL_LETTER = 49160; //丹特斯的召書
	/*
	public static final int = 49161; //
	public static final int = 49162; //
	public static final int = 49163; //
	public static final int = 49164; //
	public static final int = 49165; //
	public static final int = 49166; //
	public static final int = 49167; //
	public static final int = 49168; //
	public static final int = 49169; //
	public static final int = 49170; //
	public static final int = 49171; //
	public static final int = 49172; //
	public static final int = 49173; //
	public static final int = 49174; //
	public static final int = 49175; //
	public static final int = 49176; //
	public static final int = 49177; //
	public static final int = 49178; //
	public static final int = 49179; //
	public static final int = 49180; //
	public static final int = 49181; //
	public static final int = 49182; //
	public static final int = 49183; //
	public static final int = 49184; //
	public static final int = 49185; //
	public static final int = 49186; //
	public static final int = 49187; //
	public static final int = 49188; //
	public static final int = 49189; //
	public static final int = 49190; //
	public static final int = 49191; //
	public static final int = 49192; //
	public static final int = 49193; //
	public static final int = 49194; //
	public static final int = 49195; //
	public static final int = 49196; //
	public static final int = 49197; //
	public static final int = 49198; //
	public static final int = 49199; //
	public static final int = 49200; //
	public static final int = 49201; //
	public static final int = 49202; //
	public static final int = 49203; //
	public static final int = 49204; //
	public static final int = 49205; //
	public static final int = 49206; //
	public static final int = 49207; //
	public static final int = 49208; //
	public static final int = 49209; //
	public static final int = 49210; //
	public static final int = 49211; //
	public static final int = 49212; //
	public static final int = 49213; //
	public static final int = 49214; //
	public static final int = 49215; //
	public static final int = 49216; //
	public static final int = 49217; //
	public static final int = 49218; //
	public static final int = 49219; //
	*/
	public static final int SCROLL_OF_ORC_EMISSARYS_POLYMORPH = 49220; //妖魔密使變形卷軸
	public static final int SCALE_OF_SHINING_LIGHT = 49309; //閃爍的鱗片
	public static final int SCROLL_OF_ENCHANT_ARMOR_IT = 49310; //象牙塔對盔甲施法的卷軸
	public static final int SCROLL_OF_ENCHANT_WEAPON_IT = 49311; //象牙塔對武器施法的卷軸
	public static final int POTION_OF_HASTE_WELFARE  = 49501;// 福利加速藥水
	public static final int POTION_OF_BREATHE_WELFARE = 49502; // 福利呼吸藥水
	public static final int POTION_OF_FOREST_WELFARE = 49503; // 福利森林藥水
	public static final int POTION_OF_EMOTION_BRAVERY_WELFARE = 49504; // 福利勇敢藥水
	public static final int POTION_OF_MANA_WELFARE = 49505; // 福利藍色藥水
	public static final int POTION_OF_EMOTION_WISDOM_WELFARE = 49506; // 福利慎重藥水
	public static final int POTION_OF_POLY_WELFARE = 49507; // 福利變形藥水
	
	public static final int KEY_OF_DRAGON = 50501;
	public static final int DEATHMATCH_WIN_FRAGMENT = 50515;
	public static final int GHOSTHOUSE_WIN_FRAGMENT = 50516;
	public static final int PETRACING_WIN_FRAGMENT = 50517;
	public static final int PETMATCH_WIN_FRAGMENT = 50518;
	public static final int UNLIMITEDBATTLE_WIN_FRAGMENT = 50519;
	public static final int KEY_OF_BANDITS_TREASURE_CHEST = 50531;
	
	/* BLESS */
	public static final int BLESS_POTION_OF_HEALING = 140010;
	public static final int BLESS_POTION_OF_EXTRA_HEALING = 140011;
	public static final int BLESS_POTION_OF_GREATER_HEAL = 140012;
	public static final int BLESS_POTION_OF_HASTE = 140013; //自我加速藥水
	public static final int BLESS_POTION_OF_EMOTION_BRAVERY = 140014;
	public static final int BLESS_POTION_OF_MANA_Recovery = 140015; //加速魔力回復藥水
	public static final int BLESS_POTION_OF_EMOTION_WISDOM = 140016; //慎重藥水
	public static final int BLESS_POTION_OF_GREATER_HASTE = 140018; //強化自我加速藥水
	public static final int BLESS_OF_ELVEN_WAFER = 140068; //精靈餅乾
	public static final int BLESS_SCROLL_OF_ENCHANT_ARMOR = 140074;
	public static final int BLESS_SCROLL_OF_ENCHANT_WEAPON = 140087;
	public static final int BLESS_SCROLL_OF_POLYMORPH = 140088; //變形卷軸
	public static final int BLESS_SCROLL_OF_Gians = 140129; //
	public static final int BLESS_SCROLL_OF_Kalbas = 140130; //金侃的卷軸
	/* CURSE */
	public static final int CURSE_POTION_OF_HEALING = 240010;
	public static final int CURSE_SCROLL_OF_ENCHANT_ARMOR = 240074;
	public static final int CURSE_SCROLL_OF_ENCHANT_WEAPON = 240087;
	
	
	//public static final int GINSENG = ?; //人蔘
	//public static final int BOTTLE = ?; //藥瓶
	//public static final int KEY_OF_MACROSS = ?; //時空之鑰
	//public static final int KEY_OF_WAREHOUSEMANAGER = ?; //角色專用倉庫鑰匙
	//public static final int STONE_OF_LAMIAS_POLYMORPH = ?; //變身石：拉曼斯
	//public static final int STONE_OF_ENDIAS_POLYMORPH = ?; //變身石：安迪斯
	//public static final int STONE_OF_EDEA_POLYMORP = ?; //變身石：艾迪爾
	//public static final int SEALED_LETTER = ?; //被封印的信 : 黑妖傳令兵身上的信 不可轉移 活動「聯合軍勝利大作戰」
	//public static final int DANTES_LETTER = ?; //丹特斯的信 : 由被封印的信所解開 不可轉移 活動「聯合軍勝利大作戰」
	//public static final int CAKE_OF_RECIPE = ?; //蛋糕食譜
	//public static final int CAKE_OF_HASTEN = ?; //加速蛋糕 : 人物速度 x1.33(3段加速)
	//public static final int CAKE_OF_FANTASY_BIRTHDAY = ?; //夢幻的生日蛋糕
	//public static final int GIFT_OF_BIRTHDAY = ?; //生日祝賀禮 : 效果時間24小時後未使用，自動刪除 打開能獲得生日祝賀蛋糕
	//public static final int CAKE_OF_BIRTHDAY = ?; //生日祝賀蛋糕 : 效果時間24小時後未使用，自動刪除 可以召喚「生日蛋糕怪」出現20分鐘
	//public static final int GIFT_BOX_CHRISTMAS = ?; //聖誕禮物盒 : 活動結束系統回收 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具 打開隨機獲得 聖誕蛋糕	1個 聖誕起司蛋糕1個 聖誕抹茶蛋糕1個 聖誕香蕉蛋糕塊1個 聖誕香蕉蛋糕1個 聖誕櫻桃蛋糕塊1個 聖誕櫻桃蛋糕1個 聖誕草莓蛋糕塊1個 聖誕草莓蛋糕1個
	//public static final int CAKE_OF_CHRISTMAS = ?; //聖誕蛋糕 : 可以恢復體力，相當於終極治癒藥水 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_CHRISTMAS_CHEESE = ?; //聖誕起司蛋糕 : 效果時間： 600秒 人物速度 x1.33(1段加速) 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_CHRISTMAS_GREEN_TEA = ?; //聖誕抹茶蛋糕 : 效果時間900秒 狩獵經驗值 x1.1 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_CHRISTMAS_CHERRY = ?; //聖誕櫻桃蛋糕 : 效果時間900秒 力量+1 攻擊成功+5 額外攻擊點數+3 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_CHRISTMAS_STRAWBERRT = ?; //聖誕草莓蛋糕 : 效果時間900秒 MP+50 智力+1 魔力恢復量+5 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_SLICE_CHRISTMAS_BANANA = ?; //聖誕香蕉蛋糕塊 : 效果時間300秒 敏捷+1 弓的命中率+5 弓的攻擊力+3 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_SLICE_CHRISTMAS_CHERRY = ?; //聖誕櫻桃蛋糕塊 : 效果時間300秒 力量+1 攻擊成功+5 額外攻擊點數+3 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_SLICE_CHRISTMAS_STRAWBERRT = ?; //聖誕草莓蛋糕塊 : 效果時間300秒 MP+50 智力+1 魔力恢復量+5 不可轉移 2009聖誕節「叮叮噹！騎麋鹿過聖誕！」的活動道具
	//public static final int CAKE_OF_SLICE_FANTASY_//夢幻的蛋糕塊 : 狩獵經驗值 x1.05 額外傷害減免+2
	//public static final int CAKE_OF_15TH_ANNIVERSARY = ?; //15週年紀念蛋糕 : 可以恢復體力，相當於終極治癒藥水 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_BANANA_15TH_ANNIVERSARY = ?; //15週年紀念香蕉蛋糕 : 效果時間900秒 敏捷+1 弓的命中率+5 弓的攻擊力+3 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_CHEESE_15TH_ANNIVERSARY = ?; //15週年紀念起司蛋糕 : 效果時間600秒 人物速度 x1.33(1段加速) 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_CHERRY_15TH_ANNIVERSARY = ?; //15週年紀念櫻桃蛋糕 : 效果時間900秒 力量+1 攻擊成功+5 額外攻擊點數+3 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_GREEN_TEA_15TH_ANNIVERSARY = ?; //15週年紀念抹茶蛋糕 : 效果時間900秒 狩獵經驗值 x1.1 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_STRAWBERRT_15TH_ANNIVERSARY = ?; //15週年紀念草莓蛋糕 : 效果時間900秒 MP+50 智力+1 魔力恢復量+5 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_SLICE_BANANA_15TH_ANNIVERSARY = ?; //15週年紀念香蕉蛋糕塊 : 效果時間300秒 敏捷+1 弓的命中率+5 弓的攻擊力+3 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_SLICE_CHERRY_15TH_ANNIVERSARY = ?; //15週年紀念櫻桃蛋糕塊 : 效果時間300秒 力量+1 攻擊成功+5 額外攻擊點數+3 不可轉移 台灣活動的活動道具
	//public static final int CAKE_OF_SLICE_STRAWBERRT_15TH_ANNIVERSARY = ?; //15週年紀念草莓蛋糕塊 : 效果時間300秒 MP+50 智力+1 魔力恢復量+5 不可轉移 台灣活動的活動道具
	
	//public static final int POTION_OF_ANCIENT_MANA_Recovery = ?;//古老的加速魔力回復藥水
	
	//public static final int SCROLL_OF_ENCHANT_BATTLE = ?; //強化戰鬥卷軸
	//public static final int SCROLL_OF_STRENGTHENING_POWER = ?; //體力增強卷軸
	//public static final int SCROLL_OF_STRENGTHENING_MAGIC_POWER = ?; //魔力增強卷軸
	//public static final int SCROLL_OF_ARCH_POLYMORPH = ?; //亞克變身卷軸
	
	//public static final int SCALE_OF_SERPENT = ?; //蛇鱗
	//public static final int SCALE_OF_SILVER_SERPENT = ?; //銀蛇鱗
	
	//public static final int BOOK_OF_ARCH_POLYMORPH = ?; //亞克變身魔法書
	//public static final int BOOK_OF_WEAPON_ENCHANT = ?; //武器強化書
	//public static final int BOOK_OF_ANCIENT_WEAPON_ENCHANT = ?; //古代武器強化書
	
	//public static final int SPELLBOOK_OF_ILLUSION = ?; //幻象魔法書 : 智力+1 魔防+10
	//public static final int SPELLBOOK_OF_PROHIBITION = ?;//禁斷的魔法書
	
	//public static final int CRYSTAL_OF_SPIRIT_NATURESMIRACLE = ?; //精靈水晶(生命呼喚) : 將已死亡的對象復活，並且體力完全恢復，但恢復後魔力為零。（未開放）
	
	//public static final int QUIVER_OF_EARTH_ARROW = ?; //地屬性箭筒 : 地屬性箭500支
	//public static final int QUIVER_OF_WATER_ARROW = ?; //水屬性箭筒 : 水屬性箭500支
	//public static final int QUIVER_OF_FIRE_ARROW = ?; //火屬性箭筒 : 火屬性箭500支
	//public static final int QUIVER_OF_WIND_ARROW = ?; //風屬性箭筒 : 風屬性箭500支
	
	
}