/* 20090617 rev1874  修改部份NPC資料 日文名稱資料 不建議中文使用者更改 */
Update npc Set nameid = 'シー シンガー' Where npcid  = '45228';
Update npc Set nameid = 'トライ ソウル' Where npcid  = '45316';
Update npc Set nameid = '歌う島のテレポーター' Where npcid  = '50082';
Update npc Set nameid = '歌う島へのテレポーター' Where npcid  = '50083';
Update npc Set nameid = 'ディオン' Where npcid  = '60037';
Update npc Set nameid = '行商ヨハン' Where npcid  = '70004';
Update npc Set nameid = 'ドロモンド' Where npcid  = '70997';
Update npc Set nameid = '歌う島のガイド' Where npcid  = '70998';
Update npc Set nameid = 'アレックス' Where npcid  = '70999';
Update npc Set nameid = 'アレックス' Where npcid  = '71000';
Update npc Set nameid = '薬草師クスシー' Where npcid  = '71001';
Update npc Set nameid = 'キャンセレーション師' Where npcid  = '71002';
Update npc Set nameid = '鍛冶屋ロン' Where npcid  = '71003';
Update npc Set nameid = 'アデーレ' Where npcid  = '71004';
Update npc Set nameid = 'ポピレア' Where npcid  = '71005';
Update npc Set nameid = 'ティミー' Where npcid  = '71006';
Update npc Set nameid = 'ディラン' Where npcid  = '71007';
Update npc Set nameid = '血盟募集 $1385' Where npcid  = '71008';
Update npc Set nameid = 'チコリー' Where npcid  = '71009';
Update npc Set nameid = 'チコリー' Where npcid  = '71010';
Update npc Set nameid = 'ブリアナ' Where npcid  = '71011';
Update npc Set nameid = 'ブリアナ' Where npcid  = '71012';
Update npc Set nameid = '村の自警団' Where npcid  = '71014';
Update npc Set nameid = '村の自警団' Where npcid  = '71015';
Update npc Set nameid = '村の自警団' Where npcid  = '71016';
Update npc Set nameid = '村の自警団' Where npcid  = '71017';
Update npc Set nameid = 'フェーダ' Where npcid  = '71018';
Update npc Set nameid = '弟子ヴート' Where npcid  = '71019';
Update npc Set nameid = 'ジョン' Where npcid  = '71020';
Update npc Set nameid = '骨細工師マッティ' Where npcid  = '71021';
Update npc Set nameid = '骨細工師ジーナン' Where npcid  = '71022';
Update npc Set nameid = '骨細工師ケーイ' Where npcid  = '71023';
Update npc Set nameid = 'ケスキン' Where npcid  = '71025';
Update npc Set nameid = 'ココ' Where npcid  = '71026';
Update npc Set nameid = 'クン' Where npcid  = '71027';
Update npc Set nameid = 'キヨリ' Where npcid  = '71028';
Update npc Set nameid = 'スカイ' Where npcid  = '71029';
Update npc Set nameid = '傭兵ライアン' Where npcid  = '71031';
Update npc Set nameid = '冒険者エータ' Where npcid  = '71032';
Update npc Set nameid = 'ハーミット' Where npcid  = '71033';
Update npc Set nameid = 'ラビ' Where npcid  = '71034';
Update npc Set nameid = '歌う島へのテレポーター' Where npcid  = '71035';
Update npc Set nameid = 'ヤング ムリアン' Where npcid  = '81048';
Update npc Set nameid = 'シー ハンター' Where npcid  = '81077';
Update npc Set nameid = 'ジャイアント アント ウィッチ' Where npcid  = '81078';
Update npc Set nameid = 'グランド センチピード' Where npcid  = '81079';
Update npc Set nameid = 'パプリオンの信奉者' Where npcid  = '81081';