UPDATE trap SET note  = "捕獸夾" WHERE  id  = "1";
UPDATE trap SET note  = "治癒術" WHERE  id  = "2";
UPDATE trap SET note  = "攻擊毒" WHERE  id  = "3";
UPDATE trap SET note  = "沉默毒" WHERE  id  = "4";
UPDATE trap SET note  = "麻痺毒" WHERE  id  = "5";
UPDATE trap SET note  = "流星雨" WHERE  id  = "6";
UPDATE trap SET note  = "針(横)" WHERE  id  = "7";
UPDATE trap SET note  = "傲慢之塔 4樓-怪物" WHERE  id  = "8";
UPDATE trap SET note  = "傲慢之塔 8樓-怪物" WHERE  id  = "9";
UPDATE trap SET note  = "傲慢之塔 14樓-怪物" WHERE  id  = "10";
UPDATE trap SET note  = "傲慢之塔 18樓-怪物" WHERE  id  = "11";
UPDATE trap SET note  = "傲慢之塔 24樓-怪物" WHERE  id  = "12";
UPDATE trap SET note  = "傲慢之塔 28樓-怪物" WHERE  id  = "13";
UPDATE trap SET note  = "傲慢之塔 34樓-怪物" WHERE  id  = "14";
UPDATE trap SET note  = "傲慢之塔 38樓-怪物" WHERE  id  = "15";
UPDATE trap SET note  = "傲慢之塔 44樓-怪物" WHERE  id  = "16";
UPDATE trap SET note  = "傲慢之塔 48樓-怪物" WHERE  id  = "17";
UPDATE trap SET note  = "傲慢之塔 54樓-怪物" WHERE  id  = "18";
UPDATE trap SET note  = "傲慢之塔 64樓-怪物" WHERE  id  = "19";
UPDATE trap SET note  = "傲慢之塔 74樓-怪物" WHERE  id  = "20";
UPDATE trap SET note  = "傲慢之塔 78樓-怪物" WHERE  id  = "21";
UPDATE trap SET note  = "傲慢之塔 84樓-怪物" WHERE  id  = "22";
UPDATE trap SET note  = "傲慢之塔 94樓-怪物" WHERE  id  = "23";
UPDATE trap SET note  = "象牙塔 4樓-鋼鐵高崙" WHERE  id  = "24";
UPDATE trap SET note  = "象牙塔 4樓-密密" WHERE  id  = "25";
UPDATE trap SET note  = "象牙塔 4樓-活鎧甲" WHERE  id  = "26";
UPDATE trap SET note  = "象牙塔 5樓-鋼鐵高崙" WHERE  id  = "27";
UPDATE trap SET note  = "象牙塔 5樓-密密" WHERE  id  = "28";
UPDATE trap SET note  = "象牙塔 5樓-活鎧甲" WHERE  id  = "29";
UPDATE trap SET note  = "象牙塔 6樓-影魔" WHERE  id  = "30";
UPDATE trap SET note  = "象牙塔 6樓-死神" WHERE  id  = "31";
UPDATE trap SET note  = "象牙塔 7樓-影魔" WHERE  id  = "32";
UPDATE trap SET note  = "象牙塔 7樓-死神" WHERE  id  = "33";
UPDATE trap SET note  = "象牙塔 8樓-鋼鐵高崙" WHERE  id  = "34";
UPDATE trap SET note  = "象牙塔 8樓-影魔" WHERE  id  = "35";
UPDATE trap SET note  = "象牙塔 8樓-死神" WHERE  id  = "36";
UPDATE trap SET note  = "象牙塔 8樓-活鎧甲" WHERE  id  = "37";
UPDATE trap SET note  = "福朗克的迷宮-海賊骷髏" WHERE  id  = "38";
UPDATE trap SET note  = "福朗克的迷宮-海賊骷髏士兵" WHERE  id  = "39";
UPDATE trap SET note  = "福朗克的迷宮-海賊骷髏首領" WHERE  id  = "40";
UPDATE trap SET note  = "福朗克的迷宮-海賊骷髏刀手" WHERE  id  = "41";
UPDATE trap SET note  = "福朗克的迷宮-開始地點" WHERE  id  = "42";
UPDATE trap SET note  = "迪哥的廢氣監獄-開始地點" WHERE  id  = "43";
UPDATE trap SET note  = "幽靈之家-木乃伊的詛咒" WHERE  id  = "44";
UPDATE trap SET note  = "幽靈之家-闇盲咒術" WHERE  id  = "45";
UPDATE trap SET note  = "幽靈之家-緩速術" WHERE  id  = "46";
UPDATE trap SET note  = "幽靈之家-加速術" WHERE  id  = "47";
UPDATE trap SET note  = "幽靈之家-傳送術" WHERE  id  = "48";
UPDATE trap SET note  = "幽靈之家-傳送術" WHERE  id  = "49";
UPDATE trap SET note  = "幽靈之家-傳送術" WHERE  id  = "50";
UPDATE trap SET note  = "幽靈之家-傳送術" WHERE  id  = "51";
UPDATE trap SET note  = "幽靈之家-傳送術" WHERE  id  = "52";
