/*
 * 20090517 怪物技能中文說明
 */
Update mobskill Set mobname = '暴走兔(冰錐)' Where mobid = '45049';
Update mobskill Set mobname = '歐吉(範圍)' Where mobid = '45278';
Update mobskill Set mobname = '黑暗棲林者(遠距離攻擊)' Where mobid = '45347';
Update mobskill Set mobname = '恐怖的地獄犬(火燄)' Where mobid = '45471';
Update mobskill Set mobname = '大王烏賊(迴轉漩渦)' Where mobid = '45734';
Update mobskill Set mobname = '阿魯巴(加速術)' Where mobid = '45373';
Update mobskill Set mobname = '阿魯巴(加速術)' Where mobid = '45505';
Update mobskill Set mobname = '小安加斯(火焰噴吐)' Where mobid = '45746';
Update mobskill Set mobname = '食腐獸(遠距離特殊攻擊)' Where mobid = '46065' AND actNo = '0';
Update mobskill Set mobname = '地獄束縛犬(火焰噴吐)' Where mobid = '45512';
Update mobskill Set mobname = '血騎士(迴旋斬)' Where mobid = '45527';
Update mobskill Set mobname = '混沌(呼喚傳送術)' Where mobid = '45625' AND actNo = '0';
Update mobskill Set mobname = '混沌(物理攻擊)' Where mobid = '45625'AND Type = '1';
Update mobskill Set mobname = '混沌(衝擊之暈)' Where mobid = '45625' AND actNo = '2';
Update mobskill Set mobname = '混沌(地裂術)' Where mobid = '45625' AND actNo = '3';
Update mobskill Set mobname = '混沌(召喚混沌的司祭A)' Where mobid = '45625' AND actNo = '4';
Update mobskill Set mobname = '混沌(召喚混沌的司祭b)' Where mobid = '45625' AND actNo = '5';
Update mobskill Set mobname = '混沌(召喚混沌的司祭c)' Where mobid = '45625' AND actNo = '6';

/*20090601 怪物技能中文化*/
Update mobskill Set mobname = '暴走兔(冰錐)' Where mobid =45049 AND actNo = 0;
Update mobskill Set mobname = '南瓜怪(強力攻撃)' Where mobid =45167 AND actNo = 0;
Update mobskill Set mobname = '艾爾摩法師(冰錐)' Where mobid =45224 AND actNo = 0;
Update mobskill Set mobname = '海之歌姬(小龍捲風)' Where mobid =45228 AND actNo = 0;
Update mobskill Set mobname = '地獄犬(炎)' Where mobid =45241 AND actNo = 0;
Update mobskill Set mobname = '黑暗妖精魔法學徒(冰錐)' Where mobid =45256 AND actNo = 0;
Update mobskill Set mobname = '黑暗妖精魔法學徒(龍捲風)' Where mobid =45256 AND actNo = 1;
Update mobskill Set mobname = '深淵之花(遠距離攻撃)' Where mobid =45273 AND actNo = 0;
Update mobskill Set mobname = '黑暗安特(範囲魔法)' Where mobid =45275 AND actNo = 0;
Update mobskill Set mobname = '歐吉(範圍)' Where mobid =45278 AND actNo = 0;
Update mobskill Set mobname = '奇岩 地獄犬(炎)' Where mobid =45283 AND actNo = 0;
Update mobskill Set mobname = '火焰戰士(突刺)' Where mobid =45284 AND actNo = 0;
Update mobskill Set mobname = '火焰弓箭手(近接攻撃)' Where mobid =45291 AND actNo = 0;
Update mobskill Set mobname = '地底蟹人(大螯攻擊)' Where mobid =45297 AND actNo = 0;
Update mobskill Set mobname = '炎魔的分身(地板炸裂)' Where mobid =45315 AND actNo = 0;
Update mobskill Set mobname = '試煉靈魂(玩家召回)' Where mobid =45316 AND actNo = 0;
Update mobskill Set mobname = '試煉靈魂(魔法相消術)' Where mobid =45316 AND actNo = 1;
Update mobskill Set mobname = '試煉靈魂(広範囲魔法)' Where mobid =45316 AND actNo = 2;
Update mobskill Set mobname = '試煉靈魂(召還:巨人)' Where mobid =45316 AND actNo = 3;
Update mobskill Set mobname = '試煉靈魂(物理攻撃)' Where mobid =45316 AND actNo = 4;
Update mobskill Set mobname = '黑暗棲林者(範囲魔法)' Where mobid =45326 AND actNo = 0;
Update mobskill Set mobname = '烈炎獸(炎)' Where mobid =45341 AND actNo = 0;
Update mobskill Set mobname = '烈炎獸(頭突き)' Where mobid =45341 AND actNo = 1;
Update mobskill Set mobname = '黑暗棲林者(遠距離攻擊)' Where mobid =45347 AND actNo = 0;
Update mobskill Set mobname = '黑暗精靈使(範囲魔法)' Where mobid =45363 AND actNo = 0;
Update mobskill Set mobname = '黑暗精靈使(召還:闇之精靈)' Where mobid =45363 AND actNo = 1;
Update mobskill Set mobname = '喚獸師(遠距離攻撃)' Where mobid =45368 AND actNo = 0;
Update mobskill Set mobname = '阿魯巴(加速術)' Where mobid =45373 AND actNo = 0;
Update mobskill Set mobname = '地底蜥蜴人(遠距離攻撃)' Where mobid =45374 AND actNo = 0;
Update mobskill Set mobname = '地底魔蠍(螯突刺)' Where mobid =45382 AND actNo = 0;
Update mobskill Set mobname = '地底蛇蠍(螯突刺)' Where mobid =45383 AND actNo = 0;
Update mobskill Set mobname = '炎魔的思克巴(強化魅魔之吻)' Where mobid =45391 AND actNo = 0;
Update mobskill Set mobname = '炎魔的思克巴(吸血鬼之吻)' Where mobid =45391 AND actNo = 1;
Update mobskill Set mobname = '思克巴(強化魅魔之吻)' Where mobid =45393 AND actNo = 0;
Update mobskill Set mobname = '思克巴(吸血鬼之吻)' Where mobid =45393 AND actNo = 1;
Update mobskill Set mobname = '思克巴(強化魅魔之吻)' Where mobid =45394 AND actNo = 0;
Update mobskill Set mobname = '思克巴(吸血鬼之吻)' Where mobid =45394 AND actNo = 1;
Update mobskill Set mobname = '思克巴(強化魅魔之吻)' Where mobid =45400 AND actNo = 0;
Update mobskill Set mobname = '思克巴(吸血鬼之吻)' Where mobid =45400 AND actNo = 1;
Update mobskill Set mobname = '黑法師(範囲魔法)' Where mobid =45405 AND actNo = 0;
Update mobskill Set mobname = '烈炎獸(炎)' Where mobid =45408 AND actNo = 0;
Update mobskill Set mobname = '烈炎獸(頭突き)' Where mobid =45408 AND actNo = 1;
Update mobskill Set mobname = '迪哥(震裂術)' Where mobid =45413 AND actNo = 0;
Update mobskill Set mobname = '地之牙(束縛術)' Where mobid =45416 AND actNo = 0;
Update mobskill Set mobname = '地之牙(地獄之牙)' Where mobid =45416 AND actNo = 1;
Update mobskill Set mobname = '風之牙(緩速術)' Where mobid =45418 AND actNo = 0;
Update mobskill Set mobname = '風之牙(風刃)' Where mobid =45418 AND actNo = 1;
Update mobskill Set mobname = '水之牙(弱化術)' Where mobid =45419 AND actNo = 0;
Update mobskill Set mobname = '水之牙(冰錐)' Where mobid =45419 AND actNo = 1;
Update mobskill Set mobname = '地底巨王龜(寒冰氣息)' Where mobid =45422 AND actNo = 0;
Update mobskill Set mobname = '地底巨王龜(緩速術)' Where mobid =45422 AND actNo = 1;
Update mobskill Set mobname = '地底巨王龜(弱化術)' Where mobid =45422 AND actNo = 2;
Update mobskill Set mobname = '地底巨王龜(物理攻撃)' Where mobid =45422 AND actNo = 3;
Update mobskill Set mobname = '地底多眼怪(風之枷鎖)' Where mobid =45423 AND actNo = 0;
Update mobskill Set mobname = '火之牙(疾病術)' Where mobid =45424 AND actNo = 0;
Update mobskill Set mobname = '火之牙(火箭)' Where mobid =45424 AND actNo = 1;
Update mobskill Set mobname = '黑法師(範囲魔法)' Where mobid =45425 AND actNo = 0;
Update mobskill Set mobname = '炎魔的思克巴女皇(強化魅魔之吻)' Where mobid =45450 AND actNo = 0;
Update mobskill Set mobname = '炎魔的思克巴女皇(吸血鬼之吻)' Where mobid =45450 AND actNo = 1;
Update mobskill Set mobname = '思克巴女皇(強化魅魔之吻)' Where mobid =45451 AND actNo = 0;
Update mobskill Set mobname = '思克巴女皇(吸血鬼之吻)' Where mobid =45451 AND actNo = 1;
Update mobskill Set mobname = '魔法師(極光雷電)' Where mobid =45456 AND actNo = 0;
Update mobskill Set mobname = '德雷克(範囲攻撃)' Where mobid =45458 AND actNo = 0;
Update mobskill Set mobname = '德雷克(単体攻撃)' Where mobid =45458 AND actNo = 1;
Update mobskill Set mobname = '德雷克(物理攻撃)' Where mobid =45458 AND actNo = 2;
Update mobskill Set mobname = '西瑪(極光雷電)' Where mobid =45464 AND actNo = 0;
Update mobskill Set mobname = '恐怖的地獄犬(火燄)' Where mobid =45471 AND actNo = 0;
Update mobskill Set mobname =  '巴土瑟(地裂術)' Where mobid =45473 AND actNo = 0;
Update mobskill Set mobname = '闇黑棲林者(範囲魔法)' Where mobid =45474 AND actNo = 0;
Update mobskill Set mobname = '地獄犬(炎)' Where mobid =45476 AND actNo = 0;
Update mobskill Set mobname = '火燄之魔法師(燃燒的火球)' Where mobid =45480 AND actNo = 0;
Update mobskill Set mobname = '火燄之魔法師(物理攻撃)' Where mobid =45480 AND actNo = 1;
Update mobskill Set mobname = '小惡魔(火炎魔方陣)' Where mobid =45481 AND actNo = 0;
Update mobskill Set mobname = '小惡魔(物理攻撃)' Where mobid =45481 AND actNo = 1;
Update mobskill Set mobname = '炎魔的小惡魔(火炎魔方陣)' Where mobid =45482 AND actNo = 0;
Update mobskill Set mobname = '炎魔的小惡魔(物理攻撃)' Where mobid =45482 AND actNo = 1;
Update mobskill Set mobname = '暗黑萊肯(物理攻撃)' Where mobid =45485 AND actNo = 0;
Update mobskill Set mobname = '地底伊萊克頓(極光雷電)' Where mobid =45487 AND actNo = 0;
Update mobskill Set mobname = '地底伊萊克頓(広範囲電撃攻撃)' Where mobid =45487 AND actNo = 1;
Update mobskill Set mobname = '卡士伯(燃燒的火球)' Where mobid =45488 AND actNo = 0;
Update mobskill Set mobname = '庫曼(遠距離攻撃)' Where mobid =45492 AND actNo = 0;
Update mobskill Set mobname = '幼龍(炎)' Where mobid =45496 AND actNo = 0;
Update mobskill Set mobname = '馬庫爾(光箭)' Where mobid =45497 AND actNo = 0;
Update mobskill Set mobname = '墳墓守護者(act30)' Where mobid =45498 AND actNo = 0;
Update mobskill Set mobname = '水靈之主(吸血鬼之吻)' Where mobid =45500 AND actNo = 0;
Update mobskill Set mobname = '水靈之主(冰錐)' Where mobid =45500 AND actNo = 1;
Update mobskill Set mobname = '水靈之主(物理攻撃)' Where mobid =45500 AND actNo = 2;
Update mobskill Set mobname = '暗黑黑騎士(物理攻撃)' Where mobid =45503 AND actNo = 0;
Update mobskill Set mobname = '阿魯巴(加速術)' Where mobid =45505 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的艾爾摩法師(冰錐)' Where mobid =45506 AND actNo = 0;
Update mobskill Set mobname = '地靈之主(束縛術)' Where mobid =45508 AND actNo = 0;
Update mobskill Set mobname = '地靈之主(地裂術)' Where mobid =45508 AND actNo = 1;
Update mobskill Set mobname = '風靈之主(緩速術)' Where mobid =45510 AND actNo = 0;
Update mobskill Set mobname = '風靈之主(極道落雷)' Where mobid =45510 AND actNo = 1;
Update mobskill Set mobname = '火靈之主(魔力奪取)' Where mobid =45511 AND actNo = 0;
Update mobskill Set mobname = '火靈之主(燃燒的火球)' Where mobid =45511 AND actNo = 1;
Update mobskill Set mobname = '地獄束縛犬(火焰噴吐)' Where mobid =45512 AND actNo = 0;
Update mobskill Set mobname = '潔尼斯女王(広範囲魔法)' Where mobid =45513 AND actNo = 0;
Update mobskill Set mobname = '伊弗利特(火燄投射)' Where mobid =45515 AND actNo = 0;
Update mobskill Set mobname = '伊弗利特(火焰投射)' Where mobid =45516 AND actNo = 0;
Update mobskill Set mobname = '血色術師(遠距離特殊攻撃)' Where mobid =45517 AND actNo = 0;
Update mobskill Set mobname = '血色術師(範囲特殊攻撃)' Where mobid =45517 AND actNo = 1;
Update mobskill Set mobname = '火焰烈炎獸(炎)' Where mobid =45520 AND actNo = 0;
Update mobskill Set mobname = '火焰烈炎獸(頭突き)' Where mobid =45520 AND actNo = 1;
Update mobskill Set mobname = '骨龍(炎)' Where mobid =45522 AND actNo = 0;
Update mobskill Set mobname = '闇黑君王(遠距離特殊攻撃)' Where mobid =45523 AND actNo = 0;
Update mobskill Set mobname = '闇黑君王(範囲特殊攻撃)' Where mobid =45523 AND actNo = 1;
Update mobskill Set mobname = '深紅飛龍(5セル範囲特殊攻撃)' Where mobid =45526 AND actNo = 0;
Update mobskill Set mobname = '血騎士(迴旋斬)' Where mobid =45527 AND actNo = 0;
Update mobskill Set mobname = '冷酷冰原老虎(物理攻撃)' Where mobid =45528 AND actNo = 0;
Update mobskill Set mobname = '飛龍(炎)' Where mobid =45529 AND actNo = 0;
Update mobskill Set mobname = '墳墓守護者法師(act1)' Where mobid =45530 AND actNo = 0;
Update mobskill Set mobname = '墳墓守護者法師(act18)' Where mobid =45530 AND actNo = 1;
Update mobskill Set mobname = '墳墓守護者法師(燃燒的火球)' Where mobid =45530 AND actNo = 2;
Update mobskill Set mobname = '暗黑火焰弓箭手(弓攻撃)' Where mobid =45532 AND actNo = 0;
Update mobskill Set mobname = '暗黑火焰弓箭手(近接攻撃)' Where mobid =45532 AND actNo = 1;
Update mobskill Set mobname = '曼波兔(龍捲風)' Where mobid =45534 AND actNo = 0;
Update mobskill Set mobname = '曼波兔(範囲)' Where mobid =45534 AND actNo = 1;
Update mobskill Set mobname = '曼波兔(冰裂術)' Where mobid =45535 AND actNo = 0;
Update mobskill Set mobname = '曼波兔(範囲)' Where mobid =45535 AND actNo = 1;
Update mobskill Set mobname = '墳墓守護者騎士(act30)' Where mobid =45537 AND actNo = 0;
Update mobskill Set mobname = '暗黑火焰戰士(突刺)' Where mobid =45540 AND actNo = 0;
Update mobskill Set mobname = '暗黑火焰戰士(斬擊)' Where mobid =45540 AND actNo = 1;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45542 AND actNo = 0;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45542 AND actNo = 1;
Update mobskill Set mobname = '黑長者(龍捲風)' Where mobid =45545 AND actNo = 0;
Update mobskill Set mobname = '黑長者(遠距離魔法)' Where mobid =45545 AND actNo = 1;
Update mobskill Set mobname = '變形怪首領(冰雪暴)' Where mobid =45546 AND actNo = 0;
Update mobskill Set mobname = '變形怪首領(火風暴)' Where mobid =45546 AND actNo = 1;
Update mobskill Set mobname = '變形怪首領(物理攻撃)' Where mobid =45546 AND actNo = 2;
Update mobskill Set mobname = '幻象眼魔(魔法)' Where mobid =45547 AND actNo = 0;
Update mobskill Set mobname = '幻象眼魔(物理攻撃)' Where mobid =45547 AND actNo = 1;
Update mobskill Set mobname = '豪勢(放射劍)' Where mobid =45548 AND actNo = 0;
Update mobskill Set mobname = '黑長者(龍捲風)' Where mobid =45550 AND actNo = 0;
Update mobskill Set mobname = '黑長者(極道落雷)' Where mobid =45550 AND actNo = 1;
Update mobskill Set mobname = '炎魔的巴風特(地裂術)' Where mobid =45569 AND actNo = 0;
Update mobskill Set mobname = '炎魔的巴風特(物理攻撃)' Where mobid =45569 AND actNo = 1;
Update mobskill Set mobname = '墮落的司祭(烈炎術)' Where mobid =45570 AND actNo = 0;
Update mobskill Set mobname = '火焰阿西塔基奧(物理攻撃)' Where mobid =45572 AND actNo = 0;
Update mobskill Set mobname = '巴風特(地裂術)' Where mobid =45573 AND actNo = 0;
Update mobskill Set mobname = '親衛隊長．凱特(8セル遠距離特殊攻撃)' Where mobid =45574 AND actNo = 0;
Update mobskill Set mobname = '死亡的司祭(玩家召回)' Where mobid =45575 AND actNo = 0;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45575 AND actNo = 1;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45575 AND actNo = 2;
Update mobskill Set mobname = '突擊旅長．闇黑劍士(遠距離特殊攻撃)' Where mobid =45577 AND actNo = 0;
Update mobskill Set mobname = '突擊旅長．闇黑劍士(範囲特殊攻撃)' Where mobid =45577 AND actNo = 1;
Update mobskill Set mobname = '炎魔的巴列斯(燃燒的火球)' Where mobid =45579 AND actNo = 0;
Update mobskill Set mobname = '炎魔的巴列斯(物理攻撃)' Where mobid =45579 AND actNo = 1;
Update mobskill Set mobname = '暗黑思克巴女皇(強化魅魔之吻)' Where mobid =45580 AND actNo = 0;
Update mobskill Set mobname = '暗黑思克巴女皇(吸血鬼之吻)' Where mobid =45580 AND actNo = 1;
Update mobskill Set mobname = '傲慢的潔尼斯女王(広範囲魔法)' Where mobid =45581 AND actNo = 0;
Update mobskill Set mobname = '傲慢的潔尼斯女王(物理攻撃)' Where mobid =45581 AND actNo = 1;
Update mobskill Set mobname = '墮落的司祭(範囲魔法)' Where mobid =45582 AND actNo = 0;
Update mobskill Set mobname = '巴列斯(燃燒的火球)' Where mobid =45583 AND actNo = 0;
Update mobskill Set mobname = '巨大牛人(震裂術)' Where mobid =45584 AND actNo = 0;
Update mobskill Set mobname = '巨大牛人(物理攻撃)' Where mobid =45584 AND actNo = 1;
Update mobskill Set mobname = '小幻象眼魔(魔法)' Where mobid =45586 AND actNo = 0;
Update mobskill Set mobname = '小幻象眼魔(物理攻撃)' Where mobid =45586 AND actNo = 1;
Update mobskill Set mobname = '魔獸師長．辛克萊(8セル遠距離特殊攻撃)' Where mobid =45588 AND actNo = 0;
Update mobskill Set mobname = '魔獸師長．辛克萊(火球召喚)' Where mobid =45588 AND actNo = 1;
Update mobskill Set mobname = '恐怖的殭屍王(広範囲魔法)' Where mobid =45589 AND actNo = 0;
Update mobskill Set mobname = '恐怖的殭屍王(物理攻撃)' Where mobid =45589 AND actNo = 1;
Update mobskill Set mobname = '深淵水靈(吸血鬼之吻)' Where mobid =45591 AND actNo = 0;
Update mobskill Set mobname = '深淵水靈(冰錐)' Where mobid =45591 AND actNo = 1;
Update mobskill Set mobname = '深淵水靈(物理攻撃)' Where mobid =45591 AND actNo = 2;
Update mobskill Set mobname = '深淵地靈(束縛術)' Where mobid =45592 AND actNo = 0;
Update mobskill Set mobname = '深淵地靈(地裂術)' Where mobid =45592 AND actNo = 1;
Update mobskill Set mobname = '深淵風靈(緩速術)' Where mobid =45593 AND actNo = 0;
Update mobskill Set mobname = '深淵風靈(極道落雷)' Where mobid =45593 AND actNo = 1;
Update mobskill Set mobname = '深淵火靈(魔力奪取)' Where mobid =45594 AND actNo = 0;
Update mobskill Set mobname = '深淵火靈(烈炎術)' Where mobid =45594 AND actNo = 1;
Update mobskill Set mobname = '深淵火靈(物理攻撃)' Where mobid =45594 AND actNo = 2;
Update mobskill Set mobname = '艾莉絲(龍捲風)' Where mobid =45595 AND actNo = 0;
Update mobskill Set mobname = '艾莉絲(物理攻撃)' Where mobid =45595 AND actNo = 1;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45597 AND actNo = 0;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45597 AND actNo = 1;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45598 AND actNo = 0;
Update mobskill Set mobname = '死亡的司祭(単体魔法)' Where mobid =45598 AND actNo = 1;
Update mobskill Set mobname = '混沌的司祭(衝擊之暈)' Where mobid =45599 AND actNo = 0;
Update mobskill Set mobname = '克特(震裂術)' Where mobid =45600 AND actNo = 0;
Update mobskill Set mobname = '克特(物理攻撃)' Where mobid =45600 AND actNo = 1;
Update mobskill Set mobname = '死亡騎士(吸血鬼之吻)' Where mobid =45601 AND actNo = 0;
Update mobskill Set mobname = '死亡騎士(震裂術)' Where mobid =45601 AND actNo = 1;
Update mobskill Set mobname = '死亡騎士(召還:史巴托)' Where mobid =45601 AND actNo = 2;
Update mobskill Set mobname = '死亡騎士(物理攻撃)' Where mobid =45601 AND actNo = 3;
Update mobskill Set mobname = '魔法團長．卡勒米爾(8セル遠距離特殊攻撃)' Where mobid =45602 AND actNo = 0;
Update mobskill Set mobname = '巨大墳墓守護者(act30)' Where mobid =45603 AND actNo = 0;
Update mobskill Set mobname = '馬昆斯吸血鬼(魔法)' Where mobid =45604 AND actNo = 0;
Update mobskill Set mobname = '馬昆斯吸血鬼(吸血鬼之吻)' Where mobid =45604 AND actNo = 1;
Update mobskill Set mobname = '馬昆斯吸血鬼(物理攻撃)' Where mobid =45604 AND actNo = 2;
Update mobskill Set mobname = '吸血鬼(召還:殘暴的骷髏神射手)' Where mobid =45606 AND actNo = 0;
Update mobskill Set mobname = '吸血鬼(召還:殘暴的骷髏鬥士)' Where mobid =45606 AND actNo = 1;
Update mobskill Set mobname = '吸血鬼(召還:殘暴的史巴托)' Where mobid =45606 AND actNo = 2;
Update mobskill Set mobname = '吸血鬼(魔法)' Where mobid =45606 AND actNo = 3;
Update mobskill Set mobname = '吸血鬼(吸血鬼之吻)' Where mobid =45606 AND actNo = 4;
Update mobskill Set mobname = '吸血鬼(召還:蝙蝠)' Where mobid =45606 AND actNo = 5;
Update mobskill Set mobname = '魔獸團長．凱巴勒(遠距離特殊攻撃)' Where mobid =45607 AND actNo = 0;
Update mobskill Set mobname = '魔獸團長．凱巴勒(範囲特殊攻撃)' Where mobid =45607 AND actNo = 1;
Update mobskill Set mobname = '傭兵隊長．麥帕斯托(遠距離特殊攻撃)' Where mobid =45608 AND actNo = 0;
Update mobskill Set mobname = '傭兵隊長．麥帕斯托(範囲特殊攻撃)' Where mobid =45608 AND actNo = 1;
Update mobskill Set mobname = '冰之女王(冰雪暴)' Where mobid =45609 AND actNo = 0;
Update mobskill Set mobname = '冰之女王(物理攻撃)' Where mobid =45609 AND actNo = 1;
Update mobskill Set mobname = '古代巨人(震裂術)' Where mobid =45610 AND actNo = 0;
Update mobskill Set mobname = '古代巨人(物理攻撃)' Where mobid =45610 AND actNo = 1;
Update mobskill Set mobname = '神官長．邦妮(8セル遠距離特殊攻撃)' Where mobid =45612 AND actNo = 0;
Update mobskill Set mobname = '巨蟻女皇(地割れ)' Where mobid =45614 AND actNo = 0;
Update mobskill Set mobname = '巨蟻女皇(物理攻撃)' Where mobid =45614 AND actNo = 1;
Update mobskill Set mobname = '冥法團長．可利波斯(遠距離特殊攻撃)' Where mobid =45615 AND actNo = 0;
Update mobskill Set mobname = '冥法團長．可利波斯(範囲特殊攻撃)' Where mobid =45615 AND actNo = 1;
Update mobskill Set mobname = '木乃伊王(物理攻撃)' Where mobid =45616 AND actNo = 0;
Update mobskill Set mobname = '不死鳥(遠距離火炎)' Where mobid =45617 AND actNo = 0;
Update mobskill Set mobname = '不死鳥(物理攻撃)' Where mobid =45617 AND actNo = 1;
Update mobskill Set mobname = '騎士范德(震裂術)' Where mobid =45618 AND actNo = 0;
Update mobskill Set mobname = '騎士范德(火球召喚)' Where mobid =45618 AND actNo = 1;
Update mobskill Set mobname = '騎士范德(召還:暗黑黑騎士)' Where mobid =45618 AND actNo = 2;
Update mobskill Set mobname = '騎士范德(物理攻撃)' Where mobid =45618 AND actNo = 3;
Update mobskill Set mobname = '土精靈王(遠距離魔法)' Where mobid =45619 AND actNo = 0;
Update mobskill Set mobname = '土精靈王(物理攻撃)' Where mobid =45619 AND actNo = 1;
Update mobskill Set mobname = '水精靈王(遠距離魔法)' Where mobid =45620 AND actNo = 0;
Update mobskill Set mobname = '水精靈王(物理攻撃)' Where mobid =45620 AND actNo = 1;
Update mobskill Set mobname = '風精靈王(龍捲風)' Where mobid =45621 AND actNo = 0;
Update mobskill Set mobname = '風精靈王(物理攻撃)' Where mobid =45621 AND actNo = 1;
Update mobskill Set mobname = '火精靈王(燃燒的火球)' Where mobid =45622 AND actNo = 0;
Update mobskill Set mobname = '火精靈王(物理攻撃)' Where mobid =45622 AND actNo = 1;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45624 AND actNo = 0;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45624 AND actNo = 1;
Update mobskill Set mobname = '混沌(呼喚傳送術)' Where mobid =45625 AND actNo = 0;
Update mobskill Set mobname = '貓' Where mobid =45039 AND actNo = 0;
Update mobskill Set mobname = '混沌(魔法消除)' Where mobid =45625 AND actNo = 1;
Update mobskill Set mobname = '混沌(地裂術)' Where mobid =45625 AND actNo = 2;
Update mobskill Set mobname = '混沌(召喚混沌的司祭A)' Where mobid =45625 AND actNo = 3;
Update mobskill Set mobname = '混沌(召喚混沌的司祭b)' Where mobid =45625 AND actNo = 4;
Update mobskill Set mobname = '混沌(召喚混沌的司祭c)' Where mobid =45625 AND actNo = 5;
Update mobskill Set mobname = '混沌(物理攻擊)' Where mobid =45625 AND actNo = 6;
Update mobskill Set mobname = '混沌的司祭(衝擊之暈)' Where mobid =45627 AND actNo = 0;
Update mobskill Set mobname = '火焰之影親衛兵(玩家召回)' Where mobid =45628 AND actNo = 0;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45628 AND actNo = 1;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45628 AND actNo = 2;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45629 AND actNo = 0;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45629 AND actNo = 1;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45630 AND actNo = 0;
Update mobskill Set mobname = '火焰之影親衛兵(単体魔法)' Where mobid =45630 AND actNo = 1;
Update mobskill Set mobname = '火焰之影親衛兵(衝擊之暈)' Where mobid =45631 AND actNo = 0;
Update mobskill Set mobname = '土精靈王(遠距離魔法)' Where mobid =45642 AND actNo = 0;
Update mobskill Set mobname = '土精靈王(物理攻撃)' Where mobid =45642 AND actNo = 1;
Update mobskill Set mobname = '水精靈王(遠距離魔法)' Where mobid =45643 AND actNo = 0;
Update mobskill Set mobname = '水精靈王(物理攻撃)' Where mobid =45643 AND actNo = 1;
Update mobskill Set mobname = '風精靈王(龍捲風)' Where mobid =45644 AND actNo = 0;
Update mobskill Set mobname = '風精靈王(物理攻撃)' Where mobid =45644 AND actNo = 1;
Update mobskill Set mobname = '火精靈王(燃燒的火球)' Where mobid =45645 AND actNo = 0;
Update mobskill Set mobname = '火精靈王(物理攻撃)' Where mobid =45645 AND actNo = 1;
Update mobskill Set mobname = '深淵之主(広範囲魔法)' Where mobid =45646 AND actNo = 0;
Update mobskill Set mobname = '深淵之主(魔法相消術)' Where mobid =45646 AND actNo = 1;
Update mobskill Set mobname = '深淵之主(燃燒的火球)' Where mobid =45646 AND actNo = 2;
Update mobskill Set mobname = '深淵之主(物理攻撃)' Where mobid =45646 AND actNo = 3;
Update mobskill Set mobname = '炎魔的惡魔(広範囲魔法)' Where mobid =45647 AND actNo = 0;
Update mobskill Set mobname = '炎魔的惡魔(燃燒的火球)' Where mobid =45647 AND actNo = 1;
Update mobskill Set mobname = '炎魔的惡魔(物理攻撃)' Where mobid =45647 AND actNo = 2;
Update mobskill Set mobname = '惡魔(広範囲魔法)' Where mobid =45649 AND actNo = 0;
Update mobskill Set mobname = '惡魔(燃燒的火球)' Where mobid =45649 AND actNo = 1;
Update mobskill Set mobname = '惡魔(召還:鬼魂)' Where mobid =45649 AND actNo = 2;
Update mobskill Set mobname = '惡魔(召還:骷髏神射手)' Where mobid =45649 AND actNo = 3;
Update mobskill Set mobname = '惡魔(召還:高崙熔岩怪)' Where mobid =45649 AND actNo = 4;
Update mobskill Set mobname = '惡魔(召還:鋼鐵高崙)' Where mobid =45649 AND actNo = 5;
Update mobskill Set mobname = '惡魔(召還:烈炎獸)' Where mobid =45649 AND actNo = 6;
Update mobskill Set mobname = '惡魔(召還:阿魯巴)' Where mobid =45649 AND actNo = 7;
Update mobskill Set mobname = '惡魔(召還:獨眼巨人)' Where mobid =45649 AND actNo = 8;
Update mobskill Set mobname = '惡魔(物理攻撃)' Where mobid =45649 AND actNo = 9;
Update mobskill Set mobname = '殭屍王(広範囲魔法)' Where mobid =45650 AND actNo = 0;
Update mobskill Set mobname = '殭屍王(物理攻撃)' Where mobid =45650 AND actNo = 1;
Update mobskill Set mobname = '巴蘭卡(範囲)' Where mobid =45651 AND actNo = 0;
Update mobskill Set mobname = '巴蘭卡(召還:黑虎)' Where mobid =45651 AND actNo = 1;
Update mobskill Set mobname = '巴蘭卡(物理範囲)' Where mobid =45651 AND actNo = 2;
Update mobskill Set mobname = '木乃伊王(物理攻撃)' Where mobid =45653 AND actNo = 0;
Update mobskill Set mobname =  '艾莉絲(龍捲風)' Where mobid =45654 AND actNo = 0;
Update mobskill Set mobname = '艾莉絲(物理攻撃)' Where mobid =45654 AND actNo = 1;
Update mobskill Set mobname = '騎士范德(物理攻撃)' Where mobid =45664 AND actNo = 0;
Update mobskill Set mobname = '阿利歐克(特殊)' Where mobid =45671 AND actNo = 0;
Update mobskill Set mobname = '阿利歐克(物理攻撃)' Where mobid =45671 AND actNo = 1;
Update mobskill Set mobname = '巫妖(広範囲魔法)' Where mobid =45672 AND actNo = 0;
Update mobskill Set mobname = '巫妖(遠距離魔法)' Where mobid =45672 AND actNo = 1;
Update mobskill Set mobname = '巫妖(物理攻撃)' Where mobid =45672 AND actNo = 2;
Update mobskill Set mobname = '鐮刀死神(遠距離魔法)' Where mobid =45673 AND actNo = 0;
Update mobskill Set mobname = '鐮刀死神(広範囲魔法)' Where mobid =45673 AND actNo = 1;
Update mobskill Set mobname = '鐮刀死神(物理範囲攻撃)' Where mobid =45673 AND actNo = 2;
Update mobskill Set mobname = '死亡(玩家召回)' Where mobid =45674 AND actNo = 0;
Update mobskill Set mobname = '死亡(衝擊之暈)' Where mobid =45674 AND actNo = 1;
Update mobskill Set mobname = '死亡(魔法相消術)' Where mobid =45674 AND actNo = 2;
Update mobskill Set mobname = '死亡(召喚:死亡的司祭)' Where mobid =45674 AND actNo = 3;
Update mobskill Set mobname = '死亡(召喚:死亡的司祭)' Where mobid =45674 AND actNo = 4;
Update mobskill Set mobname = '死亡(召喚:死亡的司祭)' Where mobid =45674 AND actNo = 5;
Update mobskill Set mobname = '死亡(召喚:死亡的司祭)' Where mobid =45674 AND actNo = 6;
Update mobskill Set mobname = '死亡(召喚:死亡的司祭ス)' Where mobid =45674 AND actNo = 7;
Update mobskill Set mobname = '死亡(光箭)' Where mobid =45674 AND actNo = 8;
Update mobskill Set mobname = '死亡(特殊攻撃)' Where mobid =45674 AND actNo = 9;
Update mobskill Set mobname = '火焰之影(ブレス)' Where mobid =45675 AND actNo = 0;
Update mobskill Set mobname = '火焰之影(物理攻撃)' Where mobid =45675 AND actNo = 1;
Update mobskill Set mobname = '火焰之影(物理攻撃2)' Where mobid =45675 AND actNo = 2;
Update mobskill Set mobname = '冥法軍王．海露拜(召還:血色術師)' Where mobid =45676 AND actNo = 0;
Update mobskill Set mobname = '冥法軍王．海露拜(召還:闇黑君王)' Where mobid =45676 AND actNo = 1;
Update mobskill Set mobname = '冥法軍王．海露拜(火球召喚)' Where mobid =45676 AND actNo = 2;
Update mobskill Set mobname = '蕾雅(冰裂術)' Where mobid =45677 AND actNo = 0;
Update mobskill Set mobname = '蕾雅(強制変身:オーク)' Where mobid =45677 AND actNo = 1;
Update mobskill Set mobname = '蕾雅(召還:召喚精靈使)' Where mobid =45677 AND actNo = 2;
Update mobskill Set mobname = '賽尼斯(全部治癒術)' Where mobid =45678 AND actNo = 0;
Update mobskill Set mobname = '賽尼斯(冰雪暴)' Where mobid =45678 AND actNo = 1;
Update mobskill Set mobname = '賽尼斯(流星雨)' Where mobid =45678 AND actNo = 2;
Update mobskill Set mobname = '反王肯恩(範囲攻撃)' Where mobid =45680 AND actNo = 0;
Update mobskill Set mobname = '反王肯恩(物理攻撃)' Where mobid =45680 AND actNo = 1;
Update mobskill Set mobname = '林德拜爾(電撃)' Where mobid =45681 AND actNo = 0;
Update mobskill Set mobname = '林德拜爾(安息)' Where mobid =45681 AND actNo = 1;
Update mobskill Set mobname = '林德拜爾(電撃:遠距離)' Where mobid =45681 AND actNo = 2;
Update mobskill Set mobname = '林德拜爾(電撃:近距離)' Where mobid =45681 AND actNo = 3;
Update mobskill Set mobname = '林德拜爾(首振り)' Where mobid =45681 AND actNo = 4;
Update mobskill Set mobname = '林德拜爾(右手)' Where mobid =45681 AND actNo = 5;
Update mobskill Set mobname = '林德拜爾(左手)' Where mobid =45681 AND actNo = 6;
Update mobskill Set mobname = '安塔瑞斯(ブレス)' Where mobid =45682 AND actNo = 0;
Update mobskill Set mobname = '安塔瑞斯(安息)' Where mobid =45682 AND actNo = 1;
Update mobskill Set mobname = '安塔瑞斯(地裂術)' Where mobid =45682 AND actNo = 2;
Update mobskill Set mobname = '安塔瑞斯(ブレス:遠距離)' Where mobid =45682 AND actNo = 3;
Update mobskill Set mobname = '安塔瑞斯(ブレス:近距離)' Where mobid =45682 AND actNo = 4;
Update mobskill Set mobname = '安塔瑞斯(首振り)' Where mobid =45682 AND actNo = 5;
Update mobskill Set mobname = '安塔瑞斯(右手)' Where mobid =45682 AND actNo = 6;
Update mobskill Set mobname = '安塔瑞斯(左手)' Where mobid =45682 AND actNo = 7;
Update mobskill Set mobname = '法利昂(泡)' Where mobid =45683 AND actNo = 0;
Update mobskill Set mobname = '法利昂(泡:遠距離)' Where mobid =45683 AND actNo = 1;
Update mobskill Set mobname = '法利昂(泡:近距離)' Where mobid =45683 AND actNo = 2;
Update mobskill Set mobname = '法利昂(アイスブレス)' Where mobid =45683 AND actNo = 3;
Update mobskill Set mobname = '法利昂(首振り)' Where mobid =45683 AND actNo = 4;
Update mobskill Set mobname = '法利昂(右手)' Where mobid =45683 AND actNo = 5;
Update mobskill Set mobname = '法利昂(左手)' Where mobid =45683 AND actNo = 6;
Update mobskill Set mobname = '法利昂(尻尾)' Where mobid =45683 AND actNo = 7;
Update mobskill Set mobname = '法利昂(安息)' Where mobid =45683 AND actNo = 8;
Update mobskill Set mobname = '巴拉卡斯(メテオ)' Where mobid =45684 AND actNo = 0;
Update mobskill Set mobname = '巴拉卡斯(メテオ:遠距離)' Where mobid =45684 AND actNo = 1;
Update mobskill Set mobname = '巴拉卡斯(メテオ:近距離)' Where mobid =45684 AND actNo = 2;
Update mobskill Set mobname = '巴拉卡斯(安息)' Where mobid =45684 AND actNo = 3;
Update mobskill Set mobname = '巴拉卡斯(首振り)' Where mobid =45684 AND actNo = 4;
Update mobskill Set mobname = '巴拉卡斯(右手)' Where mobid =45684 AND actNo = 5;
Update mobskill Set mobname = '堕落(強制変身:ゾンビ)' Where mobid =45685 AND actNo = 0;
Update mobskill Set mobname = '堕落(広範囲魔法)' Where mobid =45685 AND actNo = 1;
Update mobskill Set mobname = '堕落(召還:墮落的司祭)' Where mobid =45685 AND actNo = 2;
Update mobskill Set mobname = '堕落(召還:墮落的司祭)' Where mobid =45685 AND actNo = 3;
Update mobskill Set mobname = '堕落(召還:墮落的司祭)' Where mobid =45685 AND actNo = 4;
Update mobskill Set mobname = '堕落(召還:墮落的司祭)' Where mobid =45685 AND actNo = 5;
Update mobskill Set mobname = '堕落(召還:墮落的司祭)' Where mobid =45685 AND actNo = 6;
Update mobskill Set mobname = '高等小獵犬(地獄之牙)' Where mobid =45692 AND actNo = 0;
Update mobskill Set mobname = '高等聖伯納犬(風刃)' Where mobid =45693 AND actNo = 0;
Update mobskill Set mobname = '高等狐狸(火箭)' Where mobid =45694 AND actNo = 0;
Update mobskill Set mobname = '高等暴走兔(冰錐)' Where mobid =45695 AND actNo = 0;
Update mobskill Set mobname = '高等貓(寒冷戰慄)' Where mobid =45696 AND actNo = 0;
Update mobskill Set mobname = '憤怒的古代人亡靈(極光雷電)' Where mobid =45701 AND actNo = 0;
Update mobskill Set mobname = '憤怒的古代人亡靈(地裂術)' Where mobid =45702 AND actNo = 0;
Update mobskill Set mobname = '憤怒的古代人亡靈(燃燒的火球)' Where mobid =45703 AND actNo = 0;
Update mobskill Set mobname = '憤怒的古代人亡靈(光箭)' Where mobid =45704 AND actNo = 0;
Update mobskill Set mobname = '炎魔創造物(火炎魔方陣)' Where mobid =45708 AND actNo = 0;
Update mobskill Set mobname = '炎魔僕人(広範囲魔法)' Where mobid =45709 AND actNo = 0;
Update mobskill Set mobname = '炎魔僕人(燃燒的火球)' Where mobid =45709 AND actNo = 1;
Update mobskill Set mobname = '炎魔僕人(物理攻撃)' Where mobid =45709 AND actNo = 2;
Update mobskill Set mobname = '真．虎男(遠距離魔法)' Where mobid =45710 AND actNo = 0;
Update mobskill Set mobname = '高麗犬(遠距離魔法)' Where mobid =45712 AND actNo = 0;
Update mobskill Set mobname = '船舶之墓殭屍(2セル遠距離特殊攻撃)' Where mobid =45720 AND actNo = 0;
Update mobskill Set mobname = '船舶之墓殭屍(6セル遠距離魔法攻撃)' Where mobid =45721 AND actNo = 0;
Update mobskill Set mobname = '船舶之墓殭屍(束縛術)' Where mobid =45721 AND actNo = 1;
Update mobskill Set mobname = '船舶的惡靈(召還:船舶的惡靈召喚物)' Where mobid =45723 AND actNo = 0;
Update mobskill Set mobname = '深海希爾黛斯(6セル遠距離特殊攻撃)' Where mobid =45727 AND actNo = 0;
Update mobskill Set mobname = '深海希爾黛斯(8セル遠距離特殊攻撃)' Where mobid =45727 AND actNo = 1;
Update mobskill Set mobname = '深海伊萊克頓(範囲特殊攻撃)' Where mobid =45732 AND actNo = 0;
Update mobskill Set mobname = '大王烏賊(迴轉漩渦)' Where mobid =45734 AND actNo = 0;
Update mobskill Set mobname = '小惡魔(火炎魔方陣)' Where mobid =45736 AND actNo = 0;
Update mobskill Set mobname = '地之守護者(衝擊之暈)' Where mobid =45739 AND actNo = 0;
Update mobskill Set mobname = '水之守護者(衝擊之暈)' Where mobid =45740 AND actNo = 0;
Update mobskill Set mobname = '火之守護者(衝擊之暈)' Where mobid =45741 AND actNo = 0;
Update mobskill Set mobname = '風之守護者(衝擊之暈)' Where mobid =45742 AND actNo = 0;
Update mobskill Set mobname = '諾納(物理攻撃)' Where mobid =45743 AND actNo = 0;
Update mobskill Set mobname = '小安加斯(火焰噴吐)' Where mobid =45746 AND actNo = 0;
Update mobskill Set mobname = '安加斯(炎)' Where mobid =45747 AND actNo = 0;
Update mobskill Set mobname = '小巴薩斯(龍捲風)' Where mobid =45748 AND actNo = 0;
Update mobskill Set mobname = '小巴薩斯(変身後)(8セル遠距離特殊攻撃)' Where mobid =45749 AND actNo = 0;
Update mobskill Set mobname = '巴薩斯(龍捲風)' Where mobid =45750 AND actNo = 0;
Update mobskill Set mobname = '巴薩斯(変身後)(8セル遠距離特殊攻撃)' Where mobid =45751 AND actNo = 0;
Update mobskill Set mobname = '炎魔(広範囲魔法)' Where mobid =45752 AND actNo = 0;
Update mobskill Set mobname = '炎魔(全範囲魔法)' Where mobid =45752 AND actNo = 1;
Update mobskill Set mobname = '炎魔(衝擊之暈)' Where mobid =45752 AND actNo = 2;
Update mobskill Set mobname = '炎魔(変身後)(広範囲魔法)' Where mobid =45753 AND actNo = 0;
Update mobskill Set mobname = '炎魔(変身後)(全範囲魔法)' Where mobid =45753 AND actNo = 1;
Update mobskill Set mobname = '炎魔(変身後)(衝擊之暈)' Where mobid =45753 AND actNo = 2;
Update mobskill Set mobname = '污濁妖魔法師(燃燒的火球)' Where mobid =45770 AND actNo = 0;
Update mobskill Set mobname = '污濁精靈(極道落雷)' Where mobid =45771 AND actNo = 0;
Update mobskill Set mobname = '污濁妖魔鬥士(召還:污濁妖魔法師)' Where mobid =45772 AND actNo = 0;
Update mobskill Set mobname = '污濁闇精靈王(吸血鬼之吻)' Where mobid =45783 AND actNo = 0;
Update mobskill Set mobname = '污濁闇精靈王(召還:污濁闇之精靈)' Where mobid =45783 AND actNo = 1;
Update mobskill Set mobname = '污濁光精靈王(極道落雷)' Where mobid =45784 AND actNo = 0;
Update mobskill Set mobname = '污濁土精靈王(遠距離魔法)' Where mobid =45785 AND actNo = 0;
Update mobskill Set mobname = '污濁土精靈王(物理攻撃)' Where mobid =45785 AND actNo = 1;
Update mobskill Set mobname = '污濁火精靈王(燃燒的火球)' Where mobid =45786 AND actNo = 0;
Update mobskill Set mobname = '污濁火精靈王(物理攻撃)' Where mobid =45786 AND actNo = 1;
Update mobskill Set mobname = '污濁風精靈王(龍捲風)' Where mobid =45787 AND actNo = 0;
Update mobskill Set mobname = '污濁風精靈王霊(物理攻撃)' Where mobid =45787 AND actNo = 1;
Update mobskill Set mobname = '污濁水精靈王(遠距離魔法)' Where mobid =45788 AND actNo = 0;
Update mobskill Set mobname = '污濁水精靈王(物理攻撃)' Where mobid =45788 AND actNo = 1;
Update mobskill Set mobname = '樹精分身(遠距離特殊攻撃)' Where mobid =45794 AND actNo = 0;
Update mobskill Set mobname = '樹精(遠距離特殊攻撃)' Where mobid =45795 AND actNo = 0;
Update mobskill Set mobname = '樹精(召還:樹精分身)' Where mobid =45795 AND actNo = 1;
Update mobskill Set mobname = '瑪依奴夏門的鑽石高崙(究極光裂術)' Where mobid =45801 AND actNo = 0;
Update mobskill Set mobname = '瑪依奴夏門(極道落雷)' Where mobid =45802 AND actNo = 0;
Update mobskill Set mobname = '瑪依奴夏門(雷霆風暴)' Where mobid =45802 AND actNo = 1;
Update mobskill Set mobname = '希爾黛斯(冰錐)' Where mobid =45812 AND actNo = 0;
Update mobskill Set mobname = '奎斯坦修(冰錐)' Where mobid =45823 AND actNo = 0;
Update mobskill Set mobname = '變形怪首領(冰雪暴)' Where mobid =45828 AND actNo = 0;
Update mobskill Set mobname = '變形怪首領(火風暴)' Where mobid =45828 AND actNo = 1;
Update mobskill Set mobname = '變形怪首領(物理攻撃)' Where mobid =45828 AND actNo = 2;
Update mobskill Set mobname = '巴貝多(燃燒的火球)' Where mobid =45829 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45831 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45831 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45832 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45832 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45833 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45833 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45834 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45834 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =45835 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45839 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45839 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =45840 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45842 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45842 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =45843 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45847 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45847 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(単体魔法)' Where mobid =45847 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =45849 AND actNo = 0;
Update mobskill Set mobname = '闇黑棲林者(範囲魔法)' Where mobid =45850 AND actNo = 0;
Update mobskill Set mobname = '闇黑棲林者(範囲魔法)' Where mobid =45851 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45853 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45853 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(単体魔法)' Where mobid =45853 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45859 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45859 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(単体魔法)' Where mobid =45859 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45860 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45860 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(単体魔法)' Where mobid =45860 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =45861 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =45862 AND actNo = 0;
Update mobskill Set mobname = '法令軍王．蕾雅(冰裂術)' Where mobid =45863 AND actNo = 0;
Update mobskill Set mobname = '法令軍王．蕾雅(強制変身:オーク)' Where mobid =45863 AND actNo = 1;
Update mobskill Set mobname = '法令軍王．蕾雅(高級治癒術)' Where mobid =45863 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45864 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45864 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(単体魔法)' Where mobid =45864 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45865 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45865 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45866 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45866 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =45867 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45869 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(物理攻撃)' Where mobid =45869 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(単体魔法)' Where mobid =45869 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45870 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45870 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(遠距離特殊攻撃)' Where mobid =45871 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(範囲特殊攻撃)' Where mobid =45871 AND actNo = 1;
Update mobskill Set mobname = '異變蜥蜴人(冰錐)' Where mobid =45874 AND actNo = 0;
Update mobskill Set mobname = '巨大守護螞蟻(震裂術)' Where mobid =45952 AND actNo = 0;
Update mobskill Set mobname = '巨大守護螞蟻(物理攻撃)' Where mobid =45952 AND actNo = 1;
Update mobskill Set mobname = '黑暗妖精殘兵(冰錐)' Where mobid =45899 AND actNo = 0;
Update mobskill Set mobname = '黑暗妖精殘兵(冰錐)' Where mobid =45906 AND actNo = 0;
Update mobskill Set mobname = '黑暗精靈使(範囲魔法)' Where mobid =45907 AND actNo = 0;
Update mobskill Set mobname = '黑暗精靈使(召還:闇之精靈)' Where mobid =45907 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的 多眼怪(木乃伊的詛咒)' Where mobid =45926 AND actNo = 0;
Update mobskill Set mobname = '水之精靈(冰箭)' Where mobid =45931 AND actNo = 0;
Update mobskill Set mobname = '水之精靈(召還:水之精靈召喚物)' Where mobid =45931 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的 梅杜莎(木乃伊的詛咒)' Where mobid =45935 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的 希爾黛斯(6セル遠距離特殊攻撃)' Where mobid =45936 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的 希爾黛斯(8セル遠距離特殊攻撃)' Where mobid =45936 AND actNo = 1;
Update mobskill Set mobname = '伊娃 伊萊克頓(範囲特殊攻撃)' Where mobid =45938 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的巫女莎爾(範囲魔法)' Where mobid =45941 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的 水精靈王(冰錐)' Where mobid =45942 AND actNo = 0;
Update mobskill Set mobname = '卡普(地裂術)' Where mobid =45943 AND actNo = 0;
Update mobskill Set mobname = '巨大蜈蚣(特殊範囲攻撃1)' Where mobid =45944 AND actNo = 0;
Update mobskill Set mobname = '巨大蜈蚣(特殊範囲攻撃2)' Where mobid =45944 AND actNo = 1;
Update mobskill Set mobname = '清潔工螞蟻(特殊範囲攻撃3)' Where mobid =45945 AND actNo = 2;
Update mobskill Set mobname = '長老‧琪娜(8セル遠距離特殊攻撃)' Where mobid =45955 AND actNo = 0;
Update mobskill Set mobname = '長老‧琪娜(5セル範囲特殊攻撃)' Where mobid =45955 AND actNo = 1;
Update mobskill Set mobname = '長老‧琪娜(物理攻撃)' Where mobid =45955 AND actNo = 2;
Update mobskill Set mobname = '長老‧巴塔斯(5セル範囲特殊攻撃)' Where mobid =45956 AND actNo = 0;
Update mobskill Set mobname = '長老‧巴塔斯(物理攻撃)' Where mobid =45956 AND actNo = 1;
Update mobskill Set mobname = '長老‧巴塔斯(5セル範囲特殊攻撃)' Where mobid =45957 AND actNo = 0;
Update mobskill Set mobname = '長老‧巴塔斯(7セル範囲特殊攻撃)' Where mobid =45957 AND actNo = 1;
Update mobskill Set mobname = '長老‧巴塔斯(物理攻撃)' Where mobid =45957 AND actNo = 2;
Update mobskill Set mobname = '長老‧安迪斯(5セル範囲特殊攻撃)' Where mobid =45958 AND actNo = 0;
Update mobskill Set mobname = '長老‧安迪斯(物理攻撃)' Where mobid =45958 AND actNo = 1;
Update mobskill Set mobname = '長老‧艾迪爾(8セル遠距離特殊攻撃)' Where mobid =45959 AND actNo = 0;
Update mobskill Set mobname = '長老‧艾迪爾(物理攻撃)' Where mobid =45959 AND actNo = 1;
Update mobskill Set mobname = '長老‧泰瑪斯(8セル遠距離特殊攻撃)' Where mobid =45960 AND actNo = 0;
Update mobskill Set mobname = '長老‧泰瑪斯(ダーク火球召喚)' Where mobid =45960 AND actNo = 1;
Update mobskill Set mobname = '長老‧泰瑪斯(物理攻撃)' Where mobid =45960 AND actNo = 2;
Update mobskill Set mobname = '長老‧拉曼斯(5セル範囲特殊攻撃)' Where mobid =45961 AND actNo = 0;
Update mobskill Set mobname = '長老‧拉曼斯(召喚:黑虎)' Where mobid =45961 AND actNo = 1;
Update mobskill Set mobname = '長老‧拉曼斯(召喚:地獄束縛犬)' Where mobid =45961 AND actNo = 2;
Update mobskill Set mobname = '長老‧拉曼斯(物理攻撃)' Where mobid =45961 AND actNo = 3;
Update mobskill Set mobname = '長老‧巴陸德(8セル遠距離特殊攻撃)' Where mobid =45962 AND actNo = 0;
Update mobskill Set mobname = '長老‧巴陸德(5セル範囲特殊攻撃)' Where mobid =45962 AND actNo = 1;
Update mobskill Set mobname = '長老‧巴陸德(物理攻撃)' Where mobid =45962 AND actNo = 2;
Update mobskill Set mobname = '副神官‧卡山德拉(8セル遠距離特殊攻撃)' Where mobid =45963 AND actNo = 0;
Update mobskill Set mobname = '長老隨從(A)(8セル遠距離特殊攻撃)' Where mobid =45994 AND actNo = 0;
Update mobskill Set mobname = '長老隨從(B)(8セル遠距離特殊攻撃)' Where mobid =45995 AND actNo = 0;
Update mobskill Set mobname = '長老隨從(C)(8セル遠距離特殊攻撃)' Where mobid =45998 AND actNo = 0;
Update mobskill Set mobname = '長老隨從(D)(8セル遠距離特殊攻撃)' Where mobid =45999 AND actNo = 0;
Update mobskill Set mobname = '長老随行員(E)(8セル遠距離特殊攻撃)' Where mobid =46002 AND actNo = 0;
Update mobskill Set mobname = '長老随行員(F)(8セル遠距離特殊攻撃)' Where mobid =46003 AND actNo = 0;
Update mobskill Set mobname = '長老随行員(G)(8セル遠距離特殊攻撃)' Where mobid =46004 AND actNo = 0;
Update mobskill Set mobname = '長老随行員(H)(8セル遠距離特殊攻撃)' Where mobid =46007 AND actNo = 0;
Update mobskill Set mobname = '黑法師(遠距離魔法1)' Where mobid =46018 AND actNo = 0;
Update mobskill Set mobname = '黑法師(遠距離魔法2)' Where mobid =46018 AND actNo = 1;
Update mobskill Set mobname = '貪慾的法師(燃燒的火球)' Where mobid =46021 AND actNo = 0;
Update mobskill Set mobname = '貪慾的法師(火風暴)' Where mobid =46021 AND actNo = 1;
Update mobskill Set mobname = '塔洛斯伯爵(範囲特殊攻撃)' Where mobid =46025 AND actNo = 0;
Update mobskill Set mobname = '塔洛斯伯爵(範囲特殊攻撃)' Where mobid =46025 AND actNo = 1;
Update mobskill Set mobname = '曼孟(範囲特殊攻撃)' Where mobid =46026 AND actNo = 0;
Update mobskill Set mobname = '曼孟(範囲特殊攻撃)' Where mobid =46026 AND actNo = 1;
Update mobskill Set mobname = '腐爛的殭屍法師(冰錐)' Where mobid =46033 AND actNo = 0;
Update mobskill Set mobname = '腐爛的殭屍法師(集體緩速術)' Where mobid =46033 AND actNo = 1;
Update mobskill Set mobname = '腐爛的殭屍將軍(地裂術)' Where mobid =46034 AND actNo = 0;
Update mobskill Set mobname = '腐爛的殭屍王(範囲特殊攻撃)' Where mobid =46035 AND actNo = 0;
Update mobskill Set mobname = '腐爛的殭屍王(遠距離特殊攻撃)' Where mobid =46036 AND actNo = 0;
Update mobskill Set mobname = '腐爛的骷髏騎士(範囲特殊攻撃)' Where mobid =46036 AND actNo = 1;
Update mobskill Set mobname = '瑪雅(燃燒的火球)' Where mobid =46037 AND actNo = 0;
Update mobskill Set mobname = '瑪雅(範囲特殊攻撃)' Where mobid =46037 AND actNo = 1;
Update mobskill Set mobname = '瑪雅(範囲特殊攻撃)' Where mobid =46037 AND actNo = 2;
Update mobskill Set mobname = '瑪雅(召還:瑪雅的召喚物)' Where mobid =46037 AND actNo = 3;
Update mobskill Set mobname = '瑪雅(召還:瑪雅的召喚物)' Where mobid =46037 AND actNo = 4;
Update mobskill Set mobname = '瑪雅(召還:瑪雅的召喚物)' Where mobid =46037 AND actNo = 5;
Update mobskill Set mobname = '船舶的惡靈(召還:船舶的惡靈召喚物)' Where mobid =46053 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(衝擊之暈)' Where mobid =46062 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精鬥士(6セル遠距離特殊攻撃)' Where mobid =46062 AND actNo = 1;
Update mobskill Set mobname = '受詛咒的黑暗妖精法師(10セル遠距離特殊攻撃)' Where mobid =46063 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(6セル遠距離特殊攻撃)' Where mobid =46064 AND actNo = 0;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(4セル範囲攻撃)' Where mobid =46064 AND actNo = 2;
Update mobskill Set mobname = '受詛咒的黑暗妖精騎士(7セル範囲特殊攻撃)' Where mobid =46064 AND actNo = 1;
Update mobskill Set mobname = '食腐獸(遠距離特殊攻擊)' Where mobid =46065 AND actNo = 0;
Update mobskill Set mobname = '特提斯(5セル範囲特殊攻撃)' Where mobid =46066 AND actNo = 0;
Update mobskill Set mobname = '翼龍(龍捲風)' Where mobid =46067 AND actNo = 0;
Update mobskill Set mobname = '無法被選擇的人(物理攻撃)' Where mobid =46069 AND actNo = 0;
Update mobskill Set mobname = '無法被選擇的人(龍捲風)' Where mobid =46070 AND actNo = 0;
Update mobskill Set mobname = '無法被選擇的人(8セル遠距離特殊攻撃)' Where mobid =46071 AND actNo = 0;
Update mobskill Set mobname = '無法被選擇的人(龍捲風)' Where mobid =46072 AND actNo = 0;
Update mobskill Set mobname = '無法被選擇的人(8セル遠距離特殊攻撃)' Where mobid =46073 AND actNo = 0;
Update mobskill Set mobname = '無法被選擇的人(炎)' Where mobid =46078 AND actNo = 0;
Update mobskill Set mobname = '無法被選擇的人(炎)' Where mobid =46079 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 1(レッサーデーモン)(火炎魔方陣)' Where mobid =46082 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 1(レッサーデーモン)(物理攻撃)' Where mobid =46082 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 2(レッサーデーモン)(火炎魔方陣)' Where mobid =46083 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 2(レッサーデーモン)(物理攻撃)' Where mobid =46083 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 3(レッサーデーモン)(火炎魔方陣)' Where mobid =46084 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 3(レッサーデーモン)(物理攻撃)' Where mobid =46084 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 4(レッサーデーモン)(火炎魔方陣)' Where mobid =46085 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 4(レッサーデーモン)(物理攻撃)' Where mobid =46085 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 5(レッサーデーモン)(火炎魔方陣)' Where mobid =46086 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 5(レッサーデーモン)(物理攻撃)' Where mobid =46086 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 6(レッサーデーモン)(火炎魔方陣)' Where mobid =46087 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 6(レッサーデーモン)(物理攻撃)' Where mobid =46087 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 7(レッサーデーモン)(火炎魔方陣)' Where mobid =46088 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 7(レッサーデーモン)(物理攻撃)' Where mobid =46088 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 8(レッサーデーモン)(火炎魔方陣)' Where mobid =46089 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 8(レッサーデーモン)(物理攻撃)' Where mobid =46089 AND actNo = 1;
Update mobskill Set mobname = '巡察兵 9(レッサーデーモン)(火炎魔方陣)' Where mobid =46090 AND actNo = 0;
Update mobskill Set mobname = '巡察兵 9(レッサーデーモン)(物理攻撃)' Where mobid =46090 AND actNo = 1;
Update mobskill Set mobname = '歩哨兵(レッサーデーモン)(火炎魔方陣)' Where mobid =46091 AND actNo = 0;
Update mobskill Set mobname = '歩哨兵(レッサーデーモン)(物理攻撃)' Where mobid =46091 AND actNo = 1;
Update mobskill Set mobname = '不被選擇的人(単体魔法)' Where mobid =46093 AND actNo = 0;
Update mobskill Set mobname = '不被選擇的人(単体魔法)' Where mobid =46094 AND actNo = 0;
Update mobskill Set mobname = '不被選擇的人(単体魔法)' Where mobid =46095 AND actNo = 0;
Update mobskill Set mobname = '不被選擇的人(玩家召回)' Where mobid =46096 AND actNo = 0;
Update mobskill Set mobname = '不被選擇的人(単体魔法)' Where mobid =46096 AND actNo = 1;
Update mobskill Set mobname = '底比斯 凱比斯(物理攻撃)' Where mobid =46111 AND actNo = 0;
Update mobskill Set mobname = '底比斯 凱比斯(物理攻撃)' Where mobid =46112 AND actNo = 0;
Update mobskill Set mobname = '底比斯 尖碑石奴(龍捲風)' Where mobid =46113 AND actNo = 0;
Update mobskill Set mobname = '底比斯 尖碑石奴(物理攻撃)' Where mobid =46113 AND actNo = 1;
Update mobskill Set mobname = '底比斯 尖碑石奴(龍捲風)' Where mobid =46114 AND actNo = 0;
Update mobskill Set mobname = '底比斯 尖碑石奴(物理攻撃)' Where mobid =46114 AND actNo = 1;
Update mobskill Set mobname = '底比斯 斯芬克斯(物理攻撃)' Where mobid =46115 AND actNo = 0;
Update mobskill Set mobname = '底比斯 斯芬克斯(範囲魔法)' Where mobid =46115 AND actNo = 1;
Update mobskill Set mobname = '底比斯 斯芬克斯(物理攻撃)' Where mobid =46116 AND actNo = 0;
Update mobskill Set mobname =  '底比斯 斯芬克斯(範囲魔法)' Where mobid =46116 AND actNo = 1;
Update mobskill Set mobname =  '底比斯 尼荷斯(6セル遠距離特殊攻撃)' Where mobid =46117 AND actNo = 0;
Update mobskill Set mobname = '底比斯 尼荷斯(6セル遠距離特殊攻撃)' Where mobid =46118 AND actNo = 0;
Update mobskill Set mobname = '底比斯 阿努斯(物理攻撃)' Where mobid =46119 AND actNo = 0;
Update mobskill Set mobname = '底比斯 阿努斯(物理攻撃)' Where mobid =46120 AND actNo = 0;
Update mobskill Set mobname = '底比斯 巴斯(雷霆風暴)' Where mobid =46121 AND actNo = 0;
Update mobskill Set mobname = '底比斯 巴斯(物理攻撃)' Where mobid =46121 AND actNo = 1;
Update mobskill Set mobname = '底比斯 阿斯(雷霆風暴)' Where mobid =46122 AND actNo = 0;
Update mobskill Set mobname = '底比斯 阿斯(物理攻撃)' Where mobid =46122 AND actNo = 1;
Update mobskill Set mobname = '底比斯 賀洛斯(6セル遠距離特殊攻撃)' Where mobid =46123 AND actNo = 0;
Update mobskill Set mobname = '底比斯 賀洛斯(4セル範囲特殊攻撃)' Where mobid =46123 AND actNo = 1;
Update mobskill Set mobname = '底比斯 賀洛斯(物理攻撃)' Where mobid =46123 AND actNo = 2;
Update mobskill Set mobname = '底比斯 賀洛斯ス(召還:底比斯 尼荷斯)' Where mobid =46123 AND actNo = 3;
Update mobskill Set mobname = '底比斯 阿努比斯(6セル遠距離特殊攻撃)' Where mobid =46124 AND actNo = 0;
Update mobskill Set mobname = '底比斯 阿努比斯(4セル範囲特殊攻撃)' Where mobid =46124 AND actNo = 1;
Update mobskill Set mobname = '底比斯 阿努比斯(物理攻撃)' Where mobid =46124 AND actNo = 2;
Update mobskill Set mobname = '底比斯 阿努比斯(召還:底比斯 阿努斯)' Where mobid =46124 AND actNo = 3;
Update mobskill Set mobname = '底比斯 阿努比斯(召還:底比斯 阿斯)' Where mobid =46124 AND actNo = 4;
Update mobskill Set mobname = '法利昂的信奉者(光箭)' Where mobid =81081 AND actNo = 0;
Update mobskill Set mobname = '火焰之影(変身)' Where mobid =81082 AND actNo = 0;
Update mobskill Set mobname = '火焰之影(強制変身:ゾンビ)' Where mobid =81082 AND actNo = 1;
Update mobskill Set mobname = '火焰之影(遠距離魔法)' Where mobid =81082 AND actNo = 2;
Update mobskill Set mobname = '火焰之影(範囲魔法)' Where mobid =81082 AND actNo = 3;
Update mobskill Set mobname = '變形怪首領(冰裂術)' Where mobid =81103 AND actNo = 0;
Update mobskill Set mobname = '變形怪首領(烈炎術)' Where mobid =81103 AND actNo = 1;
Update mobskill Set mobname = '變形怪首領(物理攻撃)' Where mobid =81103 AND actNo = 2;
Update mobskill Set mobname = '吉爾塔斯(ブルーバリア)' Where mobid =81163 AND actNo = 0;
Update mobskill Set mobname = '吉爾塔斯(砂嵐)' Where mobid =81163 AND actNo = 1;
Update mobskill Set mobname = '吉爾塔斯(アイスブレス)' Where mobid =81163 AND actNo = 2;
Update mobskill Set mobname = '吉爾塔斯(毒霧)' Where mobid =81163 AND actNo = 3;
Update mobskill Set mobname = '吉爾塔斯(震裂術)' Where mobid =81163 AND actNo = 4;
Update mobskill Set mobname = '吉爾塔斯(物理攻撃1)' Where mobid =81163 AND actNo = 5;
Update mobskill Set mobname = '吉爾塔斯(物理攻撃2)' Where mobid =81163 AND actNo = 6;
Update mobskill Set mobname = '黑長者(龍捲風)' Where mobid =81176 AND actNo = 0;
Update mobskill Set mobname = '黑長者(遠距離魔法)' Where mobid =81176 AND actNo = 1;
Update mobskill Set mobname = '高等蜥蜴人(6セル遠距離特殊攻撃)' Where mobid =81224 AND actNo = 0;
Update mobskill Set mobname = '巨大守護螞蟻(物理攻撃)' Where mobid =81231 AND actNo = 0;
Update mobskill Set mobname = '食腐獸(8セル遠距離特殊攻撃)' Where mobid =81236 AND actNo = 0;
Update mobskill Set mobname = '地獄束縛犬(炎)' Where mobid =81237 AND actNo = 0;
Update mobskill Set mobname = '變形怪首領(冰裂術)' Where mobid =81238 AND actNo = 0;
Update mobskill Set mobname = '變形怪首領(烈炎術)' Where mobid =81238 AND actNo = 1;
Update mobskill Set mobname = '變形怪首領(物理攻撃)' Where mobid =81238 AND actNo = 2;
Update mobskill Set mobname = '巨大牛人(物理攻撃)' Where mobid =81239 AND actNo = 1;