/*
 * sanday0603提供
 */
Update weapon Set name = '歐西斯匕首' Where item_id = '1';
Update weapon Set name = '骰子匕首' Where item_id = '2';
Update weapon Set name = '短劍的劍身' Where item_id = '3';
Update weapon Set name = '匕首' Where item_id = '4';
Update weapon Set name = '精靈匕首' Where item_id = '5';
Update weapon Set name = '拉斯塔巴德短劍' Where item_id = '6';
Update weapon Set name = '象牙塔短劍' Where item_id = '7';
Update weapon Set name = '米索莉短劍' Where item_id = '8';
Update weapon Set name = '奧里哈魯根短劍' Where item_id = '9';
Update weapon Set name = '小武士刀' Where item_id = '10';
Update weapon Set name = '水晶短劍' Where item_id = '11';
Update weapon Set name = '風刃短劍' Where item_id = '12';
Update weapon Set name = '死亡之指' Where item_id = '13';
Update weapon Set name = '混沌之刺' Where item_id = '14';
Update weapon Set name = '失去魔力的克特之劍' Where item_id = '15';
Update weapon Set name = '復仇之劍' Where item_id = '16';
Update weapon Set name = '受封印 被遺忘的巨劍' Where item_id = '17';
Update weapon Set name = '受封印 被遺忘的劍' Where item_id = '18';
Update weapon Set name = '長劍的劍身' Where item_id = '19';
Update weapon Set name = '奧里哈魯根的劍身' Where item_id = '20';
Update weapon Set name = '歐西斯短劍' Where item_id = '21';
Update weapon Set name = '鎖子甲破壞者' Where item_id = '22';
Update weapon Set name = '闊劍' Where item_id = '23';
Update weapon Set name = '短劍' Where item_id = '24';
Update weapon Set name = '銀劍' Where item_id = '25';
Update weapon Set name = '小侏儒短劍' Where item_id = '26';
Update weapon Set name = '彎刀' Where item_id = '27';
Update weapon Set name = '精靈短劍' Where item_id = '28';
Update weapon Set name = '銀長劍' Where item_id = '29';
Update weapon Set name = '紅騎士之劍' Where item_id = '30';
Update weapon Set name = '長劍' Where item_id = '31';
Update weapon Set name = '侵略者之劍' Where item_id = '32';
Update weapon Set name = '榮耀之劍' Where item_id = '33';
Update weapon Set name = '血紅慾望短劍' Where item_id = '34';
Update weapon Set name = '象牙塔單手劍' Where item_id = '35';
Update weapon Set name = '幻象之劍' Where item_id = '36';
Update weapon Set name = '大馬士革刀' Where item_id = '37';
Update weapon Set name = '拉斯塔巴德長劍' Where item_id = '38';
Update weapon Set name = '短刀' Where item_id = '39';
Update weapon Set name = '血色巨劍' Where item_id = '40';
Update weapon Set name = '武士刀' Where item_id = '41';
Update weapon Set name = '細劍' Where item_id = '42';
Update weapon Set name = '海賊彎刀' Where item_id = '43';
Update weapon Set name = '古代黑暗妖精之劍' Where item_id = '44';
Update weapon Set name = '波曲王之劍' Where item_id = '45';
Update weapon Set name = '生命之劍' Where item_id = '46';
Update weapon Set name = '沉默之劍' Where item_id = '47';
Update weapon Set name = '象牙塔雙手劍' Where item_id = '48';
Update weapon Set name = '武官之刃' Where item_id = '49';
Update weapon Set name = '赤焰之劍' Where item_id = '50';
Update weapon Set name = '黃金權杖' Where item_id = '51';
Update weapon Set name = '雙手劍' Where item_id = '52';
Update weapon Set name = '蜥蜴王勇士之劍' Where item_id = '53';
Update weapon Set name = '克特之劍' Where item_id = '54';
Update weapon Set name = '黑暗之劍' Where item_id = '55';
Update weapon Set name = '黑燄之劍' Where item_id = '56';
Update weapon Set name = '瑟魯基之劍' Where item_id = '57';
Update weapon Set name = '死亡騎士的烈炎之劍' Where item_id = '58';
Update weapon Set name = '騎士范德之劍' Where item_id = '59';
Update weapon Set name = '末日刀' Where item_id = '60';
Update weapon Set name = '真．冥皇執行劍' Where item_id = '61';
Update weapon Set name = '武官雙手劍' Where item_id = '62';
Update weapon Set name = '惡魔之劍' Where item_id = '63';
Update weapon Set name = '巨劍' Where item_id = '64';
Update weapon Set name = '天空之劍' Where item_id = '65';
Update weapon Set name = '屠龍劍' Where item_id = '66';
Update weapon Set name = '古老的巨劍' Where item_id = '67';
Update weapon Set name = '古老的劍' Where item_id = '68';
Update weapon Set name = '青銅 雙刀' Where item_id = '69';
Update weapon Set name = '尖刺雙刀' Where item_id = '70';
Update weapon Set name = '鋼鐵 雙刀' Where item_id = '71';
Update weapon Set name = '暗影 雙刀' Where item_id = '72';
Update weapon Set name = '象牙塔雙刀' Where item_id = '73';
Update weapon Set name = '銀光 雙刀' Where item_id = '74';
Update weapon Set name = '黑暗 雙刀' Where item_id = '75';
Update weapon Set name = '倫得雙刀' Where item_id = '76';
Update weapon Set name = '短 雙刀' Where item_id = '77';
Update weapon Set name = '暗殺軍王之痕' Where item_id = '78';
Update weapon Set name = '深淵雙刀' Where item_id = '79';
Update weapon Set name = '大馬士革 雙刀' Where item_id = '80';
Update weapon Set name = '幽暗 雙刀' Where item_id = '81';
Update weapon Set name = '拉斯塔巴德雙刀' Where item_id = '82';
Update weapon Set name = '狄亞得雙刀' Where item_id = '83';
Update weapon Set name = '暗黑雙刀' Where item_id = '84';
Update weapon Set name = '惡魔雙刀' Where item_id = '85';
Update weapon Set name = '紅影雙刀' Where item_id = '86';
Update weapon Set name = '不為人知的矛' Where item_id = '87';
Update weapon Set name = '潘的角' Where item_id = '88';
Update weapon Set name = '覆上米索莉的角' Where item_id = '89';
Update weapon Set name = '巴迪須' Where item_id = '90';
Update weapon Set name = '歐西斯之矛' Where item_id = '91';
Update weapon Set name = '柴刀' Where item_id = '92';
Update weapon Set name = '三叉戟' Where item_id = '93';
Update weapon Set name = '帕提森' Where item_id = '94';
Update weapon Set name = '矛' Where item_id = '95';
Update weapon Set name = '矛' Where item_id = '96';
Update weapon Set name = '吉薩' Where item_id = '97';
Update weapon Set name = '闊矛' Where item_id = '98';
Update weapon Set name = '精靈之矛' Where item_id = '99';
Update weapon Set name = '覆上奧里哈魯根的角' Where item_id = '100';
Update weapon Set name = '拉斯塔巴德矛' Where item_id = '101';
Update weapon Set name = '露西錘' Where item_id = '102';
Update weapon Set name = '戟' Where item_id = '103';
Update weapon Set name = '法丘' Where item_id = '104';
Update weapon Set name = '象牙塔長矛' Where item_id = '105';
Update weapon Set name = '貝卡合金' Where item_id = '106';
Update weapon Set name = '深紅長矛' Where item_id = '107';
Update weapon Set name = '失去魔力的惡魔鐮刀' Where item_id = '108';
Update weapon Set name = '失去魔力的巴風特魔杖' Where item_id = '109';
Update weapon Set name = '失去魔力的巴列斯魔杖' Where item_id = '110';
Update weapon Set name = '失去魔力的冰之女王魔杖' Where item_id = '111';
Update weapon Set name = '精靈短劍' Where item_id = '112';
Update weapon Set name = '敏捷精靈短劍' Where item_id = '113';
Update weapon Set name = '威嚴權杖' Where item_id = '114';
Update weapon Set name = '水晶魔杖' Where item_id = '115';
Update weapon Set name = '黑法師之杖' Where item_id = '116';
Update weapon Set name = '蕾雅魔杖' Where item_id = '117';
Update weapon Set name = '漆黑水晶球' Where item_id = '118';
Update weapon Set name = '惡魔鐮刀' Where item_id = '119';
Update weapon Set name = '象牙塔魔杖' Where item_id = '120';
Update weapon Set name = '冰之女王魔杖' Where item_id = '121';
Update weapon Set name = '拉斯塔巴德魔杖' Where item_id = '122';
Update weapon Set name = '巴列斯魔杖' Where item_id = '123';
Update weapon Set name = '巴風特魔杖' Where item_id = '124';
Update weapon Set name = '巫術魔法杖' Where item_id = '125';
Update weapon Set name = '瑪那魔杖' Where item_id = '126';
Update weapon Set name = '鋼鐵瑪那魔杖' Where item_id = '127';
Update weapon Set name = '橡木魔法杖' Where item_id = '128';
Update weapon Set name = '美基魔法杖' Where item_id = '129';
Update weapon Set name = '紅水晶魔杖' Where item_id = '130';
Update weapon Set name = '力量魔法杖' Where item_id = '131';
Update weapon Set name = '神官魔杖' Where item_id = '132';
Update weapon Set name = '古代人的智慧' Where item_id = '133';
Update weapon Set name = '聖晶魔杖' Where item_id = '134';
Update weapon Set name = '不為人知的斧' Where item_id = '135';
Update weapon Set name = '斧' Where item_id = '136';
Update weapon Set name = '亞連' Where item_id = '137';
Update weapon Set name = '木棒' Where item_id = '138';
Update weapon Set name = '弗萊爾' Where item_id = '139';
Update weapon Set name = '釘錘' Where item_id = '140';
Update weapon Set name = '戰錘' Where item_id = '141';
Update weapon Set name = '銀斧' Where item_id = '142';
Update weapon Set name = '戰斧' Where item_id = '143';
Update weapon Set name = '侏儒鐵斧' Where item_id = '144';
Update weapon Set name = '狂戰士斧' Where item_id = '145';
Update weapon Set name = '流星錘' Where item_id = '146';
Update weapon Set name = '象牙塔斧頭' Where item_id = '147';
Update weapon Set name = '巨斧' Where item_id = '148';
Update weapon Set name = '牛人斧頭' Where item_id = '149';
Update weapon Set name = '天父之怒' Where item_id = '150';
Update weapon Set name = '惡魔斧頭' Where item_id = '151';
Update weapon Set name = '青銅 鋼爪' Where item_id = '152';
Update weapon Set name = '鋼鐵 鋼爪' Where item_id = '153';
Update weapon Set name = '暗影 鋼爪' Where item_id = '154';
Update weapon Set name = '魔獸軍王之爪' Where item_id = '155';
Update weapon Set name = '象牙塔鋼爪' Where item_id = '156';
Update weapon Set name = '銀光 鋼爪' Where item_id = '157';
Update weapon Set name = '黑暗 鋼爪' Where item_id = '158';
Update weapon Set name = '短 鋼爪' Where item_id = '159';
Update weapon Set name = '獸王鋼爪' Where item_id = '160';
Update weapon Set name = '大馬士革 鋼爪' Where item_id = '161';
Update weapon Set name = '幽暗 鋼爪' Where item_id = '162';
Update weapon Set name = '巴蘭卡鋼爪' Where item_id = '163';
Update weapon Set name = '暗黑鋼爪' Where item_id = '164';
Update weapon Set name = '惡魔鋼爪' Where item_id = '165';
Update weapon Set name = '恨之鋼爪' Where item_id = '166';
Update weapon Set name = '受封印 被遺忘的弩槍' Where item_id = '167';
Update weapon Set name = '黑暗十字弓' Where item_id = '168';
Update weapon Set name = '獵人之弓' Where item_id = '169';
Update weapon Set name = '精靈弓' Where item_id = '170';
Update weapon Set name = '歐西斯弓' Where item_id = '171';
Update weapon Set name = '弓' Where item_id = '172';
Update weapon Set name = '短弓' Where item_id = '173';
Update weapon Set name = '象牙塔石弓' Where item_id = '174';
Update weapon Set name = '象牙塔弓' Where item_id = '175';
Update weapon Set name = '拉斯塔巴德弓' Where item_id = '176';
Update weapon Set name = '幽暗十字弓' Where item_id = '177';
Update weapon Set name = '寂靜十字弓' Where item_id = '178';
Update weapon Set name = '古代妖精弩槍' Where item_id = '179';
Update weapon Set name = '十字弓' Where item_id = '180';
Update weapon Set name = '尤米弓' Where item_id = '181';
Update weapon Set name = '古老的弩槍' Where item_id = '182';
Update weapon Set name = '幻象之弓' Where item_id = '183';
Update weapon Set name = '赤焰之弓' Where item_id = '184';
Update weapon Set name = '惡魔十字弓' Where item_id = '185';
Update weapon Set name = '狄亞得十字弓' Where item_id = '186';
Update weapon Set name = '拉斯塔巴德十字弓' Where item_id = '187';
Update weapon Set name = '拉斯塔巴德重十字弓' Where item_id = '188';
Update weapon Set name = '暗黑十字弓' Where item_id = '189';
Update weapon Set name = '沙哈之弓' Where item_id = '190';
Update weapon Set name = '弒神者之弓' Where item_id = '191';
Update weapon Set name = '水精靈之弓' Where item_id = '192';
Update weapon Set name = '鐵手甲' Where item_id = '193';
Update weapon Set name = '真鐵手甲' Where item_id = '194';
Update weapon Set name = '受詛咒的真．冥皇執行劍' Where item_id = '195';
Update weapon Set name = '炎魔的雙手劍 Lv.1' Where item_id = '196';
Update weapon Set name = '炎魔的雙手劍 Lv.2' Where item_id = '197';
Update weapon Set name = '炎魔的雙手劍 Lv.3' Where item_id = '198';
Update weapon Set name = '炎魔的雙手劍 Lv.4' Where item_id = '199';
Update weapon Set name = '炎魔的雙手劍 Lv.5' Where item_id = '200';
Update weapon Set name = '炎魔的雙手劍 Lv.6' Where item_id = '201';
Update weapon Set name = '炎魔的雙手劍 Lv.7' Where item_id = '202';
Update weapon Set name = '炎魔的雙手劍 Lv.8' Where item_id = '203';
Update weapon Set name = '深紅之弩' Where item_id = '204';
Update weapon Set name = '熾炎天使弓' Where item_id = '205';
Update weapon Set name = '黑暗精靈之劍' Where item_id = '206';
Update weapon Set name = '煉獄鋼爪' Where item_id = '207';
Update weapon Set name = '魔法精靈短劍' Where item_id = '208';
Update weapon Set name = '體質精靈短劍' Where item_id = '209';
Update weapon Set name = '守護者之矛' Where item_id = '210';
Update weapon Set name = '獨角獸之角' Where item_id = '211';
Update weapon Set name = '海神三叉戟' Where item_id = '212';
Update weapon Set name = '吉爾塔斯魔杖' Where item_id = '213';
Update weapon Set name = 'ID．妖精弓' Where item_id = '214';
Update weapon Set name = '敏捷精靈弓' Where item_id = '215';
Update weapon Set name = '妖精之弓' Where item_id = '216';
Update weapon Set name = '吉爾塔斯之劍' Where item_id = '217';
Update weapon Set name = '安加斯的釘錘' Where item_id = '218';
Update weapon Set name = '馬普勒的懲罰' Where item_id = '219';
Update weapon Set name = '法師之杖' Where item_id = '220';
Update weapon Set name = '神秘魔杖' Where item_id = '223';
Update weapon Set name = '象牙塔魔杖' Where item_id = '224';
Update weapon Set name = '王族之劍' Where item_id = '225';
Update weapon Set name = '騎士之劍' Where item_id = '226';
Update weapon Set name = '聖戰士匕首' Where item_id = '228';
Update weapon Set name = '蒼天短劍' Where item_id = '231';
Update weapon Set name = '蒼天之劍' Where item_id = '232';
Update weapon Set name = '蒼天巨劍' Where item_id = '233';
Update weapon Set name = '蒼天之矛' Where item_id = '234';
Update weapon Set name = '蒼天之斧' Where item_id = '235';
Update weapon Set name = '蒼天雙刀' Where item_id = '236';
Update weapon Set name = '蒼天鋼爪' Where item_id = '237';
Update weapon Set name = '蒼天魔杖' Where item_id = '238';
Update weapon Set name = '蒼天之弓' Where item_id = '239';
Update weapon Set name = '蒼天鐵手甲' Where item_id = '240';
Update weapon Set name = '歷戰之劍' Where item_id = '241';
Update weapon Set name = '歷戰十字弓' Where item_id = '242';
Update weapon Set name = '歷戰魔杖' Where item_id = '243';
Update weapon Set name = '歷戰鋼爪' Where item_id = '244';
Update weapon Set name = '精靈叮叮鎚' Where item_id = '245';
Update weapon Set name = '試煉之劍' Where item_id = '246';
Update weapon Set name = '試煉之劍' Where item_id = '247';
Update weapon Set name = '試煉之劍' Where item_id = '248';
Update weapon Set name = '試煉之劍' Where item_id = '249';
Update weapon Set name = 'イリュージョン ダガー' Where item_id = '250';
Update weapon Set name = 'イリュージョン ツヴァイハンダー' Where item_id = '251';
Update weapon Set name = 'イリュージョン スピアー' Where item_id = '252';
Update weapon Set name = 'イリュージョン アックス' Where item_id = '253';
Update weapon Set name = 'イリュージョン デュアルブレード' Where item_id = '254';
Update weapon Set name = 'イリュージョン スタッフ' Where item_id = '255';
Update weapon Set name = '萬聖節南瓜長劍(韓)' Where item_id = '256';
Update weapon Set name = '萬聖節南瓜長劍(日)' Where item_id = '257';
Update weapon Set name = '終極萬聖節南瓜長劍' Where item_id = '258';
Update weapon Set name = '魔力短劍' Where item_id = '259';
Update weapon Set name = '狂風之斧' Where item_id = '260';
Update weapon Set name = '大法師魔仗' Where item_id = '261';
Update weapon Set name = '毀滅巨劍' Where item_id = '262';
Update weapon Set name = '酷寒之矛' Where item_id = '263';
Update weapon Set name = '雷雨之劍' Where item_id = '264';
Update weapon Set name = '底比斯歐西里斯雙刀' Where item_id = '265';
Update weapon Set name = '底比斯歐西里斯雙手劍' Where item_id = '266';
Update weapon Set name = '底比斯歐西里斯弓' Where item_id = '267';
Update weapon Set name = '底比斯歐西里斯魔杖' Where item_id = '268';
Update weapon Set name = '幻術士魔杖' Where item_id = '269';
Update weapon Set name = '藍寶石奇古獸' Where item_id = '270';
Update weapon Set name = '黑曜石奇古獸' Where item_id = '271';
Update weapon Set name = '消滅者鎖鏈劍' Where item_id = '272';
Update weapon Set name = '破滅者鎖鏈劍' Where item_id = '273';
Update weapon Set name = '反王肯恩的權杖' Where item_id = '274';
Update weapon Set name = '龍騎士雙手劍' Where item_id = '275';
Update weapon Set name = '匕首' Where item_id = '100004';
Update weapon Set name = '精靈匕首' Where item_id = '100005';
Update weapon Set name = '米索莉短劍' Where item_id = '100008';
Update weapon Set name = '奧里哈魯根短劍' Where item_id = '100009';
Update weapon Set name = '銀劍' Where item_id = '100025';
Update weapon Set name = '彎刀' Where item_id = '100027';
Update weapon Set name = '精靈短劍' Where item_id = '100028';
Update weapon Set name = '銀長劍' Where item_id = '100029';
Update weapon Set name = '大馬士革刀' Where item_id = '100037';
Update weapon Set name = '武士刀' Where item_id = '100041';
Update weapon Set name = '細劍' Where item_id = '100042';
Update weapon Set name = '武官之刃' Where item_id = '100049';
Update weapon Set name = '雙手劍' Where item_id = '100052';
Update weapon Set name = '瑟魯基之劍' Where item_id = '100057';
Update weapon Set name = '武官雙手劍' Where item_id = '100062';
Update weapon Set name = '巨劍' Where item_id = '100064';
Update weapon Set name = '銀光 雙刀' Where item_id = '100074';
Update weapon Set name = '暗黑雙刀' Where item_id = '100084';
Update weapon Set name = '矛' Where item_id = '100095';
Update weapon Set name = '闊矛' Where item_id = '100098';
Update weapon Set name = '精靈之矛' Where item_id = '100099';
Update weapon Set name = '露西錘' Where item_id = '100102';
Update weapon Set name = '戟' Where item_id = '100103';
Update weapon Set name = '深紅長矛' Where item_id = '100107';
Update weapon Set name = '威嚴權杖' Where item_id = '100114';
Update weapon Set name = '神官魔杖' Where item_id = '100132';
Update weapon Set name = '戰斧' Where item_id = '100143';
Update weapon Set name = '流星錘' Where item_id = '100146';
Update weapon Set name = '惡魔斧頭' Where item_id = '100151';
Update weapon Set name = '銀光 鋼爪' Where item_id = '100157';
Update weapon Set name = '暗黑鋼爪' Where item_id = '100164';
Update weapon Set name = '獵人之弓' Where item_id = '100169';
Update weapon Set name = '精靈弓' Where item_id = '100170';
Update weapon Set name = '弓' Where item_id = '100172';
Update weapon Set name = '十字弓' Where item_id = '100180';
Update weapon Set name = '尤米弓' Where item_id = '100181';
Update weapon Set name = '暗黑十字弓' Where item_id = '100189';
Update weapon Set name = '深紅之弩' Where item_id = '100204';
Update weapon Set name = '煉獄鋼爪' Where item_id = '100207';
Update weapon Set name = '海神三叉戟' Where item_id = '100212';
Update weapon Set name = '歐西斯匕首' Where item_id = '200001';
Update weapon Set name = '骰子匕首' Where item_id = '200002';
Update weapon Set name = '彎刀' Where item_id = '200027';
Update weapon Set name = '侵略者之劍' Where item_id = '200032';
Update weapon Set name = '武士刀' Where item_id = '200041';
Update weapon Set name = '雙手劍' Where item_id = '200052';
Update weapon Set name = '歐西斯弓' Where item_id = '200171';

/*20090525 修正unidentified_name_id名稱*/
Update weapon Set unidentified_name_id = '$2454 $2450' Where item_id = '157'; /* 銀光鋼爪 */
Update weapon Set unidentified_name_id = '$2453 $2450' Where item_id = '162'; /* 幽暗鋼爪'  */
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.1' Where item_id = '196';
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.2' Where item_id = '197';
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.3' Where item_id = '198';
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.4' Where item_id = '199';
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.5' Where item_id = '200';
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.6' Where item_id = '201';
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.7' Where item_id = '202';
Update weapon Set identified_name_id = '炎魔的雙手劍 Lv.8' Where item_id = '203';
Update weapon Set unidentified_name_id = '終極$5254' Where item_id = '258'; /* 終極萬聖節南瓜長劍 */
Update weapon Set unidentified_name_id = '$2454 $2450' Where item_id = '100157'; /* 銀光鋼爪'  */