/*
 * 中文化 weapon 資料表
 * By Impreza8837
 */
UPDATE weapon SET name = "歐西斯匕首", unidentified_name_id = "$13", identified_name_id = "$13" WHERE item_id = "1";
UPDATE weapon SET name = "骰子匕首", unidentified_name_id = "$416", identified_name_id = "$416" WHERE item_id = "2";
UPDATE weapon SET name = "短劍的劍身", unidentified_name_id = "$785", identified_name_id = "$785" WHERE item_id = "3";
UPDATE weapon SET name = "匕首", unidentified_name_id = "$70", identified_name_id = "$70" WHERE item_id = "4";
UPDATE weapon SET name = "精靈匕首", unidentified_name_id = "$12", identified_name_id = "$12" WHERE item_id = "5";
UPDATE weapon SET name = "拉斯塔巴德短劍", unidentified_name_id = "$2905", identified_name_id = "$2905" WHERE item_id = "6";
UPDATE weapon SET name = "象牙塔短劍", unidentified_name_id = "$3288", identified_name_id = "$3288" WHERE item_id = "7";
UPDATE weapon SET name = "米索莉短劍", unidentified_name_id = "$3248", identified_name_id = "$3248" WHERE item_id = "8";
UPDATE weapon SET name = "奧里哈魯根短劍", unidentified_name_id = "$3247", identified_name_id = "$3247" WHERE item_id = "9";
UPDATE weapon SET name = "小武士刀", unidentified_name_id = "$2920", identified_name_id = "$2920" WHERE item_id = "10";
UPDATE weapon SET name = "水晶短劍", unidentified_name_id = "$3867", identified_name_id = "$3867" WHERE item_id = "11";
UPDATE weapon SET name = "風刃短劍", unidentified_name_id = "$3835", identified_name_id = "$3835" WHERE item_id = "12";
UPDATE weapon SET name = "死亡之指", unidentified_name_id = "$2648", identified_name_id = "$2648" WHERE item_id = "13";
UPDATE weapon SET name = "混沌之刺", unidentified_name_id = "$3737", identified_name_id = "$3737" WHERE item_id = "14";
UPDATE weapon SET name = "失去魔力的克特之劍", unidentified_name_id = "$2777", identified_name_id = "$2777" WHERE item_id = "15";
UPDATE weapon SET name = "復仇之劍", unidentified_name_id = "$2762", identified_name_id = "$2762" WHERE item_id = "16";
UPDATE weapon SET name = "受封印 被遺忘的巨劍", unidentified_name_id = "$1958 $1938", identified_name_id = "$1958 $1938" WHERE item_id = "17";
UPDATE weapon SET name = "受封印 被遺忘的劍", unidentified_name_id = "$1958 $1939", identified_name_id = "$1958 $1939" WHERE item_id = "18";
UPDATE weapon SET name = "長劍的劍身", unidentified_name_id = "$786", identified_name_id = "$786" WHERE item_id = "19";
UPDATE weapon SET name = "奧里哈魯根的劍身", unidentified_name_id = "$787", identified_name_id = "$787" WHERE item_id = "20";
UPDATE weapon SET name = "歐西斯短劍", unidentified_name_id = "$99", identified_name_id = "$99" WHERE item_id = "21";
UPDATE weapon SET name = "鎖子甲破壞者", unidentified_name_id = "$793", identified_name_id = "$793" WHERE item_id = "22";
UPDATE weapon SET name = "闊劍", unidentified_name_id = "$66", identified_name_id = "$66" WHERE item_id = "23";
UPDATE weapon SET name = "短劍", unidentified_name_id = "$100", identified_name_id = "$100" WHERE item_id = "24";
UPDATE weapon SET name = "銀劍", unidentified_name_id = "$1148", identified_name_id = "$1148" WHERE item_id = "25";
UPDATE weapon SET name = "小侏儒短劍", unidentified_name_id = "$97", identified_name_id = "$97" WHERE item_id = "26";
UPDATE weapon SET name = "彎刀", unidentified_name_id = "$92", identified_name_id = "$92" WHERE item_id = "27";
UPDATE weapon SET name = "精靈短劍", unidentified_name_id = "$98", identified_name_id = "$98" WHERE item_id = "28";
UPDATE weapon SET name = "銀長劍", unidentified_name_id = "$1147", identified_name_id = "$1147" WHERE item_id = "29";
UPDATE weapon SET name = "紅騎士之劍", unidentified_name_id = "$313", identified_name_id = "$313" WHERE item_id = "30";
UPDATE weapon SET name = "長劍", unidentified_name_id = "$0", identified_name_id = "$0" WHERE item_id = "31";
UPDATE weapon SET name = "侵略者之劍", unidentified_name_id = "$415", identified_name_id = "$415" WHERE item_id = "32";
UPDATE weapon SET name = "榮耀之劍", unidentified_name_id = "$3790", identified_name_id = "$3790" WHERE item_id = "33";
UPDATE weapon SET name = "血紅慾望短劍", unidentified_name_id = "$3795", identified_name_id = "$3795" WHERE item_id = "34";
UPDATE weapon SET name = "象牙塔單手劍", unidentified_name_id = "$3279", identified_name_id = "$3279" WHERE item_id = "35";
UPDATE weapon SET name = "幻象之劍", unidentified_name_id = "$1997", identified_name_id = "$1997" WHERE item_id = "36";
UPDATE weapon SET name = "大馬士革刀", unidentified_name_id = "$598", identified_name_id = "$598" WHERE item_id = "37";
UPDATE weapon SET name = "拉斯塔巴德長劍", unidentified_name_id = "$2903", identified_name_id = "$2903" WHERE item_id = "38";
UPDATE weapon SET name = "短刀", unidentified_name_id = "$3504", identified_name_id = "$3504" WHERE item_id = "39";
UPDATE weapon SET name = "血色巨劍", unidentified_name_id = "$3864", identified_name_id = "$3864" WHERE item_id = "40";
UPDATE weapon SET name = "武士刀", unidentified_name_id = "$16", identified_name_id = "$16" WHERE item_id = "41";
UPDATE weapon SET name = "細劍", unidentified_name_id = "$789", identified_name_id = "$789" WHERE item_id = "42";
UPDATE weapon SET name = "海賊彎刀", unidentified_name_id = "$3505", identified_name_id = "$3505" WHERE item_id = "43";
UPDATE weapon SET name = "古代黑暗妖精之劍", unidentified_name_id = "$2772", identified_name_id = "$2772" WHERE item_id = "44";
UPDATE weapon SET name = "波曲王之劍", unidentified_name_id = "$428", identified_name_id = "$428" WHERE item_id = "45";
UPDATE weapon SET name = "生命之劍", unidentified_name_id = "$1553", identified_name_id = "$1553" WHERE item_id = "46";
UPDATE weapon SET name = "沉默之劍", unidentified_name_id = "$3110", identified_name_id = "$3110" WHERE item_id = "47";
UPDATE weapon SET name = "象牙塔雙手劍", unidentified_name_id = "$3280", identified_name_id = "$3280" WHERE item_id = "48";
UPDATE weapon SET name = "武官之刃", unidentified_name_id = "$3840", identified_name_id = "$3840" WHERE item_id = "49";
UPDATE weapon SET name = "赤焰之劍", unidentified_name_id = "$2353", identified_name_id = "$2353" WHERE item_id = "50";
UPDATE weapon SET name = "黃金權杖", unidentified_name_id = "$2354", identified_name_id = "$2354" WHERE item_id = "51";
UPDATE weapon SET name = "雙手劍", unidentified_name_id = "$3", identified_name_id = "$3" WHERE item_id = "52";
UPDATE weapon SET name = "蜥蜴王勇士之劍", unidentified_name_id = "$3796", identified_name_id = "$3796" WHERE item_id = "53";
UPDATE weapon SET name = "克特之劍", unidentified_name_id = "$2994", identified_name_id = "$2994" WHERE item_id = "54";
UPDATE weapon SET name = "黑暗之劍", unidentified_name_id = "$3863", identified_name_id = "$3863" WHERE item_id = "55";
UPDATE weapon SET name = "黑燄之劍", unidentified_name_id = "$2350", identified_name_id = "$2350" WHERE item_id = "56";
UPDATE weapon SET name = "瑟魯基之劍", unidentified_name_id = "$17", identified_name_id = "$17" WHERE item_id = "57";
UPDATE weapon SET name = "死亡騎士的烈炎之劍", unidentified_name_id = "$2758", identified_name_id = "$2758" WHERE item_id = "58";
UPDATE weapon SET name = "騎士范德之劍", unidentified_name_id = "$2859", identified_name_id = "$2859" WHERE item_id = "59";
UPDATE weapon SET name = "末日刀", unidentified_name_id = "$417", identified_name_id = "$417" WHERE item_id = "60";
UPDATE weapon SET name = "真．冥皇執行劍", unidentified_name_id = "$3834", identified_name_id = "$3834" WHERE item_id = "61";
UPDATE weapon SET name = "武官雙手劍", unidentified_name_id = "$3839", identified_name_id = "$3839" WHERE item_id = "62";
UPDATE weapon SET name = "惡魔之劍", unidentified_name_id = "$3375", identified_name_id = "$3375" WHERE item_id = "63";
UPDATE weapon SET name = "巨劍", unidentified_name_id = "$1048", identified_name_id = "$1048" WHERE item_id = "64";
UPDATE weapon SET name = "天空之劍", unidentified_name_id = "$2253", identified_name_id = "$2253" WHERE item_id = "65";
UPDATE weapon SET name = "屠龍劍", unidentified_name_id = "$1020", identified_name_id = "$1020" WHERE item_id = "66";
UPDATE weapon SET name = "古老的巨劍", unidentified_name_id = "$1951", identified_name_id = "$1951" WHERE item_id = "67";
UPDATE weapon SET name = "古老的劍", unidentified_name_id = "$1950", identified_name_id = "$1950" WHERE item_id = "68";
UPDATE weapon SET name = "青銅 雙刀", unidentified_name_id = "$2458 $2449", identified_name_id = "$2458 $2449" WHERE item_id = "69";
UPDATE weapon SET name = "尖刺雙刀", unidentified_name_id = "$3866", identified_name_id = "$3866" WHERE item_id = "70";
UPDATE weapon SET name = "鋼鐵 雙刀", unidentified_name_id = "$2459 $2449", identified_name_id = "$2459 $2449" WHERE item_id = "71";
UPDATE weapon SET name = "暗影 雙刀", unidentified_name_id = "$2460 $2449", identified_name_id = "$2460 $2449" WHERE item_id = "72";
UPDATE weapon SET name = "象牙塔雙刀", unidentified_name_id = "$3286", identified_name_id = "$3286" WHERE item_id = "73";
UPDATE weapon SET name = "銀光 雙刀", unidentified_name_id = "$2454 $2449", identified_name_id = "$2454 $2449" WHERE item_id = "74";
UPDATE weapon SET name = "黑暗 雙刀", unidentified_name_id = "$2452 $2449", identified_name_id = "$2452 $2449" WHERE item_id = "75";
UPDATE weapon SET name = "倫得雙刀", unidentified_name_id = "$2759", identified_name_id = "$2759" WHERE item_id = "76";
UPDATE weapon SET name = "短 雙刀", unidentified_name_id = "$2461 $2449", identified_name_id = "$2461 $2449" WHERE item_id = "77";
UPDATE weapon SET name = "暗殺軍王之痕", unidentified_name_id = "$3860", identified_name_id = "$3860" WHERE item_id = "78";
UPDATE weapon SET name = "深淵雙刀", unidentified_name_id = "$3791", identified_name_id = "$3791" WHERE item_id = "79";
UPDATE weapon SET name = "大馬士革 雙刀", unidentified_name_id = "$2462 $2449", identified_name_id = "$2462 $2449" WHERE item_id = "80";
UPDATE weapon SET name = "幽暗 雙刀", unidentified_name_id = "$2453 $2449", identified_name_id = "$2453 $2449" WHERE item_id = "81";
UPDATE weapon SET name = "拉斯塔巴德雙刀", unidentified_name_id = "$2904", identified_name_id = "$2904" WHERE item_id = "82";
UPDATE weapon SET name = "狄亞得雙刀", unidentified_name_id = "$3111", identified_name_id = "$3111" WHERE item_id = "83";
UPDATE weapon SET name = "暗黑雙刀", unidentified_name_id = "$2455", identified_name_id = "$2455" WHERE item_id = "84";
UPDATE weapon SET name = "惡魔雙刀", unidentified_name_id = "$3376", identified_name_id = "$3376" WHERE item_id = "85";
UPDATE weapon SET name = "紅影雙刀", unidentified_name_id = "$3836", identified_name_id = "$3836" WHERE item_id = "86";
UPDATE weapon SET name = "不為人知的矛", unidentified_name_id = "$2760", identified_name_id = "$2760" WHERE item_id = "87";
UPDATE weapon SET name = "潘的角", unidentified_name_id = "$783", identified_name_id = "$783" WHERE item_id = "88";
UPDATE weapon SET name = "覆上米索莉的角", unidentified_name_id = "$791", identified_name_id = "$791" WHERE item_id = "89";
UPDATE weapon SET name = "巴迪須", unidentified_name_id = "$62", identified_name_id = "$62" WHERE item_id = "90";
UPDATE weapon SET name = "歐西斯之矛", unidentified_name_id = "$96", identified_name_id = "$96" WHERE item_id = "91";
UPDATE weapon SET name = "柴刀", unidentified_name_id = "$63", identified_name_id = "$63" WHERE item_id = "92";
UPDATE weapon SET name = "三叉戟", unidentified_name_id = "$102", identified_name_id = "$102" WHERE item_id = "93";
UPDATE weapon SET name = "帕提森", unidentified_name_id = "$87", identified_name_id = "$87" WHERE item_id = "94";
UPDATE weapon SET name = "槍", unidentified_name_id = "$81", identified_name_id = "$81" WHERE item_id = "95";
UPDATE weapon SET name = "矛", unidentified_name_id = "$25", identified_name_id = "$25" WHERE item_id = "96";
UPDATE weapon SET name = "吉薩", unidentified_name_id = "$76", identified_name_id = "$76" WHERE item_id = "97";
UPDATE weapon SET name = "闊矛", unidentified_name_id = "$75", identified_name_id = "$75" WHERE item_id = "98";
UPDATE weapon SET name = "精靈之矛", unidentified_name_id = "$95", identified_name_id = "$95" WHERE item_id = "99";
UPDATE weapon SET name = "覆上奧里哈魯根的角", unidentified_name_id = "$792", identified_name_id = "$792" WHERE item_id = "100";
UPDATE weapon SET name = "拉斯塔巴德矛", unidentified_name_id = "$2906", identified_name_id = "$2906" WHERE item_id = "101";
UPDATE weapon SET name = "露西錘", unidentified_name_id = "$83", identified_name_id = "$83" WHERE item_id = "102";
UPDATE weapon SET name = "戟", unidentified_name_id = "$77", identified_name_id = "$77" WHERE item_id = "103";
UPDATE weapon SET name = "法丘", unidentified_name_id = "$73", identified_name_id = "$73" WHERE item_id = "104";
UPDATE weapon SET name = "象牙塔長矛", unidentified_name_id = "$3282", identified_name_id = "$3282" WHERE item_id = "105";
UPDATE weapon SET name = "貝卡合金", unidentified_name_id = "$71", identified_name_id = "$71" WHERE item_id = "106";
UPDATE weapon SET name = "深紅長矛", unidentified_name_id = "$3250", identified_name_id = "$3250" WHERE item_id = "107";
UPDATE weapon SET name = "失去魔力的惡魔鐮刀", unidentified_name_id = "$2764", identified_name_id = "$2764" WHERE item_id = "108";
UPDATE weapon SET name = "失去魔力的巴風特魔杖", unidentified_name_id = "$2766", identified_name_id = "$2766" WHERE item_id = "109";
UPDATE weapon SET name = "失去魔力的巴列斯魔杖", unidentified_name_id = "$2768", identified_name_id = "$2768" WHERE item_id = "110";
UPDATE weapon SET name = "失去魔力的冰之女王魔杖", unidentified_name_id = "$2754", identified_name_id = "$2754" WHERE item_id = "111";
UPDATE weapon SET name = "抗魔精靈短劍", unidentified_name_id = "$801", identified_name_id = "$801" WHERE item_id = "112";
UPDATE weapon SET name = "敏捷精靈短劍", unidentified_name_id = "$802", identified_name_id = "$802" WHERE item_id = "113";
UPDATE weapon SET name = "威嚴權杖", unidentified_name_id = "$4386", identified_name_id = "$4386" WHERE item_id = "114";
UPDATE weapon SET name = "水晶魔杖", unidentified_name_id = "$2080", identified_name_id = "$2080" WHERE item_id = "115";
UPDATE weapon SET name = "黑法師之杖", unidentified_name_id = "$3089", identified_name_id = "$3089" WHERE item_id = "116";
UPDATE weapon SET name = "蕾雅魔杖", unidentified_name_id = "$3078", identified_name_id = "$3078" WHERE item_id = "117";
UPDATE weapon SET name = "漆黑水晶球", unidentified_name_id = "$3793", identified_name_id = "$3793" WHERE item_id = "118";
UPDATE weapon SET name = "惡魔鐮刀", unidentified_name_id = "$2991", identified_name_id = "$2991" WHERE item_id = "119";
UPDATE weapon SET name = "象牙塔魔杖", unidentified_name_id = "$3285", identified_name_id = "$3285" WHERE item_id = "120";
UPDATE weapon SET name = "冰之女王魔杖", unidentified_name_id = "$2990", identified_name_id = "$2990" WHERE item_id = "121";
UPDATE weapon SET name = "拉斯塔巴德魔杖", unidentified_name_id = "$2909", identified_name_id = "$2909" WHERE item_id = "122";
UPDATE weapon SET name = "巴列斯魔杖", unidentified_name_id = "$2993", identified_name_id = "$2993" WHERE item_id = "123";
UPDATE weapon SET name = "巴風特魔杖", unidentified_name_id = "$2992", identified_name_id = "$2992" WHERE item_id = "124";
UPDATE weapon SET name = "巫術魔法杖", unidentified_name_id = "$572", identified_name_id = "$572" WHERE item_id = "125";
UPDATE weapon SET name = "瑪那魔杖", unidentified_name_id = "$1063", identified_name_id = "$1063" WHERE item_id = "126";
UPDATE weapon SET name = "鋼鐵瑪那魔杖", unidentified_name_id = "$2003", identified_name_id = "$2003" WHERE item_id = "127";
UPDATE weapon SET name = "橡木魔法杖", unidentified_name_id = "$570", identified_name_id = "$570" WHERE item_id = "128";
UPDATE weapon SET name = "美基魔法杖", unidentified_name_id = "$571", identified_name_id = "$571" WHERE item_id = "129";
UPDATE weapon SET name = "紅水晶魔杖", unidentified_name_id = "$3865", identified_name_id = "$3865" WHERE item_id = "130";
UPDATE weapon SET name = "力量魔法杖", unidentified_name_id = "$573", identified_name_id = "$573" WHERE item_id = "131";
UPDATE weapon SET name = "神官魔杖", unidentified_name_id = "$3847", identified_name_id = "$3847" WHERE item_id = "132";
UPDATE weapon SET name = "古代人的智慧", unidentified_name_id = "$2241", identified_name_id = "$2241" WHERE item_id = "133";
UPDATE weapon SET name = "聖晶魔杖", unidentified_name_id = "$3838", identified_name_id = "$3838" WHERE item_id = "134";
UPDATE weapon SET name = "不為人知的斧", unidentified_name_id = "$2761", identified_name_id = "$2761" WHERE item_id = "135";
UPDATE weapon SET name = "斧", unidentified_name_id = "$1", identified_name_id = "$1" WHERE item_id = "136";
UPDATE weapon SET name = "亞連", unidentified_name_id = "$14", identified_name_id = "$14" WHERE item_id = "137";
UPDATE weapon SET name = "木棒", unidentified_name_id = "$69", identified_name_id = "$69" WHERE item_id = "138";
UPDATE weapon SET name = "弗萊爾", unidentified_name_id = "$74", identified_name_id = "$74" WHERE item_id = "139";
UPDATE weapon SET name = "釘錘", unidentified_name_id = "$20", identified_name_id = "$20" WHERE item_id = "140";
UPDATE weapon SET name = "戰錘", unidentified_name_id = "$111", identified_name_id = "$111" WHERE item_id = "141";
UPDATE weapon SET name = "銀斧", unidentified_name_id = "$1149", identified_name_id = "$1149" WHERE item_id = "142";
UPDATE weapon SET name = "戰斧", unidentified_name_id = "$60", identified_name_id = "$60" WHERE item_id = "143";
UPDATE weapon SET name = "侏儒鐵斧", unidentified_name_id = "$94", identified_name_id = "$94" WHERE item_id = "144";
UPDATE weapon SET name = "狂戰士斧", unidentified_name_id = "$418", identified_name_id = "$418" WHERE item_id = "145";
UPDATE weapon SET name = "流星錘", unidentified_name_id = "$84", identified_name_id = "$84" WHERE item_id = "146";
UPDATE weapon SET name = "象牙塔斧頭", unidentified_name_id = "$3281", identified_name_id = "$3281" WHERE item_id = "147";
UPDATE weapon SET name = "巨斧", unidentified_name_id = "$412", identified_name_id = "$412" WHERE item_id = "148";
UPDATE weapon SET name = "牛人斧頭", unidentified_name_id = "$2214", identified_name_id = "$2214" WHERE item_id = "149";
UPDATE weapon SET name = "天父之怒", unidentified_name_id = "$3735", identified_name_id = "$3735" WHERE item_id = "150";
UPDATE weapon SET name = "惡魔斧頭", unidentified_name_id = "$3249", identified_name_id = "$3249" WHERE item_id = "151";
UPDATE weapon SET name = "青銅 鋼爪", unidentified_name_id = "$2458 $2450", identified_name_id = "$2458 $2450" WHERE item_id = "152";
UPDATE weapon SET name = "鋼鐵 鋼爪", unidentified_name_id = "$2459 $2450", identified_name_id = "$2459 $2450" WHERE item_id = "153";
UPDATE weapon SET name = "暗影 鋼爪", unidentified_name_id = "$2460 $2450", identified_name_id = "$2460 $2450" WHERE item_id = "154";
UPDATE weapon SET name = "魔獸軍王之爪", unidentified_name_id = "$3861", identified_name_id = "$3861" WHERE item_id = "155";
UPDATE weapon SET name = "象牙塔鋼爪", unidentified_name_id = "$3287", identified_name_id = "$3287" WHERE item_id = "156";
UPDATE weapon SET name = "銀光 鋼爪", unidentified_name_id = "$2454 $2450", identified_name_id = "$2454 $2450" WHERE item_id = "157";
UPDATE weapon SET name = "黑暗 鋼爪", unidentified_name_id = "$2452 $2450", identified_name_id = "$2452 $2450" WHERE item_id = "158";
UPDATE weapon SET name = "短 鋼爪", unidentified_name_id = "$2461 $2450", identified_name_id = "$2461 $2450" WHERE item_id = "159";
UPDATE weapon SET name = "獸王鋼爪", unidentified_name_id = "$3837", identified_name_id = "$3837" WHERE item_id = "160";
UPDATE weapon SET name = "大馬士革 鋼爪", unidentified_name_id = "$2462 $2450", identified_name_id = "$2462 $2450" WHERE item_id = "161";
UPDATE weapon SET name = "幽暗 鋼爪", unidentified_name_id = "$2453 $2450", identified_name_id = "$2453 $2450" WHERE item_id = "162";
UPDATE weapon SET name = "巴蘭卡鋼爪", unidentified_name_id = "$3073", identified_name_id = "$3073" WHERE item_id = "163";
UPDATE weapon SET name = "暗黑鋼爪", unidentified_name_id = "$2456", identified_name_id = "$2456" WHERE item_id = "164";
UPDATE weapon SET name = "惡魔鋼爪", unidentified_name_id = "$3377", identified_name_id = "$3377" WHERE item_id = "165";
UPDATE weapon SET name = "恨之鋼爪", unidentified_name_id = "$2763", identified_name_id = "$2763" WHERE item_id = "166";
UPDATE weapon SET name = "受封印 被遺忘的弩槍", unidentified_name_id = "$1958 $1940", identified_name_id = "$1958 $1940" WHERE item_id = "167";
UPDATE weapon SET name = "黑暗十字弓", unidentified_name_id = "$2452$2451", identified_name_id = "$2452$2451" WHERE item_id = "168";
UPDATE weapon SET name = "獵人之弓", unidentified_name_id = "$1244", identified_name_id = "$1244" WHERE item_id = "169";
UPDATE weapon SET name = "精靈弓", unidentified_name_id = "$64", identified_name_id = "$64" WHERE item_id = "170";
UPDATE weapon SET name = "歐西斯弓", unidentified_name_id = "$65", identified_name_id = "$65" WHERE item_id = "171";
UPDATE weapon SET name = "弓", unidentified_name_id = "$24", identified_name_id = "$24" WHERE item_id = "172";
UPDATE weapon SET name = "短弓", unidentified_name_id = "$759", identified_name_id = "$759" WHERE item_id = "173";
UPDATE weapon SET name = "象牙塔石弓", unidentified_name_id = "$3284", identified_name_id = "$3284" WHERE item_id = "174";
UPDATE weapon SET name = "象牙塔長弓", unidentified_name_id = "$3283", identified_name_id = "$3283" WHERE item_id = "175";
UPDATE weapon SET name = "拉斯塔巴德弓", unidentified_name_id = "$2907", identified_name_id = "$2907" WHERE item_id = "176";
UPDATE weapon SET name = "幽暗十字弓", unidentified_name_id = "$2453$2451", identified_name_id = "$2453$2451" WHERE item_id = "177";
UPDATE weapon SET name = "寂靜十字弓", unidentified_name_id = "$3792", identified_name_id = "$3792" WHERE item_id = "178";
UPDATE weapon SET name = "古代妖精弩槍", unidentified_name_id = "$2771", identified_name_id = "$2771" WHERE item_id = "179";
UPDATE weapon SET name = "十字弓", unidentified_name_id = "$784", identified_name_id = "$784" WHERE item_id = "180";
UPDATE weapon SET name = "尤米弓", unidentified_name_id = "$105", identified_name_id = "$105" WHERE item_id = "181";
UPDATE weapon SET name = "古老的弩槍", unidentified_name_id = "$1952", identified_name_id = "$1952" WHERE item_id = "182";
UPDATE weapon SET name = "幻象之弓", unidentified_name_id = "$1999", identified_name_id = "$1999" WHERE item_id = "183";
UPDATE weapon SET name = "赤焰之弓", unidentified_name_id = "$2352", identified_name_id = "$2352" WHERE item_id = "184";
UPDATE weapon SET name = "惡魔十字弓", unidentified_name_id = "$3374", identified_name_id = "$3374" WHERE item_id = "185";
UPDATE weapon SET name = "狄亞得十字弓", unidentified_name_id = "$3112", identified_name_id = "$3112" WHERE item_id = "186";
UPDATE weapon SET name = "拉斯塔巴德十字弓", unidentified_name_id = "$2915", identified_name_id = "$2915" WHERE item_id = "187";
UPDATE weapon SET name = "拉斯塔巴德重十字弓", unidentified_name_id = "$2908", identified_name_id = "$2908" WHERE item_id = "188";
UPDATE weapon SET name = "暗黑十字弓", unidentified_name_id = "$2457", identified_name_id = "$2457" WHERE item_id = "189";
UPDATE weapon SET name = "沙哈之弓", unidentified_name_id = "$1821", identified_name_id = "$1821" WHERE item_id = "190";
UPDATE weapon SET name = "弒神者之弓", unidentified_name_id = "$3736", identified_name_id = "$3736" WHERE item_id = "191";
UPDATE weapon SET name = "水精靈之弓", unidentified_name_id = "$2252", identified_name_id = "$2252" WHERE item_id = "192";
UPDATE weapon SET name = "鐵手甲", unidentified_name_id = "$2464", identified_name_id = "$2464" WHERE item_id = "193";
UPDATE weapon SET name = "真鐵手甲", unidentified_name_id = "$2626", identified_name_id = "$2626" WHERE item_id = "194";
UPDATE weapon SET name = "受詛咒的真．冥皇執行劍", unidentified_name_id = "$4338", identified_name_id = "$4338" WHERE item_id = "195";
UPDATE weapon SET name = "炎魔雙手劍 Lv.1", unidentified_name_id = "$4423 Lv.1", identified_name_id = "$4423 Lv.1" WHERE item_id = "196";
UPDATE weapon SET name = "炎魔雙手劍 Lv.2", unidentified_name_id = "$4423 Lv.2", identified_name_id = "$4423 Lv.2" WHERE item_id = "197";
UPDATE weapon SET name = "炎魔雙手劍 Lv.3", unidentified_name_id = "$4423 Lv.3", identified_name_id = "$4423 Lv.3" WHERE item_id = "198";
UPDATE weapon SET name = "炎魔雙手劍 Lv.4", unidentified_name_id = "$4423 Lv.4", identified_name_id = "$4423 Lv.4" WHERE item_id = "199";
UPDATE weapon SET name = "炎魔雙手劍 Lv.5", unidentified_name_id = "$4423 Lv.5", identified_name_id = "$4423 Lv.5" WHERE item_id = "200";
UPDATE weapon SET name = "炎魔雙手劍 Lv.6", unidentified_name_id = "$4423 Lv.6", identified_name_id = "$4423 Lv.6" WHERE item_id = "201";
UPDATE weapon SET name = "炎魔雙手劍 Lv.7", unidentified_name_id = "$4423 Lv.7", identified_name_id = "$4423 Lv.7" WHERE item_id = "202";
UPDATE weapon SET name = "炎魔雙手劍 Lv.8", unidentified_name_id = "$4423 Lv.8", identified_name_id = "$4423 Lv.8" WHERE item_id = "203";
UPDATE weapon SET name = "深紅之弩", unidentified_name_id = "$4387", identified_name_id = "$4387" WHERE item_id = "204";
UPDATE weapon SET name = "熾炎天使弓", unidentified_name_id = "$4350", identified_name_id = "$4350" WHERE item_id = "205";
UPDATE weapon SET name = "黑暗妖精之劍", unidentified_name_id = "$2536", identified_name_id = "$2536" WHERE item_id = "206";
UPDATE weapon SET name = "煉獄鋼爪", unidentified_name_id = "$4384", identified_name_id = "$4384" WHERE item_id = "207";
UPDATE weapon SET name = "魔法精靈短劍", unidentified_name_id = "$803", identified_name_id = "$803" WHERE item_id = "208";
UPDATE weapon SET name = "體質精靈短劍", unidentified_name_id = "$1098", identified_name_id = "$1098" WHERE item_id = "209";
UPDATE weapon SET name = "守護者之矛", unidentified_name_id = "$4429", identified_name_id = "$4429" WHERE item_id = "210";
UPDATE weapon SET name = "獨角獸之角", unidentified_name_id = "$103", identified_name_id = "$103" WHERE item_id = "211";
UPDATE weapon SET name = "海神三叉戟", unidentified_name_id = "$4385", identified_name_id = "$4385" WHERE item_id = "212";
UPDATE weapon SET name = "吉爾塔斯魔杖", unidentified_name_id = "$4376", identified_name_id = "$4376" WHERE item_id = "213";
UPDATE weapon SET name = "ID．妖精弓", unidentified_name_id = "$3997", identified_name_id = "$3997" WHERE item_id = "214";
UPDATE weapon SET name = "敏捷精靈弓", unidentified_name_id = "$1099", identified_name_id = "$1099" WHERE item_id = "215";
UPDATE weapon SET name = "妖精之弓", unidentified_name_id = "$1766", identified_name_id = "$1766" WHERE item_id = "216";
UPDATE weapon SET name = "吉爾塔斯之劍", unidentified_name_id = "$4375", identified_name_id = "$4375" WHERE item_id = "217";
UPDATE weapon SET name = "安加斯的釘錘", unidentified_name_id = "$4442", identified_name_id = "$4442" WHERE item_id = "218";
UPDATE weapon SET name = "馬普勒之斧", unidentified_name_id = "$2208", identified_name_id = "$2208" WHERE item_id = "219";
UPDATE weapon SET name = "法師之杖", unidentified_name_id = "$1770", identified_name_id = "$1770" WHERE item_id = "220";
UPDATE weapon SET name = "神秘魔杖", unidentified_name_id = "$2079", identified_name_id = "$2079" WHERE item_id = "223";
UPDATE weapon SET name = "象牙塔魔杖", unidentified_name_id = "$3285", identified_name_id = "$3285" WHERE item_id = "224";
UPDATE weapon SET name = "王族之劍", unidentified_name_id = "$1762", identified_name_id = "$1762" WHERE item_id = "225";
UPDATE weapon SET name = "騎士之劍", unidentified_name_id = "$2293", identified_name_id = "$2293" WHERE item_id = "226";
UPDATE weapon SET name = "傳說的匕首", unidentified_name_id = "$3612", identified_name_id = "$3612" WHERE item_id = "228";
UPDATE weapon SET name = "蒼天匕首", unidentified_name_id = "$5122", identified_name_id = "$5122" WHERE item_id = "231";
UPDATE weapon SET name = "蒼天之劍", unidentified_name_id = "$5117", identified_name_id = "$5117" WHERE item_id = "232";
UPDATE weapon SET name = "蒼天巨劍", unidentified_name_id = "$5118", identified_name_id = "$5118" WHERE item_id = "233";
UPDATE weapon SET name = "蒼天長矛", unidentified_name_id = "$5121", identified_name_id = "$5121" WHERE item_id = "234";
UPDATE weapon SET name = "蒼天巨斧", unidentified_name_id = "$5119", identified_name_id = "$5119" WHERE item_id = "235";
UPDATE weapon SET name = "蒼天雙刀", unidentified_name_id = "$5123", identified_name_id = "$5123" WHERE item_id = "236";
UPDATE weapon SET name = "蒼天鋼爪", unidentified_name_id = "$5124", identified_name_id = "$5124" WHERE item_id = "237";
UPDATE weapon SET name = "蒼天魔杖", unidentified_name_id = "$5125", identified_name_id = "$5125" WHERE item_id = "238";
UPDATE weapon SET name = "蒼天之弓", unidentified_name_id = "$5120", identified_name_id = "$5120" WHERE item_id = "239";
UPDATE weapon SET name = "蒼天鐵手甲", unidentified_name_id = "$5126", identified_name_id = "$5126" WHERE item_id = "240";
UPDATE weapon SET name = "歷戰之劍", unidentified_name_id = "歷戰之劍", identified_name_id = "歷戰之劍" WHERE item_id = "241";
UPDATE weapon SET name = "歷戰十字弓", unidentified_name_id = "歷戰$2451", identified_name_id = "歷戰$2451" WHERE item_id = "242";
UPDATE weapon SET name = "歷戰魔杖", unidentified_name_id = "歷戰魔杖", identified_name_id = "歷戰魔杖" WHERE item_id = "243";
UPDATE weapon SET name = "歷戰鋼爪", unidentified_name_id = "歷戰$2450", identified_name_id = "歷戰$2450" WHERE item_id = "244";
UPDATE weapon SET name = "精靈叮叮鎚", unidentified_name_id = "$4962", identified_name_id = "$4962" WHERE item_id = "245";
UPDATE weapon SET name = "試煉之劍A", unidentified_name_id = "$4023", identified_name_id = "$4023" WHERE item_id = "246";
UPDATE weapon SET name = "試煉之劍B", unidentified_name_id = "$4024", identified_name_id = "$4024" WHERE item_id = "247";
UPDATE weapon SET name = "試煉之劍C", unidentified_name_id = "$4025", identified_name_id = "$4025" WHERE item_id = "248";
UPDATE weapon SET name = "試煉之劍D", unidentified_name_id = "$4026", identified_name_id = "$4026" WHERE item_id = "249";
UPDATE weapon SET name = "イリュージョン ダガー", unidentified_name_id = "イリュージョン ダガー", identified_name_id = "イリュージョン ダガー" WHERE item_id = "250";
UPDATE weapon SET name = "イリュージョン ツヴァイハンダー", unidentified_name_id = "イリュージョン ツヴァイハンダー", identified_name_id = "イリュージョン ツヴァイハンダー" WHERE item_id = "251";
UPDATE weapon SET name = "イリュージョン スピアー", unidentified_name_id = "イリュージョン スピアー", identified_name_id = "イリュージョン スピアー" WHERE item_id = "252";
UPDATE weapon SET name = "イリュージョン アックス", unidentified_name_id = "イリュージョン アックス", identified_name_id = "イリュージョン アックス" WHERE item_id = "253";
UPDATE weapon SET name = "イリュージョン デュアルブレード", unidentified_name_id = "イリュージョン デュアルブレード", identified_name_id = "イリュージョン デュアルブレード" WHERE item_id = "254";
UPDATE weapon SET name = "イリュージョン スタッフ", unidentified_name_id = "イリュージョン スタッフ", identified_name_id = "イリュージョン スタッフ" WHERE item_id = "255";
UPDATE weapon SET name = "萬聖節南瓜長劍(韓)", unidentified_name_id = "$5254", identified_name_id = "$5254" WHERE item_id = "256";
UPDATE weapon SET name = "萬聖節南瓜長劍(日)", unidentified_name_id = "$5254", identified_name_id = "$5254" WHERE item_id = "257";
UPDATE weapon SET name = "終極萬聖節南瓜長劍", unidentified_name_id = "終極萬聖節南瓜長劍", identified_name_id = "終極萬聖節南瓜長劍" WHERE item_id = "258";
UPDATE weapon SET name = "魔力短劍", unidentified_name_id = "$5486", identified_name_id = "$5486" WHERE item_id = "259";
UPDATE weapon SET name = "狂風之斧", unidentified_name_id = "$5487", identified_name_id = "$5487" WHERE item_id = "260";
UPDATE weapon SET name = "大法師魔杖", unidentified_name_id = "$5489", identified_name_id = "$5489" WHERE item_id = "261";
UPDATE weapon SET name = "毀滅巨劍", unidentified_name_id = "$5488", identified_name_id = "$5488" WHERE item_id = "262";
UPDATE weapon SET name = "酷寒之矛", unidentified_name_id = "$5490", identified_name_id = "$5490" WHERE item_id = "263";
UPDATE weapon SET name = "雷雨之劍", unidentified_name_id = "$5491", identified_name_id = "$5491" WHERE item_id = "264";
UPDATE weapon SET name = "底比斯歐西里斯雙刀", unidentified_name_id = "$5718", identified_name_id = "$5718" WHERE item_id = "265";
UPDATE weapon SET name = "底比斯歐西里斯雙手劍", unidentified_name_id = "$5719", identified_name_id = "$5719" WHERE item_id = "266";
UPDATE weapon SET name = "底比斯歐西里斯弓", unidentified_name_id = "$5720", identified_name_id = "$5720" WHERE item_id = "267";
UPDATE weapon SET name = "底比斯歐西里斯魔杖", unidentified_name_id = "$5721", identified_name_id = "$5721" WHERE item_id = "268";
UPDATE weapon SET name = "幻術士魔杖", unidentified_name_id = "$5661", identified_name_id = "$5661" WHERE item_id = "269";
UPDATE weapon SET name = "藍寶石奇古獸", unidentified_name_id = "$5662", identified_name_id = "$5662" WHERE item_id = "270";
UPDATE weapon SET name = "黑曜石奇古獸", unidentified_name_id = "$5663", identified_name_id = "$5663" WHERE item_id = "271";
UPDATE weapon SET name = "消滅者鎖鏈劍", unidentified_name_id = "$5668", identified_name_id = "$5668" WHERE item_id = "272";
UPDATE weapon SET name = "破滅者鎖鏈劍", unidentified_name_id = "$5669", identified_name_id = "$5669" WHERE item_id = "273";
UPDATE weapon SET name = "反王肯恩的權杖", unidentified_name_id = "$5631", identified_name_id = "$5631" WHERE item_id = "274";
UPDATE weapon SET name = "龍騎士雙手劍", unidentified_name_id = "$5664", identified_name_id = "$5664" WHERE item_id = "275";
UPDATE weapon SET name = "匕首", unidentified_name_id = "$70", identified_name_id = "$70" WHERE item_id = "100004";
UPDATE weapon SET name = "精靈匕首", unidentified_name_id = "$12", identified_name_id = "$12" WHERE item_id = "100005";
UPDATE weapon SET name = "米索莉短劍", unidentified_name_id = "$3248", identified_name_id = "$3248" WHERE item_id = "100008";
UPDATE weapon SET name = "奧里哈魯根短劍", unidentified_name_id = "$3247", identified_name_id = "$3247" WHERE item_id = "100009";
UPDATE weapon SET name = "銀劍", unidentified_name_id = "$1148", identified_name_id = "$1148" WHERE item_id = "100025";
UPDATE weapon SET name = "彎刀", unidentified_name_id = "$92", identified_name_id = "$92" WHERE item_id = "100027";
UPDATE weapon SET name = "精靈短劍", unidentified_name_id = "$98", identified_name_id = "$98" WHERE item_id = "100028";
UPDATE weapon SET name = "銀長劍", unidentified_name_id = "$1147", identified_name_id = "$1147" WHERE item_id = "100029";
UPDATE weapon SET name = "大馬士革刀", unidentified_name_id = "$598", identified_name_id = "$598" WHERE item_id = "100037";
UPDATE weapon SET name = "武士刀", unidentified_name_id = "$16", identified_name_id = "$16" WHERE item_id = "100041";
UPDATE weapon SET name = "細劍", unidentified_name_id = "$789", identified_name_id = "$789" WHERE item_id = "100042";
UPDATE weapon SET name = "武官之刃", unidentified_name_id = "$3840", identified_name_id = "$3840" WHERE item_id = "100049";
UPDATE weapon SET name = "雙手劍", unidentified_name_id = "$3", identified_name_id = "$3" WHERE item_id = "100052";
UPDATE weapon SET name = "瑟魯基之劍", unidentified_name_id = "$17", identified_name_id = "$17" WHERE item_id = "100057";
UPDATE weapon SET name = "武官雙手劍", unidentified_name_id = "$3839", identified_name_id = "$3839" WHERE item_id = "100062";
UPDATE weapon SET name = "巨劍", unidentified_name_id = "$1048", identified_name_id = "$1048" WHERE item_id = "100064";
UPDATE weapon SET name = "銀光 雙刀", unidentified_name_id = "$2454 $2449", identified_name_id = "$2454 $2449" WHERE item_id = "100074";
UPDATE weapon SET name = "暗黑雙刀", unidentified_name_id = "$2455", identified_name_id = "$2455" WHERE item_id = "100084";
UPDATE weapon SET name = "槍", unidentified_name_id = "$81", identified_name_id = "$81" WHERE item_id = "100095";
UPDATE weapon SET name = "闊矛", unidentified_name_id = "$75", identified_name_id = "$75" WHERE item_id = "100098";
UPDATE weapon SET name = "精靈之矛", unidentified_name_id = "$95", identified_name_id = "$95" WHERE item_id = "100099";
UPDATE weapon SET name = "露西錘", unidentified_name_id = "$83", identified_name_id = "$83" WHERE item_id = "100102";
UPDATE weapon SET name = "戟", unidentified_name_id = "$77", identified_name_id = "$77" WHERE item_id = "100103";
UPDATE weapon SET name = "深紅長矛", unidentified_name_id = "$3250", identified_name_id = "$3250" WHERE item_id = "100107";
UPDATE weapon SET name = "威嚴權杖", unidentified_name_id = "$4386", identified_name_id = "$4386" WHERE item_id = "100114";
UPDATE weapon SET name = "神官魔杖", unidentified_name_id = "$3847", identified_name_id = "$3847" WHERE item_id = "100132";
UPDATE weapon SET name = "戰斧", unidentified_name_id = "$60", identified_name_id = "$60" WHERE item_id = "100143";
UPDATE weapon SET name = "流星錘", unidentified_name_id = "$84", identified_name_id = "$84" WHERE item_id = "100146";
UPDATE weapon SET name = "惡魔斧頭", unidentified_name_id = "$3249", identified_name_id = "$3249" WHERE item_id = "100151";
UPDATE weapon SET name = "銀光 鋼爪", unidentified_name_id = "$2454 $2450", identified_name_id = "$2454 $2450" WHERE item_id = "100157";
UPDATE weapon SET name = "暗黑鋼爪", unidentified_name_id = "$2456", identified_name_id = "$2456" WHERE item_id = "100164";
UPDATE weapon SET name = "獵人之弓", unidentified_name_id = "$1244", identified_name_id = "$1244" WHERE item_id = "100169";
UPDATE weapon SET name = "精靈弓", unidentified_name_id = "$64", identified_name_id = "$64" WHERE item_id = "100170";
UPDATE weapon SET name = "弓", unidentified_name_id = "$24", identified_name_id = "$24" WHERE item_id = "100172";
UPDATE weapon SET name = "十字弓", unidentified_name_id = "$784", identified_name_id = "$784" WHERE item_id = "100180";
UPDATE weapon SET name = "尤米弓", unidentified_name_id = "$105", identified_name_id = "$105" WHERE item_id = "100181";
UPDATE weapon SET name = "暗黑十字弓", unidentified_name_id = "$2457", identified_name_id = "$2457" WHERE item_id = "100189";
UPDATE weapon SET name = "深紅之弩", unidentified_name_id = "$4387", identified_name_id = "$4387" WHERE item_id = "100204";
UPDATE weapon SET name = "煉獄鋼爪", unidentified_name_id = "$4384", identified_name_id = "$4384" WHERE item_id = "100207";
UPDATE weapon SET name = "海神三叉戟", unidentified_name_id = "$4385", identified_name_id = "$4385" WHERE item_id = "100212";
UPDATE weapon SET name = "歐西斯匕首", unidentified_name_id = "$13", identified_name_id = "$13" WHERE item_id = "200001";
UPDATE weapon SET name = "骰子匕首", unidentified_name_id = "$416", identified_name_id = "$416" WHERE item_id = "200002";
UPDATE weapon SET name = "彎刀", unidentified_name_id = "$92", identified_name_id = "$92" WHERE item_id = "200027";
UPDATE weapon SET name = "侵略者之劍", unidentified_name_id = "$415", identified_name_id = "$415" WHERE item_id = "200032";
UPDATE weapon SET name = "武士刀", unidentified_name_id = "$16", identified_name_id = "$16" WHERE item_id = "200041";
UPDATE weapon SET name = "雙手劍", unidentified_name_id = "$3", identified_name_id = "$3" WHERE item_id = "200052";
UPDATE weapon SET name = "歐西斯弓", unidentified_name_id = "$65", identified_name_id = "$65" WHERE item_id = "200171";
