/*	[4/22]
L1j1749
*/
Update resolvent Set note = '歐西斯匕首' Where item_id = '1';
Update resolvent Set note = '歐西斯匕首' Where item_id = '200001';
Update resolvent Set note = '歐西斯短劍' Where item_id = '21';
Update resolvent Set note = '骰子匕首' Where item_id = '2';
Update resolvent Set note = '骰子匕首' Where item_id = '200002';
Update resolvent Set note = '闊劍' Where item_id = '23';
Update resolvent Set note = '小侏儒短劍' Where item_id = '26';
Update resolvent Set note = '彎刀' Where item_id = '27';
Update resolvent Set note = '彎刀' Where item_id = '100027';
Update resolvent Set note = '彎刀' Where item_id = '200027';
Update resolvent Set note = '銀劍' Where item_id = '25';
Update resolvent Set note = '銀劍' Where item_id = '100025';
Update resolvent Set note = '侵略者之劍' Where item_id = '32';
Update resolvent Set note = '侵略者之劍' Where item_id = '200032';
Update resolvent Set note = '長劍' Where item_id = '31';
Update resolvent Set note = '雙手劍' Where item_id = '52';
Update resolvent Set note = '雙手劍' Where item_id = '100052';
Update resolvent Set note = '雙手劍' Where item_id = '200052';
Update resolvent Set note = '三叉戟' Where item_id = '93';
Update resolvent Set note = '歐西斯之矛' Where item_id = '91';
Update resolvent Set note = '矛' Where item_id = '95';
Update resolvent Set note = '矛' Where item_id = '100095';
Update resolvent Set note = '矛' Where item_id = '96';
Update resolvent Set note = '帕提森' Where item_id = '94';
Update resolvent Set note = '法丘' Where item_id = '104';
Update resolvent Set note = '露西錘' Where item_id = '102';
Update resolvent Set note = '露西錘' Where item_id = '100102';
Update resolvent Set note = '深紅長矛' Where item_id = '107';
Update resolvent Set note = '深紅長矛' Where item_id = '100107';
Update resolvent Set note = '亞連' Where item_id = '137';
Update resolvent Set note = '斧' Where item_id = '136';
Update resolvent Set note = '木棒' Where item_id = '138';
Update resolvent Set note = '弗萊爾' Where item_id = '139';
Update resolvent Set note = '釘錘' Where item_id = '140';
Update resolvent Set note = '戰斧' Where item_id = '143';
Update resolvent Set note = '戰斧' Where item_id = '100143';
Update resolvent Set note = '狂戰士斧' Where item_id = '145';
Update resolvent Set note = '流星錘' Where item_id = '146';
Update resolvent Set note = '流星錘' Where item_id = '100146';
Update resolvent Set note = '銀斧' Where item_id = '142';
Update resolvent Set note = '巨斧' Where item_id = '148';
Update resolvent Set note = '牛人斧頭' Where item_id = '149';
Update resolvent Set note = '惡魔斧頭' Where item_id = '151';
Update resolvent Set note = '惡魔斧頭' Where item_id = '100151';
Update resolvent Set note = '橡木魔法杖' Where item_id = '128';
Update resolvent Set note = '瑪那魔杖' Where item_id = '126';
Update resolvent Set note = '神官魔杖' Where item_id = '132';
Update resolvent Set note = '神官魔杖' Where item_id = '100132';
Update resolvent Set note = '歐西斯弓' Where item_id = '171';
Update resolvent Set note = '歐西斯弓' Where item_id = '200171';
Update resolvent Set note = '弓' Where item_id = '172';
Update resolvent Set note = '弓' Where item_id = '100172';
Update resolvent Set note = '獵人之弓' Where item_id = '169';
Update resolvent Set note = '獵人之弓' Where item_id = '100169';
Update resolvent Set note = '手套' Where item_id = '20182';
Update resolvent Set note = '手套' Where item_id = '120182';
Update resolvent Set note = '皮手套' Where item_id = '20162';
Update resolvent Set note = '藍海賊手套' Where item_id = '20188';
Update resolvent Set note = '地靈手套' Where item_id = '20177';
Update resolvent Set note = '風靈手套' Where item_id = '20189';
Update resolvent Set note = '火靈手套' Where item_id = '20181';
Update resolvent Set note = '水靈手套' Where item_id = '20172';
Update resolvent Set note = '歐西斯頭盔' Where item_id = '20034';
Update resolvent Set note = '歐西斯頭盔' Where item_id = '220034';
Update resolvent Set note = '鋼盔' Where item_id = '20043';
Update resolvent Set note = '鋼盔' Where item_id = '120043';
Update resolvent Set note = '鋼盔' Where item_id = '220043';
Update resolvent Set note = '侏儒鐵盔' Where item_id = '20007';
Update resolvent Set note = '抗魔法頭盔' Where item_id = '20011';
Update resolvent Set note = '抗魔法頭盔' Where item_id = '120011';
Update resolvent Set note = '小藤甲' Where item_id = '20089';
Update resolvent Set note = '歐西斯環甲' Where item_id = '20135';
Update resolvent Set note = '歐西斯環甲' Where item_id = '220135';
Update resolvent Set note = '銀釘皮甲' Where item_id = '20147';
Update resolvent Set note = '銀釘皮甲' Where item_id = '220147';
Update resolvent Set note = '環甲' Where item_id = '20096';
Update resolvent Set note = '歐西斯鏈甲' Where item_id = '20136';
Update resolvent Set note = '歐西斯鏈甲' Where item_id = '220136';
Update resolvent Set note = '綿質長袍' Where item_id = '20114';
Update resolvent Set note = '精靈護胸金屬板' Where item_id = '20139';
Update resolvent Set note = '鱗甲' Where item_id = '20122';
Update resolvent Set note = '鱗甲' Where item_id = '220122';
Update resolvent Set note = '骷髏盔甲' Where item_id = '20124';
Update resolvent Set note = '青銅盔甲' Where item_id = '20149';
Update resolvent Set note = '青銅盔甲' Where item_id = '120149';
Update resolvent Set note = '藤甲' Where item_id = '20115';
Update resolvent Set note = '藤甲' Where item_id = '220115';
Update resolvent Set note = '皮甲' Where item_id = '20101';
Update resolvent Set note = '皮甲' Where item_id = '120101';
Update resolvent Set note = '皮甲' Where item_id = '220101';
Update resolvent Set note = '被遺忘的金屬盔甲' Where item_id = '20143';
Update resolvent Set note = '被遺忘的鱗甲' Where item_id = '20142';
Update resolvent Set note = '被遺忘的皮盔甲' Where item_id = '20140';
Update resolvent Set note = '被遺忘的長袍' Where item_id = '20141';
Update resolvent Set note = '歐西斯斗篷' Where item_id = '20072';
Update resolvent Set note = '侏儒斗篷' Where item_id = '20052';
Update resolvent Set note = '抗魔法斗篷' Where item_id = '20056';
Update resolvent Set note = '抗魔法斗篷' Where item_id = '120056';
Update resolvent Set note = '抗魔法斗篷' Where item_id = '220056';
Update resolvent Set note = '長靴' Where item_id = '20205';
Update resolvent Set note = '藍海賊長靴' Where item_id = '20217';
Update resolvent Set note = '小型身體腰帶' Where item_id = '20306';
Update resolvent Set note = '小型身體腰帶' Where item_id = '120306';
Update resolvent Set note = '小型靈魂腰帶' Where item_id = '20307';
Update resolvent Set note = '小型靈魂腰帶' Where item_id = '120307';
Update resolvent Set note = '小型精神腰帶' Where item_id = '20308';
Update resolvent Set note = '小型精神腰帶' Where item_id = '120308';
Update resolvent Set note = '身體腰帶' Where item_id = '20312';
Update resolvent Set note = '身體腰帶' Where item_id = '120312';
Update resolvent Set note = '靈魂腰帶' Where item_id = '20316';
Update resolvent Set note = '靈魂腰帶' Where item_id = '120316';
Update resolvent Set note = '精神腰帶' Where item_id = '20319';
Update resolvent Set note = '精神腰帶' Where item_id = '120319';
Update resolvent Set note = '多羅皮帶' Where item_id = '20321';
Update resolvent Set note = '多羅皮帶' Where item_id = '120321';
Update resolvent Set note = '智力項鍊' Where item_id = '20266';
Update resolvent Set note = '智力項鍊' Where item_id = '120266';
Update resolvent Set note = '妖魔戰士護身符' Where item_id = '20263';
Update resolvent Set note = '召喚控制戒指' Where item_id = '20284';
Update resolvent Set note = '治癒藥水' Where item_id = '40010';
Update resolvent Set note = '治癒藥水' Where item_id = '140010';
Update resolvent Set note = '治癒藥水' Where item_id = '240010';
Update resolvent Set note = '強力治癒藥水' Where item_id = '40011';
Update resolvent Set note = '強力治癒藥水' Where item_id = '140011';
Update resolvent Set note = '終極治癒藥水' Where item_id = '40012';
Update resolvent Set note = '終極治癒藥水' Where item_id = '140012';
Update resolvent Set note = '濃縮體力恢復劑' Where item_id = '40019';
Update resolvent Set note = '濃縮強力體力恢復劑' Where item_id = '40020';
Update resolvent Set note = '濃縮終極體力恢復劑' Where item_id = '40021';
Update resolvent Set note = '解毒藥水' Where item_id = '40017';
Update resolvent Set note = '自我加速藥水' Where item_id = '40013';
Update resolvent Set note = '自我加速藥水' Where item_id = '140013';
Update resolvent Set note = '強化 綠色藥水' Where item_id = '40018';
Update resolvent Set note = '強化 綠色藥水' Where item_id = '140018';
Update resolvent Set note = '慎重藥水' Where item_id = '40016';
Update resolvent Set note = '慎重藥水' Where item_id = '140016';
Update resolvent Set note = '勇敢藥水' Where item_id = '40014';
Update resolvent Set note = '勇敢藥水' Where item_id = '140014';
Update resolvent Set note = '加速魔力回復藥水' Where item_id = '40015';
Update resolvent Set note = '加速魔力回復藥水' Where item_id = '140015';
Update resolvent Set note = '精靈餅乾' Where item_id = '40068';
Update resolvent Set note = '精靈餅乾' Where item_id = '140068';
Update resolvent Set note = '磨刀石' Where item_id = '40317';
Update resolvent Set note = '鑑定卷軸' Where item_id = '40126';
Update resolvent Set note = '瞬間移動卷軸' Where item_id = '40100';
Update resolvent Set note = '瞬間移動卷軸' Where item_id = '140100';
Update resolvent Set note = '解除咀咒的卷軸' Where item_id = '40119';
Update resolvent Set note = '解除咀咒的卷軸' Where item_id = '140119';
Update resolvent Set note = '傳送回家的卷軸' Where item_id = '40079';
Update resolvent Set note = '復活卷軸' Where item_id = '40089';
Update resolvent Set note = '復活卷軸' Where item_id = '140089';
Update resolvent Set note = '變形卷軸' Where item_id = '40088';
Update resolvent Set note = '變形卷軸' Where item_id = '140088';
Update resolvent Set note = '空的魔法卷軸(等級1)' Where item_id = '40090';
Update resolvent Set note = '空的魔法卷軸(等級2)' Where item_id = '40091';
Update resolvent Set note = '空的魔法卷軸(等級3)' Where item_id = '40092';
Update resolvent Set note = '空的魔法卷軸(等級4)' Where item_id = '40093';
Update resolvent Set note = '空的魔法卷軸(等級5)' Where item_id = '40094';
Update resolvent Set note = '魔法書 (燃燒的火球)' Where item_id = '40170';
Update resolvent Set note = '魔法書 (通暢氣脈術)' Where item_id = '40171';
Update resolvent Set note = '魔法書 (壞物術)' Where item_id = '40172';
Update resolvent Set note = '魔法書 (吸血鬼之吻)' Where item_id = '40173';
Update resolvent Set note = '魔法書 (緩速術)' Where item_id = '40174';
Update resolvent Set note = '魔法書 (魔法屏障)' Where item_id = '40175';
Update resolvent Set note = '魔法書 (冥想術)' Where item_id = '40176';
Update resolvent Set note = '魔法書 (岩牢)' Where item_id = '40177';
Update resolvent Set note = '魔法書 (木乃伊的詛咒)' Where item_id = '40178';
Update resolvent Set note = '魔法書 (極道落雷)' Where item_id = '40179';
Update resolvent Set note = '魔法書 (高級治癒術)' Where item_id = '40180';
Update resolvent Set note = '魔法書 (迷魅術)' Where item_id = '40181';
Update resolvent Set note = '魔法書 (聖潔之光)' Where item_id = '40182';
Update resolvent Set note = '魔法書 (冰錐)' Where item_id = '40183';
Update resolvent Set note = '魔法書 (魔力奪取)' Where item_id = '40184';
Update resolvent Set note = '魔法書 (黑闇之影)' Where item_id = '40185';
Update resolvent Set note = '魔法書 (造屍術)' Where item_id = '40186';
Update resolvent Set note = '魔法書 (體魄強健術)' Where item_id = '40187';
Update resolvent Set note = '魔法書 (加速術)' Where item_id = '40188';
Update resolvent Set note = '魔法書 (魔法相消術)' Where item_id = '40189';
Update resolvent Set note = '魔法書 (地裂術)' Where item_id = '40190';
Update resolvent Set note = '魔法書 (烈炎術)' Where item_id = '40191';
Update resolvent Set note = '魔法書 (弱化術)' Where item_id = '40192';
Update resolvent Set note = '魔法書 (祝福魔法武器)' Where item_id = '40193';
Update resolvent Set note = '魔法書 (雷霆風暴)' Where item_id = '40210';
Update resolvent Set note = '魔法書 (沉睡之霧)' Where item_id = '40211';
Update resolvent Set note = '魔法書 (變形術)' Where item_id = '40212';
Update resolvent Set note = '魔法書 (聖結界)' Where item_id = '40213';
Update resolvent Set note = '魔法書 (集體傳送術)' Where item_id = '40214';
Update resolvent Set note = '魔法書 (火風暴)' Where item_id = '40215';
Update resolvent Set note = '魔法書 (藥水霜化術)' Where item_id = '40216';
Update resolvent Set note = '魔法書 (強力無所遁形術)' Where item_id = '40217';
Update resolvent Set note = '黑暗精靈水晶(暗隱術)' Where item_id = '40265';
Update resolvent Set note = '黑暗精靈水晶(附加劇毒)' Where item_id = '40266';
Update resolvent Set note = '黑暗精靈水晶(影之防護)' Where item_id = '40267';
Update resolvent Set note = '黑暗精靈水晶(提煉魔石)' Where item_id = '40268';
Update resolvent Set note = '黑暗精靈水晶(力量提升)' Where item_id = '40269';
Update resolvent Set note = '黑暗精靈水晶(行走加速)' Where item_id = '40270';
Update resolvent Set note = '黑暗精靈水晶(燃燒鬥志)' Where item_id = '40271';
Update resolvent Set note = '黑暗精靈水晶(暗黑盲咒)' Where item_id = '40272';
Update resolvent Set note = '黑暗精靈水晶(毒性抵抗)' Where item_id = '40273';
Update resolvent Set note = '黑暗精靈水晶(敏捷提升)' Where item_id = '40274';
Update resolvent Set note = '黑暗精靈水晶(雙重破壞)' Where item_id = '40275';
Update resolvent Set note = '黑暗精靈水晶(暗影閃避)' Where item_id = '40276';
Update resolvent Set note = '黑暗精靈水晶(暗影之牙)' Where item_id = '40277';
Update resolvent Set note = '黑暗精靈水晶(會心一擊)' Where item_id = '40278';
Update resolvent Set note = '黑暗精靈水晶(閃避提升)' Where item_id = '40279';
Update resolvent Set note = '技術書(衝擊之暈)' Where item_id = '40164';
Update resolvent Set note = '閃電魔杖' Where item_id = '40007';
Update resolvent Set note = '創造怪物魔杖' Where item_id = '40006';
Update resolvent Set note = '創造怪物魔杖' Where item_id = '140006';
Update resolvent Set note = '變形魔杖' Where item_id = '40008';
Update resolvent Set note = '變形魔杖' Where item_id = '140008';
Update resolvent Set note = '黑色血痕' Where item_id = '40524';
Update resolvent Set note = '元素石' Where item_id = '40515';
Update resolvent Set note = '鑽石' Where item_id = '40044';
Update resolvent Set note = '綠寶石' Where item_id = '40047';
Update resolvent Set note = '紅寶石' Where item_id = '40045';
Update resolvent Set note = '藍寶石' Where item_id = '40046';
Update resolvent Set note = '品質鑽石' Where item_id = '40048';
Update resolvent Set note = '品質綠寶石' Where item_id = '40051';
Update resolvent Set note = '品質紅寶石' Where item_id = '40049';
Update resolvent Set note = '品質藍寶石' Where item_id = '40050';
Update resolvent Set note = '粗糙的米索莉塊' Where item_id = '40496';
Update resolvent Set note = '金屬塊' Where item_id = '40408';
Update resolvent Set note = '蘑菇汁' Where item_id = '40499';
Update resolvent Set note = '黑色米索莉原石' Where item_id = '40444';
Update resolvent Set note = '黑色米索莉' Where item_id = '40443';
Update resolvent Set note = '布拉伯的胃液' Where item_id = '40442';
Update resolvent Set note = '鋼鐵原石' Where item_id = '40899';
Update resolvent Set note = '火山灰' Where item_id = '40486';
Update resolvent Set note = '精靈之淚' Where item_id = '40514';
Update resolvent Set note = '奇美拉之皮(龍)' Where item_id = '40397';
Update resolvent Set note = '奇美拉之皮(山羊)' Where item_id = '40398';
Update resolvent Set note = '奇美拉之皮(獅子)' Where item_id = '40399';
Update resolvent Set note = '奇美拉之皮(蛇)' Where item_id = '40400';
Update resolvent Set note = '深淵花枝條' Where item_id = '40437';
Update resolvent Set note = '金屬蜈蚣的皮' Where item_id = '40483';
Update resolvent Set note = '蝙蝠之牙' Where item_id = '40438';
Update resolvent Set note = '鼴鼠的皮' Where item_id = '40431';
Update resolvent Set note = '犰狳的尾巴' Where item_id = '40434';
Update resolvent Set note = '狼皮' Where item_id = '40424';
Update resolvent Set note = '黑暗元素石' Where item_id = '40490';
Update resolvent Set note = '毒蠍之皮' Where item_id = '40459';
Update resolvent Set note = '地獄犬之皮' Where item_id = '40472';
Update resolvent Set note = '巨大莫妮亞蜘蛛絲' Where item_id = '40419';
Update resolvent Set note = '污濁安特的樹枝' Where item_id = '40512';
Update resolvent Set note = '污濁安特的樹皮' Where item_id = '40510';
Update resolvent Set note = '污濁安特的水果' Where item_id = '40511';
Update resolvent Set note = '守護者之牙' Where item_id = '40986';
Update resolvent Set note = '土之守護者的尾巴' Where item_id = '40978';
Update resolvent Set note = '水之守護者的尾巴' Where item_id = '40979';
Update resolvent Set note = '火之守護者的尾巴' Where item_id = '40980';
Update resolvent Set note = '風之守護者的尾巴' Where item_id = '40981';
Update resolvent Set note = '土之守護者的皮' Where item_id = '40982';
Update resolvent Set note = '水之守護者的皮' Where item_id = '40983';
Update resolvent Set note = '火之守護者的皮' Where item_id = '40984';
Update resolvent Set note = '風之守護者的皮' Where item_id = '40985';
Update resolvent Set note = '骨頭碎片' Where item_id = '40407';
Update resolvent Set note = '黑暗妖精士兵的徽章' Where item_id = '40999';
Update resolvent Set note = '法利昂的血痕' Where item_id = '41343';
Update resolvent Set note = '阿吐巴妖魔魔法書' Where item_id = '40612';
Update resolvent Set note = '那魯加妖魔魔法書' Where item_id = '40610';
Update resolvent Set note = '都達瑪拉妖魔魔法書' Where item_id = '40611';
Update resolvent Set note = '甘地妖魔魔法書' Where item_id = '40609';
Update resolvent Set note = '大洞穴卷軸碎片' Where item_id = '40432';
Update resolvent Set note = '航海日誌第1頁' Where item_id = '41038';
Update resolvent Set note = '航海日誌第2頁' Where item_id = '41039';
Update resolvent Set note = '航海日誌第3頁' Where item_id = '41040';
Update resolvent Set note = '航海日誌第4頁' Where item_id = '41041';
Update resolvent Set note = '航海日誌第5頁' Where item_id = '41042';
Update resolvent Set note = '航海日誌第6頁' Where item_id = '41043';
Update resolvent Set note = '航海日誌第7頁' Where item_id = '41044';
Update resolvent Set note = '航海日誌第8頁' Where item_id = '41045';
Update resolvent Set note = '航海日誌第9頁' Where item_id = '41046';
Update resolvent Set note = '航海日誌第10頁' Where item_id = '41047';
Update resolvent Set note = '原住民圖騰' Where item_id = '40329';
Update resolvent Set note = '原住民圖騰' Where item_id = '140329';
Update resolvent Set note = '人魚之鱗' Where item_id = '40041';
Update resolvent Set note = '梅杜莎之血' Where item_id = '41342';
Update resolvent Set note = '少了刀刃的武器' Where item_id = '41206';
Update resolvent Set note = '靈魂石碎片' Where item_id = '40678';
Update resolvent Set note = '血石碎片' Where item_id = '40718';