UPDATE area SET	areaname = "說話之島" WHERE areaid = "1";
UPDATE area SET	areaname = "冒險洞窟 1樓" WHERE areaid = "2";
UPDATE area SET	areaname = "冒險洞窟 2樓" WHERE areaid = "3";
UPDATE area SET	areaname = "甘特之屋" WHERE areaid = "4";
UPDATE area SET	areaname = "往古魯丁的船" WHERE areaid = "5";
UPDATE area SET	areaname = "往說話之島的船" WHERE areaid = "6";
UPDATE area SET	areaname = "古魯丁地監 1樓" WHERE areaid = "7";
UPDATE area SET	areaname = "古魯丁地監 2樓" WHERE areaid = "8";
UPDATE area SET	areaname = "古魯丁地監 3樓" WHERE areaid = "9";
UPDATE area SET	areaname = "古魯丁地監 4樓" WHERE areaid = "10";
UPDATE area SET	areaname = "古魯丁地監 5樓" WHERE areaid = "11";
UPDATE area SET	areaname = "古魯丁地監 6樓" WHERE areaid = "12";
UPDATE area SET	areaname = "古魯丁地監 7樓" WHERE areaid = "13";
UPDATE area SET	areaname = "海底隧道" WHERE areaid = "14";
UPDATE area SET	areaname = "肯特內城" WHERE areaid = "15";
UPDATE area SET	areaname = "哈汀研究所" WHERE areaid = "16";
UPDATE area SET	areaname = "娜魯帕洞穴" WHERE areaid = "17";
UPDATE area SET	areaname = "都佩傑諾地監" WHERE areaid = "18";
UPDATE area SET	areaname = "眠龍洞穴 1樓" WHERE areaid = "19";
UPDATE area SET	areaname = "眠龍洞穴 2樓" WHERE areaid = "20";
UPDATE area SET	areaname = "眠龍洞穴 3樓" WHERE areaid = "21";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "22";
UPDATE area SET	areaname = "風木城地監 1樓" WHERE areaid = "23";
UPDATE area SET	areaname = "風木城地監 1樓" WHERE areaid = "24";
UPDATE area SET	areaname = "騎士洞穴 1樓" WHERE areaid = "25";
UPDATE area SET	areaname = "騎士洞穴 2樓" WHERE areaid = "26";
UPDATE area SET	areaname = "騎士洞穴 3樓" WHERE areaid = "27";
UPDATE area SET	areaname = "騎士洞穴 4樓" WHERE areaid = "28";
UPDATE area SET	areaname = "風木城內城" WHERE areaid = "29";
UPDATE area SET	areaname = "龍之谷地監 1樓" WHERE areaid = "30";
UPDATE area SET	areaname = "龍之谷地監 2樓" WHERE areaid = "31";
UPDATE area SET	areaname = "龍之谷地監 3樓" WHERE areaid = "32";
UPDATE area SET	areaname = "龍之谷地監 4樓" WHERE areaid = "33";
UPDATE area SET	areaname = "龍之谷地監 5樓" WHERE areaid = "34";
UPDATE area SET	areaname = "龍之谷地監 6樓" WHERE areaid = "35";
UPDATE area SET	areaname = "安塔瑞斯棲息地" WHERE areaid = "36";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "37";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "38";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "39";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "40";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "41";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "42";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "43";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "44";
UPDATE area SET	areaname = "巨蟻洞穴" WHERE areaid = "45";
UPDATE area SET	areaname = "奇岩內城" WHERE areaid = "46";
UPDATE area SET	areaname = "奇岩地監 1樓" WHERE areaid = "47";
UPDATE area SET	areaname = "奇岩地監 2樓" WHERE areaid = "48";
UPDATE area SET	areaname = "奇岩地監 3樓" WHERE areaid = "49";
UPDATE area SET	areaname = "奇岩地監 4樓" WHERE areaid = "50";
UPDATE area SET	areaname = "歌唱之島" WHERE areaid = "51";
UPDATE area SET	areaname = "隱藏之谷" WHERE areaid = "52";
UPDATE area SET	areaname = "海音地監 1樓" WHERE areaid = "53";
UPDATE area SET	areaname = "海音地監 2樓" WHERE areaid = "54";
UPDATE area SET	areaname = "海音地監 3樓" WHERE areaid = "55";
UPDATE area SET	areaname = "伊娃神殿" WHERE areaid = "56";
UPDATE area SET	areaname = "海音地監 4樓" WHERE areaid = "57";
UPDATE area SET	areaname = "海音內城" WHERE areaid = "58";
UPDATE area SET	areaname = "法利昂棲息地" WHERE areaid = "59";
UPDATE area SET	areaname = "侏儒洞穴" WHERE areaid = "60";
UPDATE area SET	areaname = "巴拉卡斯棲息地" WHERE areaid = "61";
UPDATE area SET	areaname = "歌唱之島" WHERE areaid = "62";
UPDATE area SET	areaname = "隱藏之谷" WHERE areaid = "63";
UPDATE area SET	areaname = "林德拜爾棲息地" WHERE areaid = "64";
UPDATE area SET	areaname = "遺忘之島" WHERE areaid = "65";
UPDATE area SET	areaname = "水晶洞穴 1樓" WHERE areaid = "66";
UPDATE area SET	areaname = "水晶洞穴 2樓" WHERE areaid = "67";
UPDATE area SET	areaname = "水晶洞穴 3樓" WHERE areaid = "68";
UPDATE area SET	areaname = "象牙塔 1樓" WHERE areaid = "69";
UPDATE area SET	areaname = "象牙塔 2樓" WHERE areaid = "70";
UPDATE area SET	areaname = "象牙塔 3樓" WHERE areaid = "71";
UPDATE area SET	areaname = "象牙塔 4樓" WHERE areaid = "72";
UPDATE area SET	areaname = "象牙塔 5樓" WHERE areaid = "73";
UPDATE area SET	areaname = "象牙塔 6樓" WHERE areaid = "74";
UPDATE area SET	areaname = "象牙塔 7樓" WHERE areaid = "75";
UPDATE area SET	areaname = "象牙塔 8樓" WHERE areaid = "76";
UPDATE area SET	areaname = "往遺忘之島的船" WHERE areaid = "77";
UPDATE area SET	areaname = "往海音的船" WHERE areaid = "78";
UPDATE area SET	areaname = "歌唱之島地監" WHERE areaid = "79";
UPDATE area SET	areaname = "隱藏之谷地監" WHERE areaid = "80";
UPDATE area SET	areaname = "帕古洞穴" WHERE areaid = "81";
UPDATE area SET	areaname = "奇岩競技場" WHERE areaid = "82";
UPDATE area SET	areaname = "奇岩競技場" WHERE areaid = "83";
UPDATE area SET	areaname = "奇岩競技場" WHERE areaid = "84";
UPDATE area SET	areaname = "說話之島競技場" WHERE areaid = "85";
UPDATE area SET	areaname = "古魯丁競技場" WHERE areaid = "86";
UPDATE area SET	areaname = "肯特競技場" WHERE areaid = "87";
UPDATE area SET	areaname = "風木競技場" WHERE areaid = "88";
UPDATE area SET	areaname = "銀騎士競技場" WHERE areaid = "89";
UPDATE area SET	areaname = "巴拉卡斯之窟競技場" WHERE areaid = "90";
UPDATE area SET	areaname = "海音競技場" WHERE areaid = "91";
UPDATE area SET	areaname = "威頓競技場" WHERE areaid = "92";
UPDATE area SET	areaname = "管理者房間" WHERE areaid = "93";
UPDATE area SET	areaname = "傲慢之塔 1樓" WHERE areaid = "94";
UPDATE area SET	areaname = "傲慢之塔 2樓" WHERE areaid = "95";
UPDATE area SET	areaname = "傲慢之塔 3樓" WHERE areaid = "96";
UPDATE area SET	areaname = "傲慢之塔 4樓" WHERE areaid = "97";
UPDATE area SET	areaname = "傲慢之塔 5樓" WHERE areaid = "98";
UPDATE area SET	areaname = "傲慢之塔 6樓" WHERE areaid = "99";
UPDATE area SET	areaname = "傲慢之塔 7樓" WHERE areaid = "100";
UPDATE area SET	areaname = "傲慢之塔 8樓" WHERE areaid = "101";
UPDATE area SET	areaname = "傲慢之塔 9樓" WHERE areaid = "102";
UPDATE area SET	areaname = "傲慢之塔 10樓" WHERE areaid = "103";
UPDATE area SET	areaname = "傲慢之塔 11樓" WHERE areaid = "104";
UPDATE area SET	areaname = "傲慢之塔 12樓" WHERE areaid = "105";
UPDATE area SET	areaname = "傲慢之塔 13樓" WHERE areaid = "106";
UPDATE area SET	areaname = "傲慢之塔 14樓" WHERE areaid = "107";
UPDATE area SET	areaname = "傲慢之塔 15樓" WHERE areaid = "108";
UPDATE area SET	areaname = "傲慢之塔 16樓" WHERE areaid = "109";
UPDATE area SET	areaname = "傲慢之塔 17樓" WHERE areaid = "110";
UPDATE area SET	areaname = "傲慢之塔 18樓" WHERE areaid = "111";
UPDATE area SET	areaname = "傲慢之塔 19樓" WHERE areaid = "112";
UPDATE area SET	areaname = "傲慢之塔 20樓" WHERE areaid = "113";
UPDATE area SET	areaname = "傲慢之塔 21樓" WHERE areaid = "114";
UPDATE area SET	areaname = "傲慢之塔 22樓" WHERE areaid = "115";
UPDATE area SET	areaname = "傲慢之塔 23樓" WHERE areaid = "116";
UPDATE area SET	areaname = "傲慢之塔 24樓" WHERE areaid = "117";
UPDATE area SET	areaname = "傲慢之塔 25樓" WHERE areaid = "118";
UPDATE area SET	areaname = "傲慢之塔 26樓" WHERE areaid = "119";
UPDATE area SET	areaname = "傲慢之塔 27樓" WHERE areaid = "120";
UPDATE area SET	areaname = "傲慢之塔 28樓" WHERE areaid = "121";
UPDATE area SET	areaname = "傲慢之塔 29樓" WHERE areaid = "122";
UPDATE area SET	areaname = "傲慢之塔 30樓" WHERE areaid = "123";
UPDATE area SET	areaname = "傲慢之塔 31樓" WHERE areaid = "124";
UPDATE area SET	areaname = "傲慢之塔 32樓" WHERE areaid = "125";
UPDATE area SET	areaname = "傲慢之塔 33樓" WHERE areaid = "126";
UPDATE area SET	areaname = "傲慢之塔 34樓" WHERE areaid = "127";
UPDATE area SET	areaname = "傲慢之塔 35樓" WHERE areaid = "128";
UPDATE area SET	areaname = "傲慢之塔 36樓" WHERE areaid = "129";
UPDATE area SET	areaname = "傲慢之塔 37樓" WHERE areaid = "130";
UPDATE area SET	areaname = "傲慢之塔 38樓" WHERE areaid = "131";
UPDATE area SET	areaname = "傲慢之塔 39樓" WHERE areaid = "132";
UPDATE area SET	areaname = "傲慢之塔 40樓" WHERE areaid = "133";
UPDATE area SET	areaname = "傲慢之塔 41樓" WHERE areaid = "134";
UPDATE area SET	areaname = "傲慢之塔 42樓" WHERE areaid = "135";
UPDATE area SET	areaname = "傲慢之塔 43樓" WHERE areaid = "136";
UPDATE area SET	areaname = "傲慢之塔 44樓" WHERE areaid = "137";
UPDATE area SET	areaname = "傲慢之塔 45樓" WHERE areaid = "138";
UPDATE area SET	areaname = "傲慢之塔 46樓" WHERE areaid = "139";
UPDATE area SET	areaname = "傲慢之塔 47樓" WHERE areaid = "140";
UPDATE area SET	areaname = "傲慢之塔 48樓" WHERE areaid = "141";
UPDATE area SET	areaname = "傲慢之塔 49樓" WHERE areaid = "142";
UPDATE area SET	areaname = "傲慢之塔 50樓" WHERE areaid = "143";
UPDATE area SET	areaname = "傲慢之塔 51樓" WHERE areaid = "144";
UPDATE area SET	areaname = "傲慢之塔 52樓" WHERE areaid = "145";
UPDATE area SET	areaname = "傲慢之塔 53樓" WHERE areaid = "146";
UPDATE area SET	areaname = "傲慢之塔 54樓" WHERE areaid = "147";
UPDATE area SET	areaname = "傲慢之塔 55樓" WHERE areaid = "148";
UPDATE area SET	areaname = "傲慢之塔 56樓" WHERE areaid = "149";
UPDATE area SET	areaname = "傲慢之塔 57樓" WHERE areaid = "150";
UPDATE area SET	areaname = "傲慢之塔 58樓" WHERE areaid = "151";
UPDATE area SET	areaname = "傲慢之塔 59樓" WHERE areaid = "152";
UPDATE area SET	areaname = "傲慢之塔 60樓" WHERE areaid = "153";
UPDATE area SET	areaname = "傲慢之塔 61樓" WHERE areaid = "154";
UPDATE area SET	areaname = "傲慢之塔 62樓" WHERE areaid = "155";
UPDATE area SET	areaname = "傲慢之塔 63樓" WHERE areaid = "156";
UPDATE area SET	areaname = "傲慢之塔 64樓" WHERE areaid = "157";
UPDATE area SET	areaname = "傲慢之塔 65樓" WHERE areaid = "158";
UPDATE area SET	areaname = "傲慢之塔 66樓" WHERE areaid = "159";
UPDATE area SET	areaname = "傲慢之塔 67樓" WHERE areaid = "160";
UPDATE area SET	areaname = "傲慢之塔 68樓" WHERE areaid = "161";
UPDATE area SET	areaname = "傲慢之塔 69樓" WHERE areaid = "162";
UPDATE area SET	areaname = "傲慢之塔 70樓" WHERE areaid = "163";
UPDATE area SET	areaname = "傲慢之塔 71樓" WHERE areaid = "164";
UPDATE area SET	areaname = "傲慢之塔 72樓" WHERE areaid = "165";
UPDATE area SET	areaname = "傲慢之塔 73樓" WHERE areaid = "166";
UPDATE area SET	areaname = "傲慢之塔 74樓" WHERE areaid = "167";
UPDATE area SET	areaname = "傲慢之塔 75樓" WHERE areaid = "168";
UPDATE area SET	areaname = "傲慢之塔 76樓" WHERE areaid = "169";
UPDATE area SET	areaname = "傲慢之塔 77樓" WHERE areaid = "170";
UPDATE area SET	areaname = "傲慢之塔 78樓" WHERE areaid = "171";
UPDATE area SET	areaname = "傲慢之塔 79樓" WHERE areaid = "172";
UPDATE area SET	areaname = "傲慢之塔 80樓" WHERE areaid = "173";
UPDATE area SET	areaname = "傲慢之塔 81樓" WHERE areaid = "174";
UPDATE area SET	areaname = "傲慢之塔 82樓" WHERE areaid = "175";
UPDATE area SET	areaname = "傲慢之塔 83樓" WHERE areaid = "176";
UPDATE area SET	areaname = "傲慢之塔 84樓" WHERE areaid = "177";
UPDATE area SET	areaname = "傲慢之塔 85樓" WHERE areaid = "178";
UPDATE area SET	areaname = "傲慢之塔 86樓" WHERE areaid = "179";
UPDATE area SET	areaname = "傲慢之塔 87樓" WHERE areaid = "180";
UPDATE area SET	areaname = "傲慢之塔 88樓" WHERE areaid = "181";
UPDATE area SET	areaname = "傲慢之塔 89樓" WHERE areaid = "182";
UPDATE area SET	areaname = "傲慢之塔 90樓" WHERE areaid = "183";
UPDATE area SET	areaname = "傲慢之塔 91樓" WHERE areaid = "184";
UPDATE area SET	areaname = "傲慢之塔 92樓" WHERE areaid = "185";
UPDATE area SET	areaname = "傲慢之塔 93樓" WHERE areaid = "186";
UPDATE area SET	areaname = "傲慢之塔 94樓" WHERE areaid = "187";
UPDATE area SET	areaname = "傲慢之塔 95樓" WHERE areaid = "188";
UPDATE area SET	areaname = "傲慢之塔 96樓" WHERE areaid = "189";
UPDATE area SET	areaname = "傲慢之塔 97樓" WHERE areaid = "190";
UPDATE area SET	areaname = "傲慢之塔 98樓" WHERE areaid = "191";
UPDATE area SET	areaname = "傲慢之塔 99樓" WHERE areaid = "192";
UPDATE area SET	areaname = "傲慢之塔 100樓" WHERE areaid = "193";
UPDATE area SET	areaname = "法師試練地監" WHERE areaid = "194";
UPDATE area SET	areaname = "法師試練地監" WHERE areaid = "195";
UPDATE area SET	areaname = "法師試練地監" WHERE areaid = "196";
UPDATE area SET	areaname = "法師試練地監" WHERE areaid = "197";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "198";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "199";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "200";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "201";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "202";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "203";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "204";
UPDATE area SET	areaname = "黑暗妖精地監" WHERE areaid = "205";
UPDATE area SET	areaname = "變種巨蟻地監" WHERE areaid = "206";
UPDATE area SET	areaname = "變種巨蟻地監" WHERE areaid = "207";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "208";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "209";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "210";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "211";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "212";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "213";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "214";
UPDATE area SET	areaname = "傑瑞德的試煉地監" WHERE areaid = "215";
UPDATE area SET	areaname = "吉姆的密室" WHERE areaid = "216";
UPDATE area SET	areaname = "亞丁內城" WHERE areaid = "217";
UPDATE area SET	areaname = "傲慢之塔地下水路" WHERE areaid = "218";
UPDATE area SET	areaname = "賽菲亞地監" WHERE areaid = "219";
UPDATE area SET	areaname = "夢幻之島" WHERE areaid = "220";
UPDATE area SET	areaname = "沉默洞穴" WHERE areaid = "221";
UPDATE area SET	areaname = "布魯迪卡洞穴" WHERE areaid = "222";
UPDATE area SET	areaname = "黑暗妖精試練地監" WHERE areaid = "223";
UPDATE area SET	areaname = "拉斯塔巴德地下洞穴 1樓" WHERE areaid = "224";
UPDATE area SET	areaname = "拉斯塔巴德地下洞穴 2樓" WHERE areaid = "225";
UPDATE area SET	areaname = "拉斯塔巴德地下洞穴 3樓" WHERE areaid = "226";
UPDATE area SET	areaname = "地獄" WHERE areaid = "227";
UPDATE area SET	areaname = "古代人空間 1樓" WHERE areaid = "228";
UPDATE area SET	areaname = "古代人空間 2樓" WHERE areaid = "229";
UPDATE area SET	areaname = "古代人空間 3樓" WHERE areaid = "230";
UPDATE area SET	areaname = "古代人空間 4樓" WHERE areaid = "231";
UPDATE area SET	areaname = "妖魔森林" WHERE areaid = "232";
UPDATE area SET	areaname = "古魯丁" WHERE areaid = "233";
UPDATE area SET	areaname = "風木" WHERE areaid = "234";
UPDATE area SET	areaname = "妖森" WHERE areaid = "235";
UPDATE area SET	areaname = "肯特" WHERE areaid = "236";
UPDATE area SET	areaname = "肯特" WHERE areaid = "237";
UPDATE area SET	areaname = "銀騎士村莊" WHERE areaid = "238";
UPDATE area SET	areaname = "銀騎士村莊" WHERE areaid = "239";
UPDATE area SET	areaname = "龍之谷" WHERE areaid = "240";
UPDATE area SET	areaname = "火龍窟" WHERE areaid = "241";
UPDATE area SET	areaname = "威頓" WHERE areaid = "242";
UPDATE area SET	areaname = "奇岩" WHERE areaid = "243";
UPDATE area SET	areaname = "奇岩" WHERE areaid = "244";
UPDATE area SET	areaname = "海音" WHERE areaid = "245";
UPDATE area SET	areaname = "歐瑞" WHERE areaid = "246";
UPDATE area SET	areaname = "歐瑞" WHERE areaid = "247";
UPDATE area SET	areaname = "亞丁" WHERE areaid = "248";
UPDATE area SET	areaname = "亞丁" WHERE areaid = "249";
UPDATE area SET	areaname = "旅館" WHERE areaid = "250";
UPDATE area SET	areaname = "古魯丁商店村" WHERE areaid = "251";
UPDATE area SET	areaname = "奇岩商店村" WHERE areaid = "252";
UPDATE area SET	areaname = "歐瑞商店村" WHERE areaid = "253";
UPDATE area SET	areaname = "銀騎士商店村" WHERE areaid = "254";
UPDATE area SET	areaname = "歐姆地監" WHERE areaid = "255";
UPDATE area SET	areaname = "狄亞得要塞" WHERE areaid = "256";
UPDATE area SET	areaname = "礦物洞穴" WHERE areaid = "257";
UPDATE area SET	areaname = "肯特城地監 1樓" WHERE areaid = "258";
UPDATE area SET	areaname = "肯特城地監 2樓" WHERE areaid = "259";
UPDATE area SET	areaname = "肯特城地監 3樓" WHERE areaid = "260";
UPDATE area SET	areaname = "肯特城地監 4樓" WHERE areaid = "261";
UPDATE area SET	areaname = "古代巨人之墓" WHERE areaid = "262";
UPDATE area SET	areaname = "古代巨人之墓" WHERE areaid = "263";
UPDATE area SET	areaname = "古代巨人之墓" WHERE areaid = "264";
UPDATE area SET	areaname = "大洞穴抵抗軍地區" WHERE areaid = "265";
UPDATE area SET	areaname = "大洞穴抵抗軍地區" WHERE areaid = "266";
UPDATE area SET	areaname = "大洞穴抵抗軍地區" WHERE areaid = "267";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "268";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "269";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "270";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "271";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "272";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "273";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "274";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "275";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "276";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "277";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "278";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "279";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "280";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "281";
UPDATE area SET	areaname = "大洞穴抵抗軍地區" WHERE areaid = "282";
UPDATE area SET	areaname = "大洞穴抵抗軍地區" WHERE areaid = "283";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "284";
UPDATE area SET	areaname = "大洞穴隱遁者地區" WHERE areaid = "285";
UPDATE area SET	areaname = "魔族神殿" WHERE areaid = "286";
UPDATE area SET	areaname = "地底湖" WHERE areaid = "287";
UPDATE area SET	areaname = "精靈墓穴" WHERE areaid = "288";
UPDATE area SET	areaname = "海賊島" WHERE areaid = "289";
UPDATE area SET	areaname = "海賊島地監 1樓" WHERE areaid = "290";
UPDATE area SET	areaname = "海賊島地監 2樓" WHERE areaid = "291";
UPDATE area SET	areaname = "海賊島地監 3樓" WHERE areaid = "292";
UPDATE area SET	areaname = "海賊島地監 4樓" WHERE areaid = "293";
UPDATE area SET	areaname = "隱藏之港" WHERE areaid = "294";
UPDATE area SET	areaname = "往隱藏之港的船" WHERE areaid = "295";
UPDATE area SET	areaname = "往海賊島的船" WHERE areaid = "296";
UPDATE area SET	areaname = "拉斯塔巴德正門" WHERE areaid = "297";
UPDATE area SET	areaname = "1樓 集會場" WHERE areaid = "298";
UPDATE area SET	areaname = "1樓 突擊隊訓練場" WHERE areaid = "299";
UPDATE area SET	areaname = "1樓 魔獸君王之室" WHERE areaid = "300";
UPDATE area SET	areaname = "1樓 魔獸調教場" WHERE areaid = "301";
UPDATE area SET	areaname = "1樓 魔獸訓練場" WHERE areaid = "302";
UPDATE area SET	areaname = "1樓 魔獸召喚室" WHERE areaid = "303";
UPDATE area SET	areaname = "1樓 黑暗結界" WHERE areaid = "304";
UPDATE area SET	areaname = "2樓 黑魔法修練場" WHERE areaid = "305";
UPDATE area SET	areaname = "2樓 黑魔法研究室" WHERE areaid = "306";
UPDATE area SET	areaname = "2樓 法令軍王之室" WHERE areaid = "307";
UPDATE area SET	areaname = "2樓 法令軍王的書房" WHERE areaid = "308";
UPDATE area SET	areaname = "2樓 暗黑精靈召喚室" WHERE areaid = "309";
UPDATE area SET	areaname = "2樓 暗黑精靈棲息地" WHERE areaid = "310";
UPDATE area SET	areaname = "2樓 暗黑精靈研究室" WHERE areaid = "311";
UPDATE area SET	areaname = "2樓 黑暗結界" WHERE areaid = "312";
UPDATE area SET	areaname = "2樓 黑暗結界" WHERE areaid = "313";
UPDATE area SET	areaname = "3樓 惡靈祭壇" WHERE areaid = "314";
UPDATE area SET	areaname = "3樓 惡靈之主祭壇" WHERE areaid = "315";
UPDATE area SET	areaname = "3樓 傭兵訓練場" WHERE areaid = "316";
UPDATE area SET	areaname = "3樓 冥法軍訓練場" WHERE areaid = "317";
UPDATE area SET	areaname = "3樓 歐姆實驗室" WHERE areaid = "318";
UPDATE area SET	areaname = "3樓 冥法軍王之室" WHERE areaid = "319";
UPDATE area SET	areaname = "3樓 中央控制室" WHERE areaid = "320";
UPDATE area SET	areaname = "3樓 惡靈之主傭兵室" WHERE areaid = "321";
UPDATE area SET	areaname = "3樓 控制室走廊" WHERE areaid = "322";
UPDATE area SET	areaname = "地下訓練場" WHERE areaid = "323";
UPDATE area SET	areaname = "地下通道" WHERE areaid = "324";
UPDATE area SET	areaname = "暗殺軍王之室" WHERE areaid = "325";
UPDATE area SET	areaname = "地下控制室" WHERE areaid = "326";
UPDATE area SET	areaname = "地下處刑場" WHERE areaid = "327";
UPDATE area SET	areaname = "地下競技場" WHERE areaid = "328";
UPDATE area SET	areaname = "地下監獄" WHERE areaid = "329";
UPDATE area SET	areaname = "海賊島" WHERE areaid = "330";
UPDATE area SET	areaname = "卡蜜拉的房間" WHERE areaid = "331";
UPDATE area SET	areaname = "混沌的大戰" WHERE areaid = "332";
UPDATE area SET	areaname = "福朗克的迷宮" WHERE areaid = "333";
UPDATE area SET	areaname = "迪哥的廢棄監獄" WHERE areaid = "334";
UPDATE area SET	areaname = "豪勢的地監" WHERE areaid = "335";
UPDATE area SET	areaname = "暗影神殿外圍" WHERE areaid = "336";
UPDATE area SET	areaname = "暗影神殿 1樓" WHERE areaid = "337";
UPDATE area SET	areaname = "暗影神殿 2樓" WHERE areaid = "338";
UPDATE area SET	areaname = "暗影神殿 3樓" WHERE areaid = "339";
UPDATE area SET	areaname = "歌唱之島" WHERE areaid = "340";
UPDATE area SET	areaname = "歌唱之島西邊地區" WHERE areaid = "341";
UPDATE area SET	areaname = "Doromond\'s Room" WHERE areaid = "342";
UPDATE area SET	areaname = "訓練之房" WHERE areaid = "343";
UPDATE area SET	areaname = "歌唱之島北邊地區" WHERE areaid = "344";
UPDATE area SET	areaname = "日本活動地圖櫻花森林" WHERE areaid = "345";
UPDATE area SET	areaname = "汙濁之地" WHERE areaid = "346";
UPDATE area SET	areaname = "奇岩城地監 1樓" WHERE areaid = "347";
UPDATE area SET	areaname = "奇岩城地監 2樓" WHERE areaid = "348";
UPDATE area SET	areaname = "奇岩城地監 3樓" WHERE areaid = "349";
UPDATE area SET	areaname = "奇岩城地監 4樓" WHERE areaid = "350";
UPDATE area SET	areaname = "海音城地監 1樓" WHERE areaid = "351";
UPDATE area SET	areaname = "海音城地監 2樓" WHERE areaid = "352";
UPDATE area SET	areaname = "海音城地監 3樓" WHERE areaid = "353";
UPDATE area SET	areaname = "廢棄的礦坑" WHERE areaid = "354";
UPDATE area SET	areaname = "廢棄的礦坑古道" WHERE areaid = "355";
UPDATE area SET	areaname = "亞丁城地監 1樓" WHERE areaid = "356";
UPDATE area SET	areaname = "亞丁城地監 2樓" WHERE areaid = "357";
UPDATE area SET	areaname = "亞丁城地監 3樓" WHERE areaid = "358";
UPDATE area SET	areaname = "3樓 黑暗結界" WHERE areaid = "359";
UPDATE area SET	areaname = "4樓 格蘭肯神殿、長老．琪娜之室" WHERE areaid = "360";
UPDATE area SET	areaname = "4樓 長老．巴塔斯之室、長老．安迪斯之室" WHERE areaid = "361";
UPDATE area SET	areaname = "4樓 庭園廣場、長老．泰瑪斯之室" WHERE areaid = "362";
UPDATE area SET	areaname = "4樓 長老．泰瑪斯之室、長老．拉曼斯之室、長老．巴陸德之室" WHERE areaid = "363";
UPDATE area SET	areaname = "4樓 長老會議廳、副神官．卡山德拉之室、真．冥皇丹特斯之室" WHERE areaid = "364";
UPDATE area SET	areaname = "黑暗妖精聖地" WHERE areaid = "365";
UPDATE area SET	areaname = "船舶之墓 海面" WHERE areaid = "366";
UPDATE area SET	areaname = "船舶之墓 船艙 1F-1" WHERE areaid = "367";
UPDATE area SET	areaname = "船舶之墓 船艙 1F-2" WHERE areaid = "368";
UPDATE area SET	areaname = "船舶之墓 船艙 1F-3" WHERE areaid = "369";
UPDATE area SET	areaname = "船舶之墓 船艙 2F-1" WHERE areaid = "370";
UPDATE area SET	areaname = "船舶之墓 船艙 2F-2" WHERE areaid = "371";
UPDATE area SET	areaname = "船舶之墓 船艙 2F-3" WHERE areaid = "372";
UPDATE area SET	areaname = "船舶之墓 船艙 3F" WHERE areaid = "373";
UPDATE area SET	areaname = "船舶之墓 深海" WHERE areaid = "374";
UPDATE area SET	areaname = "慾望洞穴入口" WHERE areaid = "375";
UPDATE area SET	areaname = "慾望洞穴大廳" WHERE areaid = "376";
UPDATE area SET	areaname = "炎魔謁見所" WHERE areaid = "377";
UPDATE area SET	areaname = "炎魔房間" WHERE areaid = "378";
UPDATE area SET	areaname = "水之領域" WHERE areaid = "379";
UPDATE area SET	areaname = "火之領域" WHERE areaid = "380";
UPDATE area SET	areaname = "風之領域" WHERE areaid = "381";
UPDATE area SET	areaname = "地之領域" WHERE areaid = "382";
UPDATE area SET	areaname = "火焰之影實驗室" WHERE areaid = "383";
UPDATE area SET	areaname = "不死魔族拋棄之地" WHERE areaid = "384";
UPDATE area SET	areaname = "原生魔族拋棄之地" WHERE areaid = "385";
UPDATE area SET	areaname = "原生魔族拋棄之地" WHERE areaid = "386";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "387";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "388";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "389";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "390";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "391";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "392";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "393";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "394";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "395";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "396";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "397";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "398";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "399";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "400";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "401";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "402";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "403";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "404";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "405";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "406";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "407";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "408";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "409";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "410";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "411";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "412";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "413";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "414";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "415";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "416";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "417";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "418";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "419";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "420";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "421";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "422";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "423";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "424";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "425";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "426";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "427";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "428";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "429";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "430";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "431";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "432";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "433";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "434";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "435";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "436";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "437";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "438";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "439";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "440";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "441";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "442";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "443";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "444";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "445";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "446";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "447";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "448";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "449";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "450";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "451";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "452";
UPDATE area SET	areaname = "亞丁地下盟屋" WHERE areaid = "453";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "454";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "455";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "456";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "457";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "458";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "459";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "460";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "461";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "462";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "463";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "464";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "465";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "466";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "467";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "468";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "469";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "470";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "471";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "472";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "473";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "474";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "475";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "476";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "477";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "478";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "479";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "480";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "481";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "482";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "483";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "484";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "485";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "486";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "487";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "488";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "489";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "490";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "491";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "492";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "493";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "494";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "495";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "496";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "497";
UPDATE area SET	areaname = "奇岩地下盟屋" WHERE areaid = "498";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "499";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "500";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "501";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "502";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "503";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "504";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "505";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "506";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "507";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "508";
UPDATE area SET	areaname = "海音地下盟屋" WHERE areaid = "509";
UPDATE area SET	areaname = "釣魚池" WHERE areaid = "510";
UPDATE area SET	areaname = "寵物競賽場地" WHERE areaid = "511";
UPDATE area SET	areaname = "寵物競賽場地" WHERE areaid = "512";
UPDATE area SET	areaname = "寵物競賽場地" WHERE areaid = "513";
UPDATE area SET	areaname = "寵物競賽場地" WHERE areaid = "514";
UPDATE area SET	areaname = "寵物競賽場地" WHERE areaid = "515";
UPDATE area SET	areaname = "幽靈之家" WHERE areaid = "516";
UPDATE area SET	areaname = "底比斯沙漠" WHERE areaid = "780";
UPDATE area SET	areaname = "底比斯金字塔內部" WHERE areaid = "781";
UPDATE area SET	areaname = "底比斯歐西里斯祭壇" WHERE areaid = "782";
UPDATE area SET	areaname = "希培利亞" WHERE areaid = "1000";
UPDATE area SET	areaname = "貝希摩斯" WHERE areaid = "1001";
UPDATE area SET	areaname = "日本活動地圖櫻花森林" WHERE areaid = "2000";
UPDATE area SET	areaname = "日本活動地圖訓練營地" WHERE areaid = "2001";
UPDATE area SET	areaname = "日本活動地圖果子森林" WHERE areaid = "2002";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2003";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2004";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2005";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2006";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2007";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2008";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2009";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2010";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2011";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2012";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2013";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2014";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2015";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2016";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2017";
UPDATE area SET	areaname = "追憶之島" WHERE areaid = "2018";
UPDATE area SET	areaname = "韓國活動地圖" WHERE areaid = "2019";
UPDATE area SET	areaname = "台灣活動地圖隱藏之谷" WHERE areaid = "2020";
UPDATE area SET	areaname = "台灣活動地圖隱藏之谷" WHERE areaid = "2021";
UPDATE area SET	areaname = "台灣活動地圖隱藏之谷" WHERE areaid = "2022";
UPDATE area SET	areaname = "台灣活動地圖隱藏之谷" WHERE areaid = "2023";
UPDATE area SET	areaname = "台灣活動地圖隱藏之谷" WHERE areaid = "2024";
UPDATE area SET	areaname = "日本活動地圖活動森林" WHERE areaid = "2025";
UPDATE area SET	areaname = "日本活動地圖地獄" WHERE areaid = "2026";
UPDATE area SET	areaname = "日本活動地圖罪惡神殿" WHERE areaid = "2027";
UPDATE area SET	areaname = "日本活動地圖罪惡神殿" WHERE areaid = "2028";
UPDATE area SET	areaname = "日本活動地圖罪惡神殿" WHERE areaid = "2029";
UPDATE area SET	areaname = "日本活動地圖罪惡神殿" WHERE areaid = "2030";
UPDATE area SET	areaname = "日本活動地圖罪惡神殿" WHERE areaid = "2031";
UPDATE area SET	areaname = "日本活動地圖罪惡墳墓" WHERE areaid = "2032";
UPDATE area SET	areaname = "日本活動地圖罪惡墳墓" WHERE areaid = "2033";
UPDATE area SET	areaname = "日本活動地圖罪惡墳墓" WHERE areaid = "2034";
UPDATE area SET	areaname = "日本活動地圖罪惡墳墓" WHERE areaid = "2035";
UPDATE area SET	areaname = "日本活動地圖罪惡墳墓" WHERE areaid = "2036";
UPDATE area SET	areaname = "日本活動地圖活動森林" WHERE areaid = "2037";
UPDATE area SET	areaname = "日本活動地圖活動森林" WHERE areaid = "2038";
UPDATE area SET	areaname = "日本活動地圖活動森林" WHERE areaid = "2039";
UPDATE area SET	areaname = "日本活動地圖活動森林" WHERE areaid = "2040";
UPDATE area SET	areaname = "日本活動地圖活動森林" WHERE areaid = "2041";
