/*
 * 中文化 mapids 資料表
 * By Impreza8837
 */
UPDATE mapids SET locationname = "說話之島" WHERE mapid = "0";
UPDATE mapids SET locationname = "冒險洞窟:1樓" WHERE mapid = "1";
UPDATE mapids SET locationname = "冒險洞窟:2樓" WHERE mapid = "2";
UPDATE mapids SET locationname = "甘特之家" WHERE mapid = "3";
UPDATE mapids SET locationname = "フィールド" WHERE mapid = "4";
UPDATE mapids SET locationname = "往古魯丁的船" WHERE mapid = "5";
UPDATE mapids SET locationname = "往說話之島的船" WHERE mapid = "6";
UPDATE mapids SET locationname = "古魯丁地監:1樓" WHERE mapid = "7";
UPDATE mapids SET locationname = "古魯丁地監:2樓" WHERE mapid = "8";
UPDATE mapids SET locationname = "古魯丁地監:3樓" WHERE mapid = "9";
UPDATE mapids SET locationname = "古魯丁地監:4樓" WHERE mapid = "10";
UPDATE mapids SET locationname = "古魯丁地監:5樓" WHERE mapid = "11";
UPDATE mapids SET locationname = "古魯丁地監:6樓" WHERE mapid = "12";
UPDATE mapids SET locationname = "古魯丁地監:7樓" WHERE mapid = "13";
UPDATE mapids SET locationname = "海底隧道" WHERE mapid = "14";
UPDATE mapids SET locationname = "肯特內城" WHERE mapid = "15";
UPDATE mapids SET locationname = "哈汀研究所" WHERE mapid = "16";
UPDATE mapids SET locationname = "娜魯帕洞穴" WHERE mapid = "17";
UPDATE mapids SET locationname = "都佩傑諾地監" WHERE mapid = "18";
UPDATE mapids SET locationname = "眠龍洞穴:1樓" WHERE mapid = "19";
UPDATE mapids SET locationname = "眠龍洞穴:2樓" WHERE mapid = "20";
UPDATE mapids SET locationname = "眠龍洞穴:3樓" WHERE mapid = "21";
UPDATE mapids SET locationname = "傑瑞德的試煉地監" WHERE mapid = "22";
UPDATE mapids SET locationname = "風木城地監:1樓" WHERE mapid = "23";
UPDATE mapids SET locationname = "風木城地監:2樓" WHERE mapid = "24";
UPDATE mapids SET locationname = "騎士洞穴:1樓" WHERE mapid = "25";
UPDATE mapids SET locationname = "騎士洞穴:2樓" WHERE mapid = "26";
UPDATE mapids SET locationname = "騎士洞穴:3樓" WHERE mapid = "27";
UPDATE mapids SET locationname = "騎士洞穴:4樓" WHERE mapid = "28";
UPDATE mapids SET locationname = "風木城內城" WHERE mapid = "29";
UPDATE mapids SET locationname = "龍之谷地監:1樓" WHERE mapid = "30";
UPDATE mapids SET locationname = "龍之谷地監:2樓" WHERE mapid = "31";
UPDATE mapids SET locationname = "龍之谷地監:3樓" WHERE mapid = "32";
UPDATE mapids SET locationname = "龍之谷地監:4樓" WHERE mapid = "33";
UPDATE mapids SET locationname = "Hall of Honor" WHERE mapid = "34";
UPDATE mapids SET locationname = "龍之谷地監" WHERE mapid = "35";
UPDATE mapids SET locationname = "龍之谷地監" WHERE mapid = "36";
UPDATE mapids SET locationname = "安塔瑞斯棲息地" WHERE mapid = "37";
UPDATE mapids SET locationname = "Hall of Honor" WHERE mapid = "38";
UPDATE mapids SET locationname = "Hall of Honor" WHERE mapid = "39";
UPDATE mapids SET locationname = "Hall of Honor" WHERE mapid = "40";
UPDATE mapids SET locationname = "Hall of Honor" WHERE mapid = "41";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "43";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "44";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "45";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "46";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "47";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "48";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "49";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "50";
UPDATE mapids SET locationname = "巨蟻洞穴" WHERE mapid = "51";
UPDATE mapids SET locationname = "ギラン城內" WHERE mapid = "52";
UPDATE mapids SET locationname = "ギランケイブ:1樓" WHERE mapid = "53";
UPDATE mapids SET locationname = "ギランケイブ:2樓" WHERE mapid = "54";
UPDATE mapids SET locationname = "ギランケイブ:3樓" WHERE mapid = "55";
UPDATE mapids SET locationname = "ギランケイブ:4樓" WHERE mapid = "56";
UPDATE mapids SET locationname = "歌う島" WHERE mapid = "57";
UPDATE mapids SET locationname = "隱された溪谷" WHERE mapid = "58";
UPDATE mapids SET locationname = "ハイネケイブ:1樓" WHERE mapid = "59";
UPDATE mapids SET locationname = "ハイネケイブ:2樓" WHERE mapid = "60";
UPDATE mapids SET locationname = "ハイネケイブ:3樓" WHERE mapid = "61";
UPDATE mapids SET locationname = "エヴァの神殿" WHERE mapid = "62";
UPDATE mapids SET locationname = "エヴァの王國" WHERE mapid = "63";
UPDATE mapids SET locationname = "ハイネ城內" WHERE mapid = "64";
UPDATE mapids SET locationname = "水龍の棲處" WHERE mapid = "65";
UPDATE mapids SET locationname = "Dwarf cave" WHERE mapid = "66";
UPDATE mapids SET locationname = "火龍の棲處" WHERE mapid = "67";
UPDATE mapids SET locationname = "歌う島" WHERE mapid = "68";
UPDATE mapids SET locationname = "隱された溪谷" WHERE mapid = "69";
UPDATE mapids SET locationname = "忘れられた島" WHERE mapid = "70";
UPDATE mapids SET locationname = "クリスタルケイブ:1樓" WHERE mapid = "72";
UPDATE mapids SET locationname = "クリスタルケイブ:2樓" WHERE mapid = "73";
UPDATE mapids SET locationname = "クリスタルケイブ:3樓" WHERE mapid = "74";
UPDATE mapids SET locationname = "象牙塔:1樓" WHERE mapid = "75";
UPDATE mapids SET locationname = "象牙塔:2樓" WHERE mapid = "76";
UPDATE mapids SET locationname = "象牙塔:3樓" WHERE mapid = "77";
UPDATE mapids SET locationname = "象牙塔:4樓" WHERE mapid = "78";
UPDATE mapids SET locationname = "象牙塔:5樓" WHERE mapid = "79";
UPDATE mapids SET locationname = "象牙塔:6樓" WHERE mapid = "80";
UPDATE mapids SET locationname = "象牙塔:7樓" WHERE mapid = "81";
UPDATE mapids SET locationname = "象牙塔:8樓" WHERE mapid = "82";
UPDATE mapids SET locationname = "Ship aden world to forgotten island" WHERE mapid = "83";
UPDATE mapids SET locationname = "Ship forgotten island to Aden world" WHERE mapid = "84";
UPDATE mapids SET locationname = "歌う島のケイブ（npcココから）" WHERE mapid = "85";
UPDATE mapids SET locationname = "歌う島のケイブ（npcクンから）" WHERE mapid = "86";
UPDATE mapids SET locationname = "パゴの部屋" WHERE mapid = "87";
UPDATE mapids SET locationname = "Giran Colosseum" WHERE mapid = "88";
UPDATE mapids SET locationname = "Giran Colosseum" WHERE mapid = "89";
UPDATE mapids SET locationname = "Giran Colosseum" WHERE mapid = "90";
UPDATE mapids SET locationname = "Talking island Colosseum" WHERE mapid = "91";
UPDATE mapids SET locationname = "Gludio Colosseum" WHERE mapid = "92";
UPDATE mapids SET locationname = "Kent Colosseum" WHERE mapid = "93";
UPDATE mapids SET locationname = "Windawood Colosseum" WHERE mapid = "94";
UPDATE mapids SET locationname = "Silver knight Colosseum" WHERE mapid = "95";
UPDATE mapids SET locationname = "Lair of Valakas Colosseum" WHERE mapid = "96";
UPDATE mapids SET locationname = "Heine Colosseum" WHERE mapid = "97";
UPDATE mapids SET locationname = "Welldone Colosseum" WHERE mapid = "98";
UPDATE mapids SET locationname = "Healper's room" WHERE mapid = "99";
UPDATE mapids SET locationname = "傲慢之塔:1樓" WHERE mapid = "101";
UPDATE mapids SET locationname = "傲慢之塔:2樓" WHERE mapid = "102";
UPDATE mapids SET locationname = "傲慢之塔:3樓" WHERE mapid = "103";
UPDATE mapids SET locationname = "傲慢之塔:4樓" WHERE mapid = "104";
UPDATE mapids SET locationname = "傲慢之塔:5樓" WHERE mapid = "105";
UPDATE mapids SET locationname = "傲慢之塔:6樓" WHERE mapid = "106";
UPDATE mapids SET locationname = "傲慢之塔:7樓" WHERE mapid = "107";
UPDATE mapids SET locationname = "傲慢之塔:8樓" WHERE mapid = "108";
UPDATE mapids SET locationname = "傲慢之塔:9樓" WHERE mapid = "109";
UPDATE mapids SET locationname = "傲慢之塔:10樓" WHERE mapid = "110";
UPDATE mapids SET locationname = "傲慢之塔:11樓" WHERE mapid = "111";
UPDATE mapids SET locationname = "傲慢之塔:12樓" WHERE mapid = "112";
UPDATE mapids SET locationname = "傲慢之塔:13樓" WHERE mapid = "113";
UPDATE mapids SET locationname = "傲慢之塔:14樓" WHERE mapid = "114";
UPDATE mapids SET locationname = "傲慢之塔:15樓" WHERE mapid = "115";
UPDATE mapids SET locationname = "傲慢之塔:16樓" WHERE mapid = "116";
UPDATE mapids SET locationname = "傲慢之塔:17樓" WHERE mapid = "117";
UPDATE mapids SET locationname = "傲慢之塔:18樓" WHERE mapid = "118";
UPDATE mapids SET locationname = "傲慢之塔:19樓" WHERE mapid = "119";
UPDATE mapids SET locationname = "傲慢之塔:20樓" WHERE mapid = "120";
UPDATE mapids SET locationname = "傲慢之塔:21樓" WHERE mapid = "121";
UPDATE mapids SET locationname = "傲慢之塔:22樓" WHERE mapid = "122";
UPDATE mapids SET locationname = "傲慢之塔:23樓" WHERE mapid = "123";
UPDATE mapids SET locationname = "傲慢之塔:24樓" WHERE mapid = "124";
UPDATE mapids SET locationname = "傲慢之塔:25樓" WHERE mapid = "125";
UPDATE mapids SET locationname = "傲慢之塔:26樓" WHERE mapid = "126";
UPDATE mapids SET locationname = "傲慢之塔:27樓" WHERE mapid = "127";
UPDATE mapids SET locationname = "傲慢之塔:28樓" WHERE mapid = "128";
UPDATE mapids SET locationname = "傲慢之塔:29樓" WHERE mapid = "129";
UPDATE mapids SET locationname = "傲慢之塔:30樓" WHERE mapid = "130";
UPDATE mapids SET locationname = "傲慢之塔:31樓" WHERE mapid = "131";
UPDATE mapids SET locationname = "傲慢之塔:32樓" WHERE mapid = "132";
UPDATE mapids SET locationname = "傲慢之塔:33樓" WHERE mapid = "133";
UPDATE mapids SET locationname = "傲慢之塔:34樓" WHERE mapid = "134";
UPDATE mapids SET locationname = "傲慢之塔:35樓" WHERE mapid = "135";
UPDATE mapids SET locationname = "傲慢之塔:36樓" WHERE mapid = "136";
UPDATE mapids SET locationname = "傲慢之塔:37樓" WHERE mapid = "137";
UPDATE mapids SET locationname = "傲慢之塔:38樓" WHERE mapid = "138";
UPDATE mapids SET locationname = "傲慢之塔:39樓" WHERE mapid = "139";
UPDATE mapids SET locationname = "傲慢之塔:40樓" WHERE mapid = "140";
UPDATE mapids SET locationname = "傲慢之塔:41樓" WHERE mapid = "141";
UPDATE mapids SET locationname = "傲慢之塔:42樓" WHERE mapid = "142";
UPDATE mapids SET locationname = "傲慢之塔:43樓" WHERE mapid = "143";
UPDATE mapids SET locationname = "傲慢之塔:44樓" WHERE mapid = "144";
UPDATE mapids SET locationname = "傲慢之塔:45樓" WHERE mapid = "145";
UPDATE mapids SET locationname = "傲慢之塔:46樓" WHERE mapid = "146";
UPDATE mapids SET locationname = "傲慢之塔:47樓" WHERE mapid = "147";
UPDATE mapids SET locationname = "傲慢之塔:48樓" WHERE mapid = "148";
UPDATE mapids SET locationname = "傲慢之塔:49樓" WHERE mapid = "149";
UPDATE mapids SET locationname = "傲慢之塔:50樓" WHERE mapid = "150";
UPDATE mapids SET locationname = "傲慢之塔:51樓" WHERE mapid = "151";
UPDATE mapids SET locationname = "傲慢之塔:52樓" WHERE mapid = "152";
UPDATE mapids SET locationname = "傲慢之塔:53樓" WHERE mapid = "153";
UPDATE mapids SET locationname = "傲慢之塔:54樓" WHERE mapid = "154";
UPDATE mapids SET locationname = "傲慢之塔:55樓" WHERE mapid = "155";
UPDATE mapids SET locationname = "傲慢之塔:56樓" WHERE mapid = "156";
UPDATE mapids SET locationname = "傲慢之塔:57樓" WHERE mapid = "157";
UPDATE mapids SET locationname = "傲慢之塔:58樓" WHERE mapid = "158";
UPDATE mapids SET locationname = "傲慢之塔:59樓" WHERE mapid = "159";
UPDATE mapids SET locationname = "傲慢之塔:60樓" WHERE mapid = "160";
UPDATE mapids SET locationname = "傲慢之塔:61樓" WHERE mapid = "161";
UPDATE mapids SET locationname = "傲慢之塔:62樓" WHERE mapid = "162";
UPDATE mapids SET locationname = "傲慢之塔:63樓" WHERE mapid = "163";
UPDATE mapids SET locationname = "傲慢之塔:64樓" WHERE mapid = "164";
UPDATE mapids SET locationname = "傲慢之塔:65樓" WHERE mapid = "165";
UPDATE mapids SET locationname = "傲慢之塔:66樓" WHERE mapid = "166";
UPDATE mapids SET locationname = "傲慢之塔:67樓" WHERE mapid = "167";
UPDATE mapids SET locationname = "傲慢之塔:68樓" WHERE mapid = "168";
UPDATE mapids SET locationname = "傲慢之塔:69樓" WHERE mapid = "169";
UPDATE mapids SET locationname = "傲慢之塔:70樓" WHERE mapid = "170";
UPDATE mapids SET locationname = "傲慢之塔:71樓" WHERE mapid = "171";
UPDATE mapids SET locationname = "傲慢之塔:72樓" WHERE mapid = "172";
UPDATE mapids SET locationname = "傲慢之塔:73樓" WHERE mapid = "173";
UPDATE mapids SET locationname = "傲慢之塔:74樓" WHERE mapid = "174";
UPDATE mapids SET locationname = "傲慢之塔:75樓" WHERE mapid = "175";
UPDATE mapids SET locationname = "傲慢之塔:76樓" WHERE mapid = "176";
UPDATE mapids SET locationname = "傲慢之塔:77樓" WHERE mapid = "177";
UPDATE mapids SET locationname = "傲慢之塔:78樓" WHERE mapid = "178";
UPDATE mapids SET locationname = "傲慢之塔:79樓" WHERE mapid = "179";
UPDATE mapids SET locationname = "傲慢之塔:80樓" WHERE mapid = "180";
UPDATE mapids SET locationname = "傲慢之塔:81樓" WHERE mapid = "181";
UPDATE mapids SET locationname = "傲慢之塔:82樓" WHERE mapid = "182";
UPDATE mapids SET locationname = "傲慢之塔:83樓" WHERE mapid = "183";
UPDATE mapids SET locationname = "傲慢之塔:84樓" WHERE mapid = "184";
UPDATE mapids SET locationname = "傲慢之塔:85樓" WHERE mapid = "185";
UPDATE mapids SET locationname = "傲慢之塔:86樓" WHERE mapid = "186";
UPDATE mapids SET locationname = "傲慢之塔:87樓" WHERE mapid = "187";
UPDATE mapids SET locationname = "傲慢之塔:88樓" WHERE mapid = "188";
UPDATE mapids SET locationname = "傲慢之塔:89樓" WHERE mapid = "189";
UPDATE mapids SET locationname = "傲慢之塔:90樓" WHERE mapid = "190";
UPDATE mapids SET locationname = "傲慢之塔:91樓" WHERE mapid = "191";
UPDATE mapids SET locationname = "傲慢之塔:92樓" WHERE mapid = "192";
UPDATE mapids SET locationname = "傲慢之塔:93樓" WHERE mapid = "193";
UPDATE mapids SET locationname = "傲慢之塔:94樓" WHERE mapid = "194";
UPDATE mapids SET locationname = "傲慢之塔:95樓" WHERE mapid = "195";
UPDATE mapids SET locationname = "傲慢之塔:96樓" WHERE mapid = "196";
UPDATE mapids SET locationname = "傲慢之塔:97樓" WHERE mapid = "197";
UPDATE mapids SET locationname = "傲慢之塔:98樓" WHERE mapid = "198";
UPDATE mapids SET locationname = "傲慢之塔:99樓" WHERE mapid = "199";
UPDATE mapids SET locationname = "傲慢之塔:100樓" WHERE mapid = "200";
UPDATE mapids SET locationname = "Mage quest dungeon" WHERE mapid = "201";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "202";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "203";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "204";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "205";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "206";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "207";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "208";
UPDATE mapids SET locationname = "Darkelf dungeon" WHERE mapid = "209";
UPDATE mapids SET locationname = "Darkelf dungeon" WHERE mapid = "210";
UPDATE mapids SET locationname = "Darkelf dungeon" WHERE mapid = "211";
UPDATE mapids SET locationname = "Darkelf dungeon" WHERE mapid = "213";
UPDATE mapids SET locationname = "Mutant ant dungeon" WHERE mapid = "217";
UPDATE mapids SET locationname = "Gerard test dungeon" WHERE mapid = "221";
UPDATE mapids SET locationname = "Jim dungeon" WHERE mapid = "237";
UPDATE mapids SET locationname = "ケント城ケイブ:1樓" WHERE mapid = "240";
UPDATE mapids SET locationname = "ケント城ケイブ:2樓" WHERE mapid = "241";
UPDATE mapids SET locationname = "ケント城ケイブ:3樓" WHERE mapid = "242";
UPDATE mapids SET locationname = "ケント城ケイブ:4樓" WHERE mapid = "243";
UPDATE mapids SET locationname = "污染された祝福の地" WHERE mapid = "244";
UPDATE mapids SET locationname = "ギラン城ケイブ:1樓" WHERE mapid = "248";
UPDATE mapids SET locationname = "ギラン城ケイブ:2樓" WHERE mapid = "249";
UPDATE mapids SET locationname = "ギラン城ケイブ:3樓" WHERE mapid = "250";
UPDATE mapids SET locationname = "ギラン城ケイブ:伯爵の部屋" WHERE mapid = "251";
UPDATE mapids SET locationname = "ハイネ城ケイブ:1樓" WHERE mapid = "252";
UPDATE mapids SET locationname = "ハイネ城ケイブ:2樓" WHERE mapid = "253";
UPDATE mapids SET locationname = "ハイネ城ケイブ:3樓" WHERE mapid = "254";
UPDATE mapids SET locationname = "ドワーフ城ケイブ:1樓" WHERE mapid = "255";
UPDATE mapids SET locationname = "ドワーフ城ケイブ:2樓" WHERE mapid = "256";
UPDATE mapids SET locationname = "アデン城ケイブ:1樓" WHERE mapid = "257";
UPDATE mapids SET locationname = "アデン城ケイブ:2樓" WHERE mapid = "258";
UPDATE mapids SET locationname = "アデン城ケイブ:3樓" WHERE mapid = "259";
UPDATE mapids SET locationname = "アデン城內" WHERE mapid = "300";
UPDATE mapids SET locationname = "地下水路" WHERE mapid = "301";
UPDATE mapids SET locationname = "セピアのダンジョン" WHERE mapid = "302";
UPDATE mapids SET locationname = "夢幻の島" WHERE mapid = "303";
UPDATE mapids SET locationname = "沈默の洞窟" WHERE mapid = "304";
UPDATE mapids SET locationname = "Elder cave" WHERE mapid = "305";
UPDATE mapids SET locationname = "Dungeon of evil thoughts" WHERE mapid = "306";
UPDATE mapids SET locationname = "地下侵攻路:1樓" WHERE mapid = "307";
UPDATE mapids SET locationname = "地下侵攻路:2樓" WHERE mapid = "308";
UPDATE mapids SET locationname = "地下侵攻路:3樓" WHERE mapid = "309";
UPDATE mapids SET locationname = "オームダンジョン" WHERE mapid = "310";
UPDATE mapids SET locationname = "ディアド要塞" WHERE mapid = "320";
UPDATE mapids SET locationname = "ブラックミスリル礦山" WHERE mapid = "330";
UPDATE mapids SET locationname = "グルーディン市場" WHERE mapid = "340";
UPDATE mapids SET locationname = "ギラン市場" WHERE mapid = "350";
UPDATE mapids SET locationname = "オーレン市場" WHERE mapid = "360";
UPDATE mapids SET locationname = "シルバーナイトタウン市場" WHERE mapid = "370";
UPDATE mapids SET locationname = "地下大空洞" WHERE mapid = "400";
UPDATE mapids SET locationname = "Large Cavern route" WHERE mapid = "401";
UPDATE mapids SET locationname = "魔族の神殿" WHERE mapid = "410";
UPDATE mapids SET locationname = "地底湖" WHERE mapid = "420";
UPDATE mapids SET locationname = "精靈の墓" WHERE mapid = "430";
UPDATE mapids SET locationname = "海賊島:前半部" WHERE mapid = "440";
UPDATE mapids SET locationname = "海賊島ケイブ:1樓" WHERE mapid = "441";
UPDATE mapids SET locationname = "海賊島ケイブ:2樓" WHERE mapid = "442";
UPDATE mapids SET locationname = "海賊島ケイブ:3樓" WHERE mapid = "443";
UPDATE mapids SET locationname = "海賊島ケイブ:4樓" WHERE mapid = "444";
UPDATE mapids SET locationname = "Hidden dock to Pirate island" WHERE mapid = "445";
UPDATE mapids SET locationname = "Ship Pirate island to Hidden dock" WHERE mapid = "446";
UPDATE mapids SET locationname = "Ship Hidden dock to Pirate island" WHERE mapid = "447";
UPDATE mapids SET locationname = "ラスタバド城:正門" WHERE mapid = "450";
UPDATE mapids SET locationname = "ラスタバド城:1階集會場" WHERE mapid = "451";
UPDATE mapids SET locationname = "ラスタバ城:突擊隊訓練場1F" WHERE mapid = "452";
UPDATE mapids SET locationname = "ラスタバ城:魔獸軍王の執務室1F" WHERE mapid = "453";
UPDATE mapids SET locationname = "ラスタバ城:野獸調教室1F" WHERE mapid = "454";
UPDATE mapids SET locationname = "ラスタバ城:野獸訓練室1F" WHERE mapid = "455";
UPDATE mapids SET locationname = "ラスタバ城:魔獸召喚室1F" WHERE mapid = "456";
UPDATE mapids SET locationname = "ラスタバ城：闇の結界1F" WHERE mapid = "457";
UPDATE mapids SET locationname = "ラスタバ城:黑魔法訓練場2F" WHERE mapid = "460";
UPDATE mapids SET locationname = "ラスタバ城:黑魔法研究室2F" WHERE mapid = "461";
UPDATE mapids SET locationname = "ラスタバ城:魔靈軍王の執務室2F" WHERE mapid = "462";
UPDATE mapids SET locationname = "ラスタバ城:魔靈軍王の書齋2F" WHERE mapid = "463";
UPDATE mapids SET locationname = "ラスタバ城:精靈召喚室2F" WHERE mapid = "464";
UPDATE mapids SET locationname = "ラスタバ城:精靈の生息地2F" WHERE mapid = "465";
UPDATE mapids SET locationname = "ラスタバ城:闇の精靈研究室2F" WHERE mapid = "466";
UPDATE mapids SET locationname = "ラスタバ城：闇の結界2F" WHERE mapid = "467";
UPDATE mapids SET locationname = "ラスタバ城：闇の結界2F" WHERE mapid = "468";
UPDATE mapids SET locationname = "ラスタバ城:惡靈の祭壇3F" WHERE mapid = "470";
UPDATE mapids SET locationname = "ラスタバ城:デビルロードの祭壇3F" WHERE mapid = "471";
UPDATE mapids SET locationname = "ラスタバ城:傭兵訓練場3F" WHERE mapid = "472";
UPDATE mapids SET locationname = "ラスタバ城:冥法軍の訓練場3F" WHERE mapid = "473";
UPDATE mapids SET locationname = "ラスタバ城:オーム實驗室3F" WHERE mapid = "474";
UPDATE mapids SET locationname = "ラスタバ城:冥法軍王の執務室3F" WHERE mapid = "475";
UPDATE mapids SET locationname = "ラスタバ城:中央コントロールルーム3F" WHERE mapid = "476";
UPDATE mapids SET locationname = "ラスタバ城:デビルロードの傭兵室3F" WHERE mapid = "477";
UPDATE mapids SET locationname = "ラスタバ城:立入禁止エリア3F" WHERE mapid = "478";
UPDATE mapids SET locationname = "海賊島:後半部" WHERE mapid = "480";
UPDATE mapids SET locationname = "Kamyla's Room" WHERE mapid = "481";
UPDATE mapids SET locationname = "Franco's Labyrinth" WHERE mapid = "482";
UPDATE mapids SET locationname = "Closed Jail of Diego" WHERE mapid = "483";
UPDATE mapids SET locationname = "Underground Jail of Jose" WHERE mapid = "484";
UPDATE mapids SET locationname = "ラスタバド城:地下訓練場" WHERE mapid = "490";
UPDATE mapids SET locationname = "ラスタバド城:地下通路" WHERE mapid = "491";
UPDATE mapids SET locationname = "ラスタバド城:暗殺軍王の執務室" WHERE mapid = "492";
UPDATE mapids SET locationname = "ラスタバド城:地下コントロールルーム" WHERE mapid = "493";
UPDATE mapids SET locationname = "ラスタバド城:地下處刑場" WHERE mapid = "494";
UPDATE mapids SET locationname = "ラスタバド城:地下決鬥場" WHERE mapid = "495";
UPDATE mapids SET locationname = "ラスタバド城:地下牢" WHERE mapid = "496";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "500";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "501";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "502";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "503";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "504";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "505";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "506";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "507";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "508";
UPDATE mapids SET locationname = "Chaos Battle Collosseum" WHERE mapid = "509";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "511";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "512";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "513";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "514";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "515";
UPDATE mapids SET locationname = "KR_Event" WHERE mapid = "516";
UPDATE mapids SET locationname = "Outer Area of Temple of Shadows" WHERE mapid = "521";
UPDATE mapids SET locationname = "1st Floor of Temple of Shadows" WHERE mapid = "522";
UPDATE mapids SET locationname = "2nd Floor of Temple of Shadows" WHERE mapid = "523";
UPDATE mapids SET locationname = "3rd Floor of Temple of Shadows" WHERE mapid = "524";
UPDATE mapids SET locationname = "ラスタバ城:グランカインの神殿/ケイナの部屋" WHERE mapid = "530";
UPDATE mapids SET locationname = "ラスタバ城:ビアタス/バロメス/エンディアスの部屋" WHERE mapid = "531";
UPDATE mapids SET locationname = "ラスタバ城:庭園/イデアの部屋" WHERE mapid = "532";
UPDATE mapids SET locationname = "ラスタバ城:ティアメス/ラミアス/バロードの部屋" WHERE mapid = "533";
UPDATE mapids SET locationname = "ラスタバ城:カサンドラ/ダンテスの部屋" WHERE mapid = "534";
UPDATE mapids SET locationname = "ダークエルフの聖地" WHERE mapid = "535";
UPDATE mapids SET locationname = "ラスタバ城:４階入り口" WHERE mapid = "536";
UPDATE mapids SET locationname = "巨蟻洞穴卵部屋A" WHERE mapid = "541";
UPDATE mapids SET locationname = "巨蟻洞穴卵部屋B" WHERE mapid = "542";
UPDATE mapids SET locationname = "巨蟻女皇棲息地" WHERE mapid = "543";
UPDATE mapids SET locationname = "船の墓場:地上層" WHERE mapid = "550";
UPDATE mapids SET locationname = "船の墓場:大型船內1F" WHERE mapid = "551";
UPDATE mapids SET locationname = "船の墓場:大型船內1F(水中)" WHERE mapid = "552";
UPDATE mapids SET locationname = "船の墓場:小型船內1F" WHERE mapid = "553";
UPDATE mapids SET locationname = "船の墓場:大型船內2F" WHERE mapid = "554";
UPDATE mapids SET locationname = "船の墓場:大型船內2F(水中)" WHERE mapid = "555";
UPDATE mapids SET locationname = "船の墓場:小型船內2F" WHERE mapid = "556";
UPDATE mapids SET locationname = "船の墓場:大型船內3F(水中)" WHERE mapid = "557";
UPDATE mapids SET locationname = "船の墓場:深海層" WHERE mapid = "558";
UPDATE mapids SET locationname = "Cave of Desire Outland" WHERE mapid = "600";
UPDATE mapids SET locationname = "Cave of Desire lobby" WHERE mapid = "601";
UPDATE mapids SET locationname = "Barlog room" WHERE mapid = "602";
UPDATE mapids SET locationname = "Barlog lair" WHERE mapid = "603";
UPDATE mapids SET locationname = "Water area" WHERE mapid = "604";
UPDATE mapids SET locationname = "Fire area" WHERE mapid = "605";
UPDATE mapids SET locationname = "Air area" WHERE mapid = "606";
UPDATE mapids SET locationname = "Earth area" WHERE mapid = "607";
UPDATE mapids SET locationname = "Yahee LAB" WHERE mapid = "608";
UPDATE mapids SET locationname = "Sakura Forest JP Event" WHERE mapid = "610";
UPDATE mapids SET locationname = "Cantonment JP Event" WHERE mapid = "611";
UPDATE mapids SET locationname = "Fruit Forest JP Event" WHERE mapid = "612";
UPDATE mapids SET locationname = "The hell" WHERE mapid = "666";
UPDATE mapids SET locationname = "memory land" WHERE mapid = "701";
UPDATE mapids SET locationname = "fallen temple" WHERE mapid = "777";
UPDATE mapids SET locationname = "fallen cave" WHERE mapid = "778";
UPDATE mapids SET locationname = "fallen cave underwater" WHERE mapid = "779";
UPDATE mapids SET locationname = "テーベ砂漠" WHERE mapid = "780";
UPDATE mapids SET locationname = "テーベ ピラミッド內部" WHERE mapid = "781";
UPDATE mapids SET locationname = "テーベ オシリス祭壇" WHERE mapid = "782";
UPDATE mapids SET locationname = "Unknown" WHERE mapid = "997";
UPDATE mapids SET locationname = "Hall of Honor" WHERE mapid = "998";
UPDATE mapids SET locationname = "シルベリア" WHERE mapid = "1000";
UPDATE mapids SET locationname = "ベヒモス" WHERE mapid = "1001";
UPDATE mapids SET locationname = "古代の空間:1樓" WHERE mapid = "2000";
UPDATE mapids SET locationname = "古代の空間:2樓" WHERE mapid = "2001";
UPDATE mapids SET locationname = "古代の空間:3樓" WHERE mapid = "2002";
UPDATE mapids SET locationname = "古代の空間:4樓" WHERE mapid = "2003";
UPDATE mapids SET locationname = "新試練" WHERE mapid = "2004";
UPDATE mapids SET locationname = "KR_EVENT" WHERE mapid = "4941";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5001";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5002";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5003";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5004";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5005";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5006";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5007";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5008";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5009";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5010";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5011";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5012";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5013";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5014";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5015";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5016";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5017";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5018";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5019";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5020";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5021";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5022";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5023";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5024";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5025";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5026";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5027";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5028";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5029";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5030";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5031";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5032";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5033";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5034";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5035";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5036";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5037";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5038";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5039";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5040";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5041";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5042";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5043";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5044";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5045";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5046";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5047";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5048";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5049";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5050";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5051";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5052";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5053";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5054";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5055";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5056";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5057";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5058";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5059";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5060";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5061";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5062";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5063";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5064";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5065";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5066";
UPDATE mapids SET locationname = "Aden Underground house" WHERE mapid = "5067";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5068";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5069";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5070";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5071";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5072";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5073";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5074";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5075";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5076";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5077";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5078";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5079";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5080";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5081";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5082";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5083";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5084";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5085";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5086";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5087";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5088";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5089";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5090";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5091";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5092";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5093";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5094";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5095";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5096";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5097";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5098";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5099";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5100";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5101";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5102";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5103";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5104";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5105";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5106";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5107";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5108";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5109";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5110";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5111";
UPDATE mapids SET locationname = "Giran Underground house" WHERE mapid = "5112";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5113";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5114";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5115";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5116";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5117";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5118";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5119";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5120";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5121";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5122";
UPDATE mapids SET locationname = "Heine Underground house" WHERE mapid = "5123";
UPDATE mapids SET locationname = "Fishing place" WHERE mapid = "5124";
UPDATE mapids SET locationname = "petmatch place" WHERE mapid = "5125";
UPDATE mapids SET locationname = "petmatch place" WHERE mapid = "5131";
UPDATE mapids SET locationname = "petmatch place" WHERE mapid = "5132";
UPDATE mapids SET locationname = "petmatch place" WHERE mapid = "5133";
UPDATE mapids SET locationname = "petmatch place" WHERE mapid = "5134";
UPDATE mapids SET locationname = "Ghost house" WHERE mapid = "5140";
UPDATE mapids SET locationname = "Singing island TW Event" WHERE mapid = "5701";
UPDATE mapids SET locationname = "Hidden valley TW Event" WHERE mapid = "5801";
UPDATE mapids SET locationname = "Hidden valley TW Event" WHERE mapid = "5802";
UPDATE mapids SET locationname = "Hidden valley TW Event" WHERE mapid = "5803";
UPDATE mapids SET locationname = "Hidden valley TW Event" WHERE mapid = "5804";
UPDATE mapids SET locationname = "Hidden valley TW Event" WHERE mapid = "5805";
UPDATE mapids SET locationname = "EventForest JP Event" WHERE mapid = "7000";
UPDATE mapids SET locationname = "The hell JP Event" WHERE mapid = "7001";
UPDATE mapids SET locationname = "Sin Temple JP Event" WHERE mapid = "7002";
UPDATE mapids SET locationname = "Sin Temple JP Event" WHERE mapid = "7003";
UPDATE mapids SET locationname = "Sin Temple JP Event" WHERE mapid = "7004";
UPDATE mapids SET locationname = "Sin Temple JP Event" WHERE mapid = "7005";
UPDATE mapids SET locationname = "Sin Temple JP Event" WHERE mapid = "7006";
UPDATE mapids SET locationname = "Sin Tomb JP Event" WHERE mapid = "7007";
UPDATE mapids SET locationname = "Sin Tomb JP Event" WHERE mapid = "7008";
UPDATE mapids SET locationname = "Sin Tomb JP Event" WHERE mapid = "7009";
UPDATE mapids SET locationname = "Sin Tomb JP Event" WHERE mapid = "7010";
UPDATE mapids SET locationname = "Sin Tomb JP Event" WHERE mapid = "7011";
UPDATE mapids SET locationname = "EventForest JP Event" WHERE mapid = "7051";
UPDATE mapids SET locationname = "EventForest JP Event" WHERE mapid = "7052";
UPDATE mapids SET locationname = "EventForest JP Event" WHERE mapid = "7053";
UPDATE mapids SET locationname = "EventForest JP Event" WHERE mapid = "7054";
UPDATE mapids SET locationname = "EventForest JP Event" WHERE mapid = "7055";
UPDATE mapids SET locationname = "歌う島" WHERE mapid = "8011";
UPDATE mapids SET locationname = "歌う島:西部" WHERE mapid = "8012";
UPDATE mapids SET locationname = "ドロモンドの部屋" WHERE mapid = "8013";
UPDATE mapids SET locationname = "訓練場" WHERE mapid = "8014";
UPDATE mapids SET locationname = "歌う島:北部" WHERE mapid = "8015";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "16384";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "16896";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "17408";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "17492";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "17820";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "17920";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "18432";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "18944";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "19456";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "19968";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "20480";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "20992";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "21504";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "22016";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "22528";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "23040";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "23552";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "24064";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "24576";
UPDATE mapids SET locationname = "InnRoom" WHERE mapid = "25088";
