UPDATE weapon_skill SET note = "沉默之劍" WHERE weapon_id = "47";
UPDATE weapon_skill SET note = "克特之劍" WHERE weapon_id = "54";
UPDATE weapon_skill SET note = "死亡騎士的烈炎之劍" WHERE weapon_id = "58";
UPDATE weapon_skill SET note = "倫得雙刀" WHERE weapon_id = "76";
UPDATE weapon_skill SET note = "冰之女王魔杖" WHERE weapon_id = "121";
UPDATE weapon_skill SET note = "炎魔雙手劍  Lv.8" WHERE weapon_id = "203";
UPDATE weapon_skill SET note = "熾炎天使弓" WHERE weapon_id = "205";
UPDATE weapon_skill SET note = "萬聖節南瓜長劍(韓)" WHERE weapon_id = "256";
UPDATE weapon_skill SET note = "萬聖節南瓜長劍(日)" WHERE weapon_id = "257";
UPDATE weapon_skill SET note = "終極萬聖節南瓜長劍" WHERE weapon_id = "258";
