/*
 * 中文化 spawnlist_boss 資料表
 * By Impreza8837
 */
UPDATE spawnlist_boss SET location = "シーシンガー" WHERE id = "1";
UPDATE spawnlist_boss SET location = "タイガー Lv5" WHERE id = "2";
UPDATE spawnlist_boss SET location = "バンディット(トライ ソウル)" WHERE id = "3";
UPDATE spawnlist_boss SET location = "クロコダイル Lv32" WHERE id = "4";
UPDATE spawnlist_boss SET location = "バンディット ボス" WHERE id = "5";
UPDATE spawnlist_boss SET location = "バンディット ボス" WHERE id = "6";
UPDATE spawnlist_boss SET location = "バンディット ボス" WHERE id = "7";
UPDATE spawnlist_boss SET location = "バンディット ボス" WHERE id = "8";
UPDATE spawnlist_boss SET location = "バンディット ボス" WHERE id = "9";
UPDATE spawnlist_boss SET location = "ネクロマンサー" WHERE id = "10";
UPDATE spawnlist_boss SET location = "ドレイク" WHERE id = "11";
UPDATE spawnlist_boss SET location = "カスパー" WHERE id = "17";
UPDATE spawnlist_boss SET location = "シュノーヴァ Lv44" WHERE id = "18";
UPDATE spawnlist_boss SET location = "マンボ ラビット 海賊島" WHERE id = "19";
UPDATE spawnlist_boss SET location = "ゼニス クイーン" WHERE id = "21";
UPDATE spawnlist_boss SET location = "イフリート" WHERE id = "22";
UPDATE spawnlist_boss SET location = "イフリート" WHERE id = "23";
UPDATE spawnlist_boss SET location = "イフリート" WHERE id = "24";
UPDATE spawnlist_boss SET location = "イフリート" WHERE id = "25";
UPDATE spawnlist_boss SET location = "ドレイク" WHERE id = "26";
UPDATE spawnlist_boss SET location = "ドレイク" WHERE id = "27";
UPDATE spawnlist_boss SET location = "ドレイク" WHERE id = "28";
UPDATE spawnlist_boss SET location = "ドレイク" WHERE id = "29";
UPDATE spawnlist_boss SET location = "マンボ ラビット" WHERE id = "30";
UPDATE spawnlist_boss SET location = "ブラック エルダー" WHERE id = "31";
UPDATE spawnlist_boss SET location = "ブラック エルダー" WHERE id = "32";
UPDATE spawnlist_boss SET location = "ドッペルゲンガー" WHERE id = "33";
UPDATE spawnlist_boss SET location = "シアー" WHERE id = "34";
UPDATE spawnlist_boss SET location = "バフォメット" WHERE id = "35";
UPDATE spawnlist_boss SET location = "ベレス" WHERE id = "36";
UPDATE spawnlist_boss SET location = "グレート ミノタウルス" WHERE id = "37";
UPDATE spawnlist_boss SET location = "カーツ" WHERE id = "38";
UPDATE spawnlist_boss SET location = "デスナイト" WHERE id = "39";
UPDATE spawnlist_boss SET location = "バンパイア" WHERE id = "42";
UPDATE spawnlist_boss SET location = "アイス クイーン" WHERE id = "43";
UPDATE spawnlist_boss SET location = "エンシェント ジャイアント" WHERE id = "44";
UPDATE spawnlist_boss SET location = "ジャイアント アント クイーン" WHERE id = "45";
UPDATE spawnlist_boss SET location = "フェニックス" WHERE id = "46";
UPDATE spawnlist_boss SET location = "ナイトバルド" WHERE id = "47";
UPDATE spawnlist_boss SET location = "混沌" WHERE id = "48";
UPDATE spawnlist_boss SET location = "ユニコーン" WHERE id = "49";
UPDATE spawnlist_boss SET location = "地の大精霊" WHERE id = "50";
UPDATE spawnlist_boss SET location = "水の大精霊" WHERE id = "51";
UPDATE spawnlist_boss SET location = "風の大精霊" WHERE id = "52";
UPDATE spawnlist_boss SET location = "火の大精霊" WHERE id = "53";
UPDATE spawnlist_boss SET location = "深淵の主" WHERE id = "54";
UPDATE spawnlist_boss SET location = "デーモン" WHERE id = "55";
UPDATE spawnlist_boss SET location = "ゾンビ ロード" WHERE id = "56";
UPDATE spawnlist_boss SET location = "バランカ" WHERE id = "57";
UPDATE spawnlist_boss SET location = "クーガー" WHERE id = "58";
UPDATE spawnlist_boss SET location = "マミーロード" WHERE id = "59";
UPDATE spawnlist_boss SET location = "アイリス" WHERE id = "60";
UPDATE spawnlist_boss SET location = "アリオク" WHERE id = "61";
UPDATE spawnlist_boss SET location = "リッチ" WHERE id = "62";
UPDATE spawnlist_boss SET location = "グリムリーパー" WHERE id = "63";
UPDATE spawnlist_boss SET location = "死" WHERE id = "64";
UPDATE spawnlist_boss SET location = "ヤヒ" WHERE id = "65";
UPDATE spawnlist_boss SET location = "ケンラウヘル" WHERE id = "68";
UPDATE spawnlist_boss SET location = "リンドビオル" WHERE id = "69";
UPDATE spawnlist_boss SET location = "アンタラス" WHERE id = "70";
UPDATE spawnlist_boss SET location = "パプリオン" WHERE id = "71";
UPDATE spawnlist_boss SET location = "ヴァラカス" WHERE id = "72";
UPDATE spawnlist_boss SET location = "堕落" WHERE id = "73";
UPDATE spawnlist_boss SET location = "紀州犬の子犬 Lv5" WHERE id = "74";
UPDATE spawnlist_boss SET location = "紀州犬の子犬 Lv5" WHERE id = "75";
UPDATE spawnlist_boss SET location = "紀州犬の子犬 Lv5" WHERE id = "76";
UPDATE spawnlist_boss SET location = "紀州犬の子犬 Lv5" WHERE id = "77";
UPDATE spawnlist_boss SET location = "紀州犬の子犬 Lv5" WHERE id = "78";
UPDATE spawnlist_boss SET location = "紀州犬の子犬 Lv5" WHERE id = "79";
UPDATE spawnlist_boss SET location = "紀州犬の子犬 Lv5" WHERE id = "80";
UPDATE spawnlist_boss SET location = "大王イカ" WHERE id = "81";
UPDATE spawnlist_boss SET location = "半魚人の長" WHERE id = "82";
UPDATE spawnlist_boss SET location = "バルログ" WHERE id = "83";
UPDATE spawnlist_boss SET location = "汚れたオーク ウォリアー" WHERE id = "84";
UPDATE spawnlist_boss SET location = "スピリッド" WHERE id = "85";
UPDATE spawnlist_boss SET location = "マイノ シャーマンのダイア ゴーレム" WHERE id = "86";
UPDATE spawnlist_boss SET location = "マイノ シャーマン" WHERE id = "87";
UPDATE spawnlist_boss SET location = "バルバドス" WHERE id = "88";
UPDATE spawnlist_boss SET location = "パプリオンの信奉者" WHERE id = "89";
UPDATE spawnlist_boss SET location = "パプリオンの信奉者" WHERE id = "90";
UPDATE spawnlist_boss SET location = "ホセ" WHERE id = "91";
UPDATE spawnlist_boss SET location = "暗殺団長 ブレイズ" WHERE id = "92";
UPDATE spawnlist_boss SET location = "親衛隊長 カイト" WHERE id = "93";
UPDATE spawnlist_boss SET location = "暗殺軍王 スレイヴ" WHERE id = "94";
UPDATE spawnlist_boss SET location = "旅団長 ダークパンサー" WHERE id = "95";
UPDATE spawnlist_boss SET location = "魔獣軍王 バランカ" WHERE id = "96";
UPDATE spawnlist_boss SET location = "師団長 シンクレア" WHERE id = "97";
UPDATE spawnlist_boss SET location = "魔獣団長 カイバール" WHERE id = "98";
UPDATE spawnlist_boss SET location = "神官長 バウンティ" WHERE id = "99";
UPDATE spawnlist_boss SET location = "魔法団長 カルミエル" WHERE id = "100";
UPDATE spawnlist_boss SET location = "魔霊軍王 ライア" WHERE id = "101";
UPDATE spawnlist_boss SET location = "傭兵隊長 メファイスト" WHERE id = "102";
UPDATE spawnlist_boss SET location = "冥法団長 クリファス" WHERE id = "103";
UPDATE spawnlist_boss SET location = "冥法軍王 ヘルバイン" WHERE id = "104";
UPDATE spawnlist_boss SET location = "伯爵親衛隊長" WHERE id = "105";
UPDATE spawnlist_boss SET location = "タロス伯爵" WHERE id = "106";
UPDATE spawnlist_boss SET location = "マモン" WHERE id = "107";
UPDATE spawnlist_boss SET location = "黒魔術師 マヤ" WHERE id = "108";
UPDATE spawnlist_boss SET location = "呪われたメデューサ" WHERE id = "109";
UPDATE spawnlist_boss SET location = "呪われた水の大精霊" WHERE id = "110";
UPDATE spawnlist_boss SET location = "呪われた巫女 サエル" WHERE id = "111";
UPDATE spawnlist_boss SET location = "水の精霊" WHERE id = "112";
UPDATE spawnlist_boss SET location = "カープ" WHERE id = "113";
UPDATE spawnlist_boss SET location = "ジャイアント ワーム" WHERE id = "114";
UPDATE spawnlist_boss SET location = "大法官 ケイナ" WHERE id = "115";
UPDATE spawnlist_boss SET location = "大法官 ビアタス" WHERE id = "116";
UPDATE spawnlist_boss SET location = "大法官 バロメス" WHERE id = "117";
UPDATE spawnlist_boss SET location = "大法官 エンディアス" WHERE id = "118";
UPDATE spawnlist_boss SET location = "大法官 イデア" WHERE id = "119";
UPDATE spawnlist_boss SET location = "大法官 ティアメス" WHERE id = "120";
UPDATE spawnlist_boss SET location = "大法官 ラミアス" WHERE id = "121";
UPDATE spawnlist_boss SET location = "大法官 バロード" WHERE id = "122";
UPDATE spawnlist_boss SET location = "副祭祀長 カサンドラ" WHERE id = "123";
UPDATE spawnlist_boss SET location = "テーベ アヌビス" WHERE id = "124";
UPDATE spawnlist_boss SET location = "テーベ ホルス" WHERE id = "125";
UPDATE spawnlist_boss SET location = "アイス クイーン" WHERE id = "126";
UPDATE spawnlist_boss SET location = "アイス デーモン" WHERE id = "127";
