/*
 * 中文化 spawnlist_boss 資料表
 * By Impreza8837
 */
UPDATE spawnlist_boss SET location = "海之歌姬" WHERE id = "1";
UPDATE spawnlist_boss SET location = "虎男 Lv5" WHERE id = "2";
UPDATE spawnlist_boss SET location = "強盜(三個)" WHERE id = "3";
UPDATE spawnlist_boss SET location = "巨大鱷魚 Lv32" WHERE id = "4";
UPDATE spawnlist_boss SET location = "強盜頭目" WHERE id = "5";
UPDATE spawnlist_boss SET location = "強盜頭目" WHERE id = "6";
UPDATE spawnlist_boss SET location = "強盜頭目" WHERE id = "7";
UPDATE spawnlist_boss SET location = "強盜頭目" WHERE id = "8";
UPDATE spawnlist_boss SET location = "強盜頭目" WHERE id = "9";
UPDATE spawnlist_boss SET location = "魔法師" WHERE id = "10";
UPDATE spawnlist_boss SET location = "飛龍" WHERE id = "11";
UPDATE spawnlist_boss SET location = "卡士伯" WHERE id = "17";
UPDATE spawnlist_boss SET location = "庫曼 Lv44" WHERE id = "18";
UPDATE spawnlist_boss SET location = "曼波兔 海賊島" WHERE id = "19";
UPDATE spawnlist_boss SET location = "潔尼斯女王" WHERE id = "21";
UPDATE spawnlist_boss SET location = "艾弗力特" WHERE id = "22";
UPDATE spawnlist_boss SET location = "艾弗力特" WHERE id = "23";
UPDATE spawnlist_boss SET location = "艾弗力特" WHERE id = "24";
UPDATE spawnlist_boss SET location = "艾弗力特" WHERE id = "25";
UPDATE spawnlist_boss SET location = "飛龍" WHERE id = "26";
UPDATE spawnlist_boss SET location = "飛龍" WHERE id = "27";
UPDATE spawnlist_boss SET location = "飛龍" WHERE id = "28";
UPDATE spawnlist_boss SET location = "飛龍" WHERE id = "29";
UPDATE spawnlist_boss SET location = "曼波兔" WHERE id = "30";
UPDATE spawnlist_boss SET location = "黑長者" WHERE id = "31";
UPDATE spawnlist_boss SET location = "黑長者" WHERE id = "32";
UPDATE spawnlist_boss SET location = "變形怪" WHERE id = "33";
UPDATE spawnlist_boss SET location = "幻象眼魔" WHERE id = "34";
UPDATE spawnlist_boss SET location = "巴風特" WHERE id = "35";
UPDATE spawnlist_boss SET location = "巴列斯" WHERE id = "36";
UPDATE spawnlist_boss SET location = "巨大牛人" WHERE id = "37";
UPDATE spawnlist_boss SET location = "克特" WHERE id = "38";
UPDATE spawnlist_boss SET location = "死亡騎士" WHERE id = "39";
UPDATE spawnlist_boss SET location = "吸血鬼" WHERE id = "42";
UPDATE spawnlist_boss SET location = "冰之女王" WHERE id = "43";
UPDATE spawnlist_boss SET location = "古代巨人" WHERE id = "44";
UPDATE spawnlist_boss SET location = "巨蟻女皇" WHERE id = "45";
UPDATE spawnlist_boss SET location = "不死鳥" WHERE id = "46";
UPDATE spawnlist_boss SET location = "騎士范德" WHERE id = "47";
UPDATE spawnlist_boss SET location = "混沌" WHERE id = "48";
UPDATE spawnlist_boss SET location = "獨角獸" WHERE id = "49";
UPDATE spawnlist_boss SET location = "土精靈王" WHERE id = "50";
UPDATE spawnlist_boss SET location = "水精靈王" WHERE id = "51";
UPDATE spawnlist_boss SET location = "風精靈王" WHERE id = "52";
UPDATE spawnlist_boss SET location = "火精靈王" WHERE id = "53";
UPDATE spawnlist_boss SET location = "深淵之主" WHERE id = "54";
UPDATE spawnlist_boss SET location = "惡魔" WHERE id = "55";
UPDATE spawnlist_boss SET location = "殭屍王" WHERE id = "56";
UPDATE spawnlist_boss SET location = "巴蘭卡" WHERE id = "57";
UPDATE spawnlist_boss SET location = "黑豹" WHERE id = "58";
UPDATE spawnlist_boss SET location = "木乃伊王" WHERE id = "59";
UPDATE spawnlist_boss SET location = "艾莉絲" WHERE id = "60";
UPDATE spawnlist_boss SET location = "阿利歐克" WHERE id = "61";
UPDATE spawnlist_boss SET location = "巫妖" WHERE id = "62";
UPDATE spawnlist_boss SET location = "鐮刀死神" WHERE id = "63";
UPDATE spawnlist_boss SET location = "死亡" WHERE id = "64";
UPDATE spawnlist_boss SET location = "火焰之影" WHERE id = "65";
UPDATE spawnlist_boss SET location = "反王肯恩" WHERE id = "68";
UPDATE spawnlist_boss SET location = "林德拜爾" WHERE id = "69";
UPDATE spawnlist_boss SET location = "安塔瑞斯" WHERE id = "70";
UPDATE spawnlist_boss SET location = "法利昂" WHERE id = "71";
UPDATE spawnlist_boss SET location = "巴拉卡斯" WHERE id = "72";
UPDATE spawnlist_boss SET location = "墮落" WHERE id = "73";
UPDATE spawnlist_boss SET location = "高麗幼犬 Lv5" WHERE id = "74";
UPDATE spawnlist_boss SET location = "高麗幼犬 Lv5" WHERE id = "75";
UPDATE spawnlist_boss SET location = "高麗幼犬 Lv5" WHERE id = "76";
UPDATE spawnlist_boss SET location = "高麗幼犬 Lv5" WHERE id = "77";
UPDATE spawnlist_boss SET location = "高麗幼犬 Lv5" WHERE id = "78";
UPDATE spawnlist_boss SET location = "高麗幼犬 Lv5" WHERE id = "79";
UPDATE spawnlist_boss SET location = "高麗幼犬 Lv5" WHERE id = "80";
UPDATE spawnlist_boss SET location = "大王烏賊" WHERE id = "81";
UPDATE spawnlist_boss SET location = "半魚人首領" WHERE id = "82";
UPDATE spawnlist_boss SET location = "炎魔" WHERE id = "83";
UPDATE spawnlist_boss SET location = "污濁妖魔戰士" WHERE id = "84";
UPDATE spawnlist_boss SET location = "樹精" WHERE id = "85";
UPDATE spawnlist_boss SET location = "瑪依奴夏門的鑽石高崙" WHERE id = "86";
UPDATE spawnlist_boss SET location = "瑪依奴夏門" WHERE id = "87";
UPDATE spawnlist_boss SET location = "巴貝多" WHERE id = "88";
UPDATE spawnlist_boss SET location = "法利昂的信奉者" WHERE id = "89";
UPDATE spawnlist_boss SET location = "法利昂的信奉者" WHERE id = "90";
UPDATE spawnlist_boss SET location = "豪勢" WHERE id = "91";
UPDATE spawnlist_boss SET location = "暗殺團長．布雷哲" WHERE id = "92";
UPDATE spawnlist_boss SET location = "親衛隊長．凱特" WHERE id = "93";
UPDATE spawnlist_boss SET location = "暗殺軍王．史雷佛" WHERE id = "94";
UPDATE spawnlist_boss SET location = "突擊旅長．闇黑劍士" WHERE id = "95";
UPDATE spawnlist_boss SET location = "魔獸軍王．巴蘭卡" WHERE id = "96";
UPDATE spawnlist_boss SET location = "魔獸師長．辛克萊" WHERE id = "97";
UPDATE spawnlist_boss SET location = "魔獸團長．凱巴勒" WHERE id = "98";
UPDATE spawnlist_boss SET location = "神官長．邦妮" WHERE id = "99";
UPDATE spawnlist_boss SET location = "魔法團長．卡勒米爾" WHERE id = "100";
UPDATE spawnlist_boss SET location = "法令軍王．蕾雅" WHERE id = "101";
UPDATE spawnlist_boss SET location = "傭兵隊長．麥帕斯托" WHERE id = "102";
UPDATE spawnlist_boss SET location = "冥法團長．可利波斯" WHERE id = "103";
UPDATE spawnlist_boss SET location = "冥法軍王．海露拜" WHERE id = "104";
UPDATE spawnlist_boss SET location = "伯爵的親衛隊" WHERE id = "105";
UPDATE spawnlist_boss SET location = "塔洛斯伯爵" WHERE id = "106";
UPDATE spawnlist_boss SET location = "曼孟" WHERE id = "107";
UPDATE spawnlist_boss SET location = "瑪雅" WHERE id = "108";
UPDATE spawnlist_boss SET location = "受詛咒的梅杜莎" WHERE id = "109";
UPDATE spawnlist_boss SET location = "受詛咒的水精靈王" WHERE id = "110";
UPDATE spawnlist_boss SET location = "受詛咒的巫女莎爾" WHERE id = "111";
UPDATE spawnlist_boss SET location = "水之精靈" WHERE id = "112";
UPDATE spawnlist_boss SET location = "卡普" WHERE id = "113";
UPDATE spawnlist_boss SET location = "巨大蜈蚣" WHERE id = "114";
UPDATE spawnlist_boss SET location = "長老．琪娜" WHERE id = "115";
UPDATE spawnlist_boss SET location = "長老．巴塔斯" WHERE id = "116";
UPDATE spawnlist_boss SET location = "長老．巴洛斯" WHERE id = "117";
UPDATE spawnlist_boss SET location = "長老．安迪斯" WHERE id = "118";
UPDATE spawnlist_boss SET location = "長老．艾迪爾" WHERE id = "119";
UPDATE spawnlist_boss SET location = "長老．泰瑪斯" WHERE id = "120";
UPDATE spawnlist_boss SET location = "長老．拉曼斯" WHERE id = "121";
UPDATE spawnlist_boss SET location = "長老．巴陸德" WHERE id = "122";
UPDATE spawnlist_boss SET location = "副神官．卡山德拉" WHERE id = "123";
UPDATE spawnlist_boss SET location = "底比斯 阿努比斯" WHERE id = "124";
UPDATE spawnlist_boss SET location = "底比斯 賀洛斯" WHERE id = "125";
UPDATE spawnlist_boss SET location = "冰之女王" WHERE id = "126";
UPDATE spawnlist_boss SET location = "冰魔" WHERE id = "127";
